### ISSUE TITLE
Outgoing webhook "File uploaded" doesn't work in versions 0.64.2, 0.65.x, 0.66.x

### ISSUE THREAD

**Issue by staltrans** [RocketChat/Rocket.Chat#11282]
Starting with version 0.64.2, the outgoing webhook "upload uploaded" does not work.
<del>In versions 0.66.x did not check</del>

Web-hook settings:

Event Trigger: "File Uploaded"
Enabled: True
Channel: all_private_groups
URLs: https://myapp.example.com/
Impersonate User: False
Post as: mr.robot
Script Enabled: False

The data which i get in my application from Rocket.Chat 0.63.3 when triggered webhook

```
$data =
'{
	"token": "tokenid",
	"bot": false,
	"channel_id": "wyrnets5dre3CcuCf",
	"channel_name": "t9750_test",
	"message_id": "McyDnmuxHu72cdCLC",
	"timestamp": "2018-06-28T06:03:42.347Z",
	"user_id": "userid",
	"user_name": "noname.noname",
	"text": "",
	"user": {
		"_id": "userid",
		"createdAt": "2016-09-22T19:29:36.010Z",
		"username": "noname.noname",
		"emails": [{
			"address": "admin@example.com",
			"verified": true
		}],
		"type": "user",
		"status": "online",
		"active": true,
		"roles": ["user", "admin"],
		"_updatedAt": "2018-06-28T05:00:49.416Z",
		"name": "Noname",
		"ldap": true,
		"lastLogin": "2018-06-28T05:00:49.342Z",
		"statusConnection": "online",
		"utcOffset": 5,
		"settings": {
			"preferences": {
				"desktopNotifications": "all",
				"unreadRoomsMode": true,
				"convertAsciiEmoji": true,
				"sendOnEnter": "normal",
				"hideFlexTab": false,
				"mobileNotifications": "all",
				"roomsListExhibitionMode": "unread",
				"roomCounterSidebar": true,
				"newMessageNotification": "chime",
				"autoImageLoad": true,
				"saveMobileBandwidth": true,
				"hideRoles": false,
				"desktopNotificationDuration": 60,
				"emailNotificationMode": "disabled",
				"hideUsernames": false,
				"collapseMediaByDefault": false,
				"hideAvatars": false,
				"useEmojis": true,
				"newRoomNotification": "door",
				"unreadAlert": true,
				"sidebarViewMode": "condensed",
				"sidebarShowUnread": true,
				"sidebarShowFavorites": true,
				"mergeChannels": false,
				"sidebarHideAvatar": true
			}
		},
		"language": "ru",
		"statusDefault": "online",
		"avatarOrigin": "upload"
	},
	"room": {
		"_id": "wyrnets5dre3CcuCf",
		"name": "t9750_test",
		"fname": "t9750_test",
		"t": "p",
		"msgs": 2,
		"u": {
			"_id": "ppkBMFn85rkwhKmzT",
			"username": "mr.robot"
		},
		"customFields": {},
		"ts": "2018-06-28T06:03:30.810Z",
		"ro": false,
		"sysMes": true,
		"_updatedAt": "2018-06-28T06:03:31.223Z",
		"topic": "topic": ["this_will_be_filled_in_with_usernames_when_replayed"]
	},
	"message": {
		"_id": "McyDnmuxHu72cdCLC",
		"rid": "wyrnets5dre3CcuCf",
		"ts": "2018-06-28T06:03:42.347Z",
		"msg": "",
		"file": {
			"_id": "QstBGu6DkWM2CkDFw",
			"name": "Screenshot_242.png",
			"type": "image/png"
		},
		"groupable": false,
		"attachments": [{
			"title": "Screenshot_242.png",
			"type": "file",
			"description": "",
			"title_link": "/file-upload/QstBGu6DkWM2CkDFw/Screenshot_242.png",
			"title_link_download": true,
			"image_url": "/file-upload/QstBGu6DkWM2CkDFw/Screenshot_242.png",
			"image_type": "image/png",
			"image_size": 12074,
			"image_preview": "base62preview"
		}],
		"alias": "Noname",
		"u": {
			"_id": "userid",
			"username": "noname.noname",
			"name": "Noname"
		},
		"unread": true,
		"mentions": [],
		"channels": [],
		"_updatedAt": "2018-06-28T06:03:42.385Z"
	},
	"alias": "Noname"
}'
```

After updating Rocket.Chat to versions 0.64.2, 0.65.x, 0.66.x, I don't get any data when a hook is triggered.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.64.2, 0.65.x, 0.66.x
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: enable
- NodeJS Version: v8.9.3
- MongoDB Version: v3.6.5

**Comment by staltrans** [comment]
Fixed in [0.69.0-rc.0](https://github.com/RocketChat/Rocket.Chat/tree/0.69.0-rc.0)

**Comment by Elintondm** [comment]
This problem came back in version 2.2.1. Text messages trigger the webhook, but file messages don't.
