### ISSUE TITLE
Real Name setting no longer works properly

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#11464]
### Description:

When sending a message to a contact in the list and the Real Name setting is turned on, the contact's short (user) name appears, replacing the real name. The rest of the other contacts remain with real names. The Real Name setting remains True.
### Steps to reproduce:

1. Ensure the Real Names property is set to True and that the contacts are showing with Real Names.
2. Try to send a direct message to a contact.
3. Their name will change to the user name.
4. Verify that the Real Name setting under Layout -> User Interface is still true.

### Expected behavior:

Real Names should be shown all through out interface if turned on.

### Actual behavior:

Short names replace the Real Names.

![image](https://user-images.githubusercontent.com/14616851/42728293-edd01746-877c-11e8-8b17-d43fc6839154.png)
![image](https://user-images.githubusercontent.com/14616851/42728299-1e801738-877d-11e8-8d71-8bc43f45cedb.png)
![image](https://user-images.githubusercontent.com/14616851/42728313-6f9fbe48-877d-11e8-8860-f784de89b173.png)

### Rocket.Chat (docker container)

| Version                 | 0.67.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 129                                                       |
| Database Migration Date | Sat Jul 14 2018 14:59:39 GMT-0500 (Central Daylight Time) |
| Installed at            | Tue Jul 03 2018 10:28:32 GMT-0500 (Central Daylight Time) |
| Uptime                  | 23 seconds                                                |
| Deployment ID           | wecGmPkstnsm2e7ge                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | 7380e46cf00dd5362ffc76757a1c51378460ad64                   |
| ------- | ---------------------------------------------------------- |
| Date    | Fri Jul 13 23:53:26 2018 -0300                             |
| Branch  | develop                                                    |
| Tag     | 0.66.3                                                     |
| Author  | Diego Sampaio                                              |
| Subject | [NEW] Accept resumeToken as query param to log in (#11443) |

### Runtime Environment

| OS Type         | Linux                                  |
| --------------- | -------------------------------------- |
| OS Platform     | linux                                  |
| OS Arch         | x64                                    |
| OS Release      | 4.15.0-24-generic                      |
| Node Version    | v8.11.3                                |
| OS Uptime       | 6 days, 20 hours, 4 minutes, 9 seconds |
| OS Load Average | 1.86, 0.99, 0.39                       |
| OS Total Memory | 3.85 GB                                |
| OS Free Memory  | 238.32 MB                              |
| OS CPU Count    | 4                                      |

**Comment by rodrigok** [comment]
May be related to https://github.com/RocketChat/Rocket.Chat/issues/11481

**Comment by ggazzo** [comment]
@bkraul could you reproduce on `develop` branch? I think I fixed this issue

**Comment by ahartlaub** [comment]
FYI - Sorry I didnt include the extra details; exact same scenario as above with @bkraul 

Just pulled latest docker image and it's still present (in develop branch)

`Rocket.Chat
Version	0.67.0-develop
Database Migration	129
Database Migration Date	Thu Jul 19 2018 10:42:55 GMT-0500 (Central Daylight Time)
Installed at	Fri Mar 09 2018 07:52:41 GMT-0600 (Central Standard Time)
Uptime	57 seconds
Deployment ID	78kwj823sQbcBB9uk
PID	1
Running Instances	1
OpLog	Disabled
Commit
Hash	48e7fc373ae6f24e14038e1631ddb48c89a100ea
Date	Thu Jul 19 15:39:05 2018 +0200
Branch	develop
Tag	0.66.3
Author	HappyTobi
Subject	[NEW] Send user status to client (#11303)`

**Comment by bkraul** [comment]
@ggazzo Issue still persists on develop commit hash 7f7690d

**Comment by traxanos** [comment]
same problem here
