### ISSUE TITLE
only usernames not fullnames in message list

### ISSUE THREAD

**Issue by mbu-cx** [RocketChat/Rocket.Chat#11553]
### Description:
since update 0.67.0, the ldap users in the "private message" category on left side only visible with there usernames, not full names

![43086235-2b507b48-8e9d-11e8-92f6-8550016e0b5b](https://user-images.githubusercontent.com/27997168/43133755-0458f346-8f40-11e8-8ae7-8665f6c3c579.png)

i tried to change the settings in the administration tab (ldap and accounts) but nothing did the trick. On previous version (0.66.0) every things works fine.

i did not find another issue since 0.67.0 release about this issue, so i created one ;)

thanks for your help!

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.9.3
- MongoDB Version: 2.6.12

![image](https://user-images.githubusercontent.com/27997168/43086471-ad50e114-8e9d-11e8-9865-c156626b457e.png)

**Comment by bkraul** [comment]
Looks related to #11443 and #11464, neither yet resolved in ```develop```.

**Comment by moonwolf-github** [comment]
After upgrade from 0.66.0 to 0.67.0 everything looks normal in desktop client, but in browser this issue exists.

**Comment by mbu-cx** [comment]
@moonwolf-github 
relogin in client and you have the same issue, i have it in client and browser

**Comment by andypost** [comment]
Without LDAP names also no longer displays

**Comment by antoine-roux** [comment]
FYI, I mitigate this issue with:
```function u(username) { return { username: username, result: db.rocketchat_subscription.updateMany({ $and: [ { 't': 'd' }, { 'name': username } ] }, { $set: { fname: db.users.findOne({ username: username }).name }, $currentDate: { _updatedAt: true } }) }; }
db.rocketchat_subscription.distinct('name', { t: 'd' }).map(function (s) { try { print(s); return u(s); } catch(err) { print('=> Failed') } })```

This is due to the v130 migration https://github.com/RocketChat/Rocket.Chat/blob/master/server/startup/migrations/v130.js

Cheers,
Antoine

**Comment by photoninger** [comment]
I tried to apply this: https://github.com/RocketChat/Rocket.Chat/pull/11544 through editing ```bundle/programs/server/app/app.js``` and ```bundle/programs/server/app/app.js.map``` and now I am on database migration 130 but still I have only usernames instead of full names in my sidebar.

**Comment by adipose** [comment]
@antoine-roux I am still on v129 and RC 0.67.  Yet I still have an issue that it's not showing my real names.  It shows some, but not all.

**Comment by adipose** [comment]
@antoine-roux 
I also updated to v130 successfully.  No real names display.  I tried your script and it simply says "failed" for every user.

**Comment by antoine-roux** [comment]
@adipose 
Do you type `use rocketchat` with you database name instead of `rocketchat` into the mongo cli before executing my snippet?

**Comment by adipose** [comment]
@antoine-roux  oddly, after printing the error I discovered that I had a version of mongo that didn't support updateMany.  Now, it worked.  Although, your code did not enable usernames for me...

**Comment by kaiiiiiiiii** [comment]
Just for reference:

The migration issue should be fixed in PR #11629

**Comment by adipose** [comment]
So, I found out why my mongodb version was out of date.  The instructions for centos suggest using a 2 year old red hat repo for mongodb, which still is pushing MongoDB 2.6.  I updated to a different yum repository and updated to 3.4.

I created a pull request for the changes I had to make.

https://github.com/RocketChat/docs/pull/864

**Comment by antoine-roux** [comment]
Hello,
Please re-open this issue, the PR does NOT fix the problem ... try to create a new direct conversation and look a the beautiful username instead of real name!

The problem does not come only from the v130 typo.

**Comment by antoine-roux** [comment]
@sampaiodiego My fault... sorry. You PR is perfect! I didn't erase my cache.
One more time, sorry.

**Comment by sampaiodiego** [comment]
no worries @antoine-roux 😄  glad to hear it indeed fixed the issue. thx

**Comment by andypost** [comment]
After upgrade to 0.68.2 & clearing cache in "messages" names still not displayed.
Any other cache should be cleared?

**Comment by adipose** [comment]
@andypost 

Did you already update the setting under layout to use full names?

**Comment by sampaiodiego** [comment]
> clearing cache in "messages"

@andypost sry but that is not what you should do.. you'll have to log out and log in back again.. that will clear your browser's cache and fix the issue. if someone else is still seeing usernames, they will have to log out and log back in to see the real names.

**Comment by andypost** [comment]
@sampaiodiego Thanks a lot, after logout/login names started to display again but only when I receive new message from contact!
Btw in android app search by nickname now returns 2 contacts when I do seach by nick

**Comment by sampaiodiego** [comment]
@andypost do you mind opening an issue on https://github.com/RocketChat/Rocket.Chat.Android ? thx

cc @rafaelks
