### ISSUE TITLE
After updating to 0.68.0 Sidebar shows Usernames instead of Real Names

### ISSUE THREAD

**Issue by johnyb0y** [RocketChat/Rocket.Chat#11598]
### Description:

After updating to 0.68.0 the **left sidebar** displays usernames instead of Real names.
I already searched settings (twice) and as far as I can tell every setting is set to Use Real Names.
Have i overlooked something ?

**EDIT:** Just to be clear: Before the update the sidebar showed the Real Names, not the usernames.

### Steps to reproduce:

1. Update to 0.68.0 from 0.65.2

### Expected behavior:

Setting shouldn't change. Also toggling the various "Use Real Names" settings should have an effect and configure the sidebar to use Real Names again.

### Actual behavior:

Username is shown and settings don't seem to change anything regarding the sidebar.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.0
- Operating System: Debian 9.5
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.11.3
- MongoDB Version: Up-to-date Debian Stable Package

Thanks.

**Comment by himpierre** [comment]
Just took a look. I guess it was always like that? The sidbar only shows the username. No? Just checked my 0.66.0 installation.

**Comment by baevga** [comment]
I have the same problem too. i was using 0.65.1 version and can to show realnames in sidebar. After update this option not work and all current chats became a login. We using numeric logins and that so uncomfortable

**Comment by johnyb0y** [comment]
@himpierre Nope, it worked before. We used real names in sidebar since at least 6 months.

**Comment by baevga** [comment]
@johnyb0y 
I'm talking about  that problem https://prnt.sc/kcdist . I deleted one chat  and start new one. After that it has real name in it's title like that http://prntscr.com/kcdjhk

Your issue about another problem?

**Comment by johnyb0y** [comment]
That looks like the same problem I'm experiencing. But for me, deleting a chat and starting a new one doesn't help.

You also said something about your login policy not working anymore. That might be worth a separate issue.

**Comment by gabrielloberg** [comment]
Same problem here.

**Comment by himpierre** [comment]
Which setting enables that feature? I have set "Set a User Name to Alias in Message" to true, but thats it.

**Comment by johnyb0y** [comment]
@himpierre which Setting specifically no idea. There are various „Use real name“ Settings spread across the configuration menu.

**Comment by baevga** [comment]
@himpierre, Option on Administration -> Layout ->User Interface -> Use Real Name

**Comment by himpierre** [comment]
Uah. Thanks. Never saw this page. You learn something new every hour. :-)

**Comment by a1268512** [comment]
i set "Use Real Name" to true but nothing changed. is there another solution for this issue?

**Comment by baevga** [comment]
@a1268512, This is not solution. This is setting that not working correctly and that's why this issue was created

**Comment by mpiotrowski-im** [comment]
It looks like a duplicate of #11553

**Comment by tomcsi** [comment]
The #11553 is ldap authenticated config. The sidebar doesn't work at all.

**Comment by johnyb0y** [comment]
@tomcsi yeah, but I think he might have misinterpreted his issue to be related to LDAP. Looks like the same issue to me.

**Comment by mpiotrowski-im** [comment]
@tomcsi It started as that but if you look closely it was corrected as a bug about sidebar (called message list in the issue). Look at the screenshot and comments. It is not about only ldap authenticated config.

**Comment by johnyb0y** [comment]
@Scream85 I have registration users as well and it's still happening. So LDAP seems to have no effect regarding this issue - at least for me.

**Comment by bkraul** [comment]
I just wonder why this issue is being largely ignored while other minor things are getting worked on, seeing the commits on develop. While this is not functionally breaking, I would consider it high-impact. From what I saw, all efforts were focused on release of 0.68 which was slated for the 27th. Hopefully some attention will be given to this. 😄

**Comment by himpich** [comment]
We are using 0.67.0. My left sidebar is mixed with nice "Name" Versions and not so nice "username" Versions.

Old conversations show up as 'Username', if I send a message to such a contact, the chat gets renamed to the 'Username' variant.

**Comment by danpospisil** [comment]
The same here - we had real names on 0.66.0 and now there is username on 0.68.0 in the left column.

**Comment by ahartlaub** [comment]
Same here.  Reported previously about 2 weeks ago.  We store our users extension numbers in their real name for easy phone tree lookup and this is crippling our use of RC.

**Comment by vesvalo** [comment]
+1, the same problem

**Comment by adipose** [comment]
So I had never heard of this "real names" thing until today, but I turned on the setting, and something very odd happened.  Only about half of the usernames show, and the other half show real names.  It appears to be the original 3-4 users I had on the system, before I imported the rest.  So perhaps if the history was first recorded under the username, the real name can never be displayed?

**Comment by bkraul** [comment]
The ones that still show real names will change to usernames as soon as you type a direct message to them.

**Comment by adipose** [comment]
ah, ok well in spite of myself I updated to .68.1, and now they all show usernames...

**Comment by adipose** [comment]
Problem solved.  First update bundle/programs/server/app/app.js and fix the line that wrongly identifies v130 as db version v129.  Then restart rocketchat and verify in the logs it has updated the db version.

Next, in mongo shell, run command from antoine here:

https://github.com/RocketChat/Rocket.Chat/issues/11553

Pasted for your convenience:
```function u(username) { return { username: username, result: db.rocketchat_subscription.updateMany({ $and: [ { 't': 'd' }, { 'name': username } ] }, { $set: { fname: db.users.findOne({ username: username }).name }, $currentDate: { _updatedAt: true } }) }; }
db.rocketchat_subscription.distinct('name', { t: 'd' }).map(function (s) { try { print(s); return u(s); } catch(err) { print('=> Failed') } })

**Comment by johnyb0y** [comment]
@adipose interesting! Maybe I’m gonnna try that tomorrow (with a vm snapshot as backup). Thanks. How did you find this solution?

**Comment by johnyb0y** [comment]
@adipose nvm saw the other issue thread.

**Comment by sampaiodiego** [comment]
sry guys for the trouble.. as you have already discovered, the issue was due to a wrong migration version. the fix will be https://github.com/RocketChat/Rocket.Chat/pull/11544 and once merged I'll release a hotfix.

**Comment by bkraul** [comment]
Muito obrigado, Diego. You da man. 😄

**Comment by adipose** [comment]
@sampaiodiego Does the upgrade to v130 solve the issue entirely? Maybe I didn't need that db update script, but I think it didn't work until I had done it.

**Comment by bkraul** [comment]
It solved for me, however, I had to Hide all my DM rooms and re-add them to my list, or send a message in order for their names to change back to Real Names. All is good now.

**Comment by sampaiodiego** [comment]
@adipose yes, it solves..

maybe you have to logout and log in back again, in order to clear client cache.

**Comment by sampaiodiego** [comment]
no mongo shell command is needed to get this fixed.. just update to latest version (`0.68.2`) and log out and log in back again.

running commands directly on db are not encouraged unless you know exactly what you're doing.

**Comment by dirknilius** [comment]
In my case this is not fixed at all. I made the update to 0.68.2 and i am now on 0.69. I logged out and in but still the username only entries in the direct message list remain. I also tried to hide and re-add and send new messages. Nothing worked :( Does anyone has an advice?

**Comment by gabrielloberg** [comment]
It is solved for us partially. Users whom I have chatted with before shows correctly, but users I haven't chatted with before still shows username in the sidebar, but shows correct in the chat room.

**Comment by dirknilius** [comment]
@gabrielloberg Right, this is the same I experienced. Maybe it's worth to consider filing another bug. Looks like the devs think they have done this right.

**Comment by Ghoshnik** [comment]
Any Update on this? im on 0.69 and still having this issue.
Seems to be the user that starts a DM will have the Full Name show in sidebar.
but the receiver of the DM will get a username....

**Comment by sampaiodiego** [comment]
@Ghoshnik just trying to isolate the issue: does it get fixed if you reload the page? are you using LDAP? thx

**Comment by dirknilius** [comment]
@sampaiodiego I have the same issue with 0.69.1. I'm using LDAP. Page reload doesn't help. The bug is present in Web / Desktop App and mobile (I'm using the native Android version).

**Comment by Ghoshnik** [comment]
@sampaiodiego 
hi sam. it does not fix if i refresh. we are using LDAP.
if i toggle to  Layout - User interface - Use Real Names to false,  it will make all DMs show as users
when i toggle it back to true it only shows some as Real names and others stay as User names.

**Comment by lehrhardt** [comment]
Hi. Having the same issue, even after updating to 0.69.3 and resetting the data in android and desktop app, some usernames are still shown with uid instead of their realnames.

**Comment by lehrhardt** [comment]
@adipose thanks for pointing this out. We have run this script manually and indeed, this fixed the display issue and all users are now being displayed with their realnames. thx.

**Comment by adipose** [comment]
@lehrhardt Great!
@sampaiodiego Perhaps it is time to reexamine whether the db upgrade is sufficient to fix this issue for LDAP users?  I also use LDAP and felt the mongodb script was required, and now it's seeming that others are finding the same.

**Comment by sampaiodiego** [comment]
I'm afraid it is not fixed for new users. I have to take a new look into this.

**Comment by photoninger** [comment]
Will this issue be fixed in 0.70? 
Or should it's state be changed to open again?

**Comment by sampaiodiego** [comment]
this was proper fixed by https://github.com/RocketChat/Rocket.Chat/pull/12154 and will be released to stable today.

**Comment by RACunha** [comment]
Problem returned in 3.18.0.
It only happens when receiving the first message from someone new. If I search for a contact and send him a message, the problem doesn't occur.
![Captura de tela 2021-09-14 143249](https://user-images.githubusercontent.com/19210519/133306081-7fc2a6de-4081-4f9f-9789-40eece636371.png)

**Comment by AndreySemenov1** [comment]
Confirm this issue

**Comment by RACunha** [comment]
Confirmed at least until 3.18.2

**Comment by KRW85** [comment]
Confirmed at 4.1.0

**Comment by icerootsvw** [comment]
Confirmed for 3.18.3

**Comment by homberger** [comment]
Try this fix in mongo shell:

```
db.rocketchat_subscription.find().forEach(function (subscription) {
	var user = db.users.findOne({username: subscription.name,}, { name: 1 });
	if (!user) {
		return;
	}
	db.rocketchat_subscription.update({_id: subscription._id,}, {$set: {fname: user.name,},});
});
```

**Comment by icerootsvw** [comment]
@homberger any further steps needed? i executed the command but the user is still shown with username instead of real name

`cd /snap/rocketchat-server/current/bin/
root@bl-rocket:/snap/rocketchat-server/current/bin# ./mongo
MongoDB shell version v3.6.14
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("4ba0cd18-8f81-4f35-8ac2-XXXXXXXX") }
MongoDB server version: 3.6.14
Server has startup warnings: 
2021-12-15T17:47:39.029+0100 I STORAGE  [initandlisten] 
2021-12-15T17:47:39.029+0100 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2021-12-15T17:47:39.029+0100 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] 
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] 
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] 
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2021-12-15T17:48:12.297+0100 I CONTROL  [initandlisten] 
rs0:PRIMARY> db.rocketchat_subscription.find().forEach(function (subscription) {
... var user = db.users.findOne({username: subscription.name,}, { name: 1 });
... if (!user) {
... return;
... }
... db.rocketchat_subscription.update({_id: subscription._id,}, {$set: {fname: user.name,},});
... });
`

**Comment by homberger** [comment]
The result of the command you entered is missing in your copied text. 
Did you only paste it into the mongo shell without executing the command, maybe?

If it was executed successfully, you should try to force reload your RC client (CTRL + SHIFT + R).

**Comment by icerootsvw** [comment]
@homberger sorry for the late response. here is what i entered. I did not get any result. Just a new emtpy line and reload the client with ctrl + shift + r did not fix the issue

`root@bl-rocket:~# rocketchat-server.mongo
MongoDB shell version v4.2.17
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("7a8f107b-7d13-449e-848a-c4073033f5ca") }
MongoDB server version: 4.2.17
Server has startup warnings: 
2022-02-22T09:02:09.878+0100 I  STORAGE  [initandlisten] 
2022-02-22T09:02:09.878+0100 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2022-02-22T09:02:09.878+0100 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] 
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] 
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] 
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
2022-02-22T09:02:27.063+0100 I  CONTROL  [initandlisten] 
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

rs0:PRIMARY> db.rocketchat_subscription.find().forEach(function (subscription) {
... var user = db.users.findOne({username: subscription.name,}, { name: 1 });
... if (!user) {
... return;
... }
... db.rocketchat_subscription.update({_id: subscription._id,}, {$set: {fname: user.name,},});
... });
rs0:PRIMARY> 
`

**Comment by icerootsvw** [comment]
my issue was i was not selecting the correct database (thank you to rocket chat support team)

rs0:PRIMARY> show dbs
admin    0.000GB
config   0.000GB
local    2.381GB
parties  1.536GB
rs0:PRIMARY> use parties


After that i executed this and it was fixed directly

`var subscriptions = db.rocketchat_subscription.find({
	t: 'd',
});

subscriptions.forEach(function(subscription) {
	var user = db.users.findOne({
		username: subscription.name,
	}, {
		name: 1
	});
	if (!user) {
		return;
	}
	db.rocketchat_subscription.update({
		_id: subscription._id,
	}, {
		$set: {
			fname: user.name,
		},
	});
})`

**Comment by homberger** [comment]
> @homberger any further steps needed? i executed the command but the user is still shown with username instead of real name

In my comment a line was missing: `use parties`
Sorry!

**Comment by AndreySemenov1** [comment]
> use parties
> db.rocketchat_subscription.find().forEach(function (subscription) {
> 	var user = db.users.findOne({username: subscription.name,}, { name: 1 });
> 	if (!user) {
> 		return;
> 	}
> 	db.rocketchat_subscription.update({_id: subscription._id,}, {$set: {fname: user.name,},});
> });

Hi! Works fine! 

But this is a very long and expensive query:(

However many thanks for temporary solution. :)

**Comment by paulopera** [comment]
I'm facing the same problem where I need to run the mongo query in order to show the full name from the users in the sidebar. 
My server information: 
Deployment Version: 3.18.7
Apps Engine Version: 1.27.1
Node Version: v12.22.1
Database Migration: 232 (3 de Agosto de 2022 06:31)
MongoDB: 4.0.28 / mmapv1 (oplog Enabled)

Right now I'm creating a script to run the query daily in order to fix the display name.
Does somebody found a solution to fix?
Thanks!

**Comment by icerootsvw** [comment]
@paulopera die Script i postet on 17.03.22 fixed the wrong names for me, with the latest rocket chat version i did not notice the issue again, so i just had to fix the usernames onces with the script

**Comment by paulopera** [comment]
The scrip only works for the past conversations, some new conversations are still displaying the username and not the display name.
Can you share the server information you're running right now?
I suspect because I'm running the 3.18.* I'm missing some DB update or something like that.

**Comment by paulopera** [comment]
I'm still running the old version because of the changes in Basic User Data Sync.

**Comment by CeeSharpDev** [comment]
Hello, 

Got same issue, the RC client shows only usernames, even on the 'user info' there is no field that displays user's full name. Admin settings / Client Settings doesn't seem to change the behavior. 

Well running the laltest stable version of RC: 6.11.1 / Mongo: 5.0 

thanks in advance :)

**Comment by paulopera** [comment]
Hello @CeeSharpDev I got it fixed by using the script @icerootsvw posted but now we need to use the mongosh instead of the mongo to run the script.
Here the steps I did as I run RC on docker:

1- At the container folder: docker compose exec mongo bash
2- At the mongo container bash: mongosh
3- Select the mongo RC DB: use rocketchat;
4- Run the script provided above by @icerootsvw [here](https://github.com/RocketChat/Rocket.Chat/issues/11598#issuecomment-1070751000) 

And now all the users got the Display Names instead of the usernames.

**Comment by CeeSharpDev** [comment]
Hello @paulopera thanks a ton for your response. Actually a wrong setting via Admin Settings was toggled earlier, hence no changes were realized, But found the right setting: 'Layout --> Use Real Names', this had fixed the issue.

Thank you again :)

**Comment by paulopera** [comment]
You are welcome @CeeSharpDev ! Indeed there's this setting where you can choose the Real Name.
