### ISSUE TITLE
Message box unaccessible unless Rocket.Chat window is resized to smallest length

### ISSUE THREAD

**Issue by antoinefrancis** [RocketChat/Rocket.Chat#11689]
On Ubuntu 18.04.1 running Rocket.Chat 2.11.0: when the app is full screen, I don't see the message box where I'm supposed to enter my input. I have to resize the Rocket.Chat window to the smallest length, so that the message box is showing up - but not entirely. See screenshots attached:

![full_screen_rocket_chat_screenshot](https://user-images.githubusercontent.com/30053899/43782493-ce9e559a-9a5f-11e8-95d0-cd3881c5b8c9.png)
![small_length_rocket_chat_screenshot](https://user-images.githubusercontent.com/30053899/43782494-cec2da3c-9a5f-11e8-8872-0fb6c1030cec.png)

**Comment by kaiiiiiiiii** [comment]
Wrong repository mate :)

https://github.com/RocketChat/Rocket.Chat.Electron/

// CC: @TwizzyDizzy

**Comment by ggazzo** [comment]
@antoinefrancis with version of rocketchat (server) are you using? because this 'design' is quite old

**Comment by antoinefrancis** [comment]
@ggazzo The server version is 0.48.1

**Comment by kaiiiiiiiii** [comment]
Update to the latest version (0.68.3) and try again please.

Thanks

**Comment by antoinefrancis** [comment]
I just installed the latest version available on snap and I have the exact same behavior. It feels like it's on the client side, not the server side.

**Comment by ggazzo** [comment]
@antoinefrancis the server and client both uses the same version...if you could send me the version you are using on snap...I'm saying that because 0.48.x is too old (more than a year I think), and probably we already fixed

**Comment by antoinefrancis** [comment]
@ggazzo Our administrator just updated the server to version 0.68.4. My client is still 2.11.0. However, I still have the same buggy behavior...

**Comment by ggazzo** [comment]
@tassoevan could you try on some linux version? maybe its a electron issue because I cant reproduce =/

**Comment by Hudell** [comment]
Can you provide screenshots of the bug on the current version? That way we can see how each part of the screen is behaving to try and determine what's causing the composer to disappear.

**Comment by antoinefrancis** [comment]
@Hudell The behavior is the exact same as the one in the previous version. See screenshots of the application window, full screen then resized to see the text box appearing:
![screenshot from 2018-08-22 16-16-58](https://user-images.githubusercontent.com/30053899/44469664-44ebb200-a628-11e8-88d1-023a842c168f.png)
![screenshot from 2018-08-22 16-17-23](https://user-images.githubusercontent.com/30053899/44469670-4917cf80-a628-11e8-8041-9c34a9564322.png)

**Comment by jjryan33** [comment]
I am having the same issue but with Windows 10

**Comment by tassoevan** [comment]
Update: a similar issue was detected by @Hudell today in Firefox browser. After some debugging, I can safely say is related to sidebar's height.

**Comment by tassoevan** [comment]
I can't reproduce this issue anymore, therefore I'm closing this issue. Please re-open if you think there's still more to do.
