### ISSUE TITLE
Use Real Name does not work for some users

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#11950]
### Description:

According to funcitonallity described here: https://github.com/RocketChat/Rocket.Chat/issues/9235

Some of the users are displayed with theirs names and some with usernames.

I and @Nepoxx https://github.com/RocketChat/Rocket.Chat/issues/9235#issuecomment-417764053 see this bug.

### Steps to reproduce:

1. Enable "Use real name"

### Expected behavior:

2. Profit

### Actual behavior:

Nice mix of usernames and names

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: ubuntu 18
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: 8+
- MongoDB Version: 4

**Comment by icerootsvw** [comment]
I have the same issue here. All users are coming from an LDAP backend (if that is important). Some users are shown with username in my list instead of real name

The names inside channels are correct. So when someone is writing it looks like

realname: hello word

 In the left navigation menu, most users are displayed with there real name but some of them are shown with the username instead

![auswahl_712](https://user-images.githubusercontent.com/40857785/45089068-47abd400-b10b-11e8-8632-57bffc23a866.png)

**Comment by cheechmarino** [comment]
Same issue with no LDAP users. Only local users created.
![names_usernames](https://user-images.githubusercontent.com/24827950/45097993-bc433a80-b12c-11e8-82d0-e8cecfc9ff0a.PNG)

**Comment by oinadmin** [comment]
I read that in version 0.70.0 bag fix

**Comment by piotrkochan** [comment]
resolved in https://github.com/RocketChat/Rocket.Chat/releases/tag/0.69.2

**Comment by oryfoxer7410** [comment]
Issue still present in 0.69.2. Can confirm LDAP users will randomly show username over name.

**Comment by localguru** [comment]
I do see this since upgrading from 0.61.0 to 0.69.2 a few days ago. We are using SAML.

![bildschirmfoto_2018-09-20_15-40-54](https://user-images.githubusercontent.com/8544984/45823825-db29fb00-bcee-11e8-834b-dc3c06fb3295.png)

**Comment by localguru** [comment]
@piotrkochan please reopen. problems seems not fully solved. thanks.

**Comment by piotrkochan** [comment]
Not resolved in 0.70.0-rc.0

**Comment by ChibiG** [comment]
installed 0.74.1 and issue still exist

**Comment by tassoevan** [comment]
Is anyone experiencing this **without** LDAP or SAML?

**Comment by cheechmarino** [comment]
> 
> 
> Is anyone experiencing this **without** LDAP or SAML?

Our setup without LDAP or SAML shows FULL (Real) names.

**Comment by bvartik-tachyum** [comment]
Version 3.12.3, issue still exists. LDAP to MS AD.

**Comment by vaDrn** [comment]
fricking 2021 and issue is still present

**Comment by homberger** [comment]
And still present in 2022

**Comment by vaDrn** [comment]
I decided to try out Mattermost and potentially migrate to it. Or just get directly to Slack or Teams.
See no point waiting and hoping that basic function will appear or be fixed in a year or two.

oh wait this stuff isn't working since 2018 they might not fix it in another 4 years or ever

this project is dead.
I rather drop this sinking ship

**Comment by supermuxa** [comment]
It looks like the names are taken from AD for a reason: 
Whoever you wrote to first will be shown by their name in AD. And he will see your login instead name in AD .
