### ISSUE TITLE
migration issue ( 0.59.3 => 0.69.1 )

### ISSUE THREAD

**Issue by tiyooo** [RocketChat/Rocket.Chat#12210]
The current situation is as follows.
- Centos6 + Rocketchat 0.59.3

I recently migrated as below.
- Centos7 + 0.69.1

After the migration,
The name of the person in the chat window looks like English.
Previously, the name was shown in Korean.

How can I fix it?

After Migration
![after migration](https://user-images.githubusercontent.com/43229191/46208702-84639780-c366-11e8-9b78-7e5bc705d784.png)

Before Migration
![before migration](https://user-images.githubusercontent.com/43229191/46208703-84639780-c366-11e8-8445-7cc3e9b436d2.png)

**Comment by piotrkochan** [comment]
Try Layout -> User interface -> Use Real Name

**Comment by tiyooo** [comment]
hi~
It is already a real name.

![a](https://user-images.githubusercontent.com/43229191/46209335-91818600-c368-11e8-8383-d97e59e5379c.png)

**Comment by localguru** [comment]
I think is this problem: https://github.com/RocketChat/Rocket.Chat/issues/11913 and fixed here. So and upgrade might help.

**Comment by tiyooo** [comment]
I upgraded to 0.70.0 
However, the problem still occurs.


![b](https://user-images.githubusercontent.com/43229191/46215188-b5989380-c377-11e8-8a34-4cf47a066538.png)

**Comment by xholicka** [comment]
Still experiencing this issue on 0.74.3 
Real names option is enabled. 
Direct messages is mixture of realnames and usernames.

This should have been solved in another threads, but obviously it wasn't. 
Anyone have a solution?
Thank you.
![realname_option](https://user-images.githubusercontent.com/1271193/72050688-078dd000-32c2-11ea-82f6-d04f36395624.png)
![versions](https://user-images.githubusercontent.com/1271193/72050689-078dd000-32c2-11ea-92e6-592a612c516c.png)
![names](https://user-images.githubusercontent.com/1271193/72050690-078dd000-32c2-11ea-99ad-217ede6f3a10.png)

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
