### ISSUE TITLE
Integration with Jitsi - Creation of Video Conference Link

### ISSUE THREAD

**Issue by rodrigocolli** [RocketChat/Rocket.Chat#12253]
There are situations that we only need to generate a room in the Jitsi for video conferences with non-Rocket Chat external users.

It would be interesting to have an option to create a room in Jitsi without the need to choose a user or group in the rocket chat. One possibility would be to have the option to create a room in the main menu and in it we could select external emails, users and groups of the rocket chat.

**Comment by himpierre** [comment]
You mean somethinke like the jitsi slash command? https://rocket.chat/marketplace

**Comment by reetp** [comment]
Ooops:

Rocket 0.70.0 docker install

2018-10-04T11:14:30.717151992Z      error: 'Failed to load the App "Jitsi Slash Command" (3b387ba9-f57c-44c6-9810-8c0256abd64c) as it requires v1.0.0 of the App API however your server comes with v1.1.1. Please tell the author to update their App as it is out of date.',

:-)

**Comment by reetp** [comment]
This is a bit of a spectacular fail, especially when you are trying to promote a new feature.

Not sure who was responsible for this faux pas, but it really is embarrassing........

**Comment by geekgonecrazy** [comment]
This should be resolved soon.  Basically right now when developers submit apps they can only specify one single app engine version to target.  We are making that adjustment in the marketplace api and will be pushing it out soon.

**Comment by geekgonecrazy** [comment]
in general this issue will be fixed.  @rodrigok does look like this app particularly will need to be updated to target `^1.0.0`

**Comment by graywolf336** [comment]
Closing as this should no longer be an issue. :)

**Comment by himpierre** [comment]
Jitsi app still fails with rocketchat 0.70.3. Same error as comment https://github.com/RocketChat/Rocket.Chat/issues/12253?_pjax=%23js-repo-pjax-container#issuecomment-426980906


![bildschirmfoto 2018-10-08 um 14 54 49](https://user-images.githubusercontent.com/40269193/46610192-4c98e480-cb0a-11e8-88c2-eaea841fd820.png)

**Comment by reetp** [comment]
I can confirm on 0.70.3
@graywolf336 this should be reopened <headbang>

**Comment by reetp** [comment]
@rocket-cat reopen

**Comment by geekgonecrazy** [comment]
Should now be fixed.  Removing the app and re-installing should resolve the issue now

**Comment by himpierre** [comment]
>Should now be fixed. Removing the app and re-installing should resolve the issue now

Confirmed. If only @rodrigok would fix the typo. (jitisi instead of jitsi) :-)

**Comment by reetp** [comment]
@rocket-cat open

(reopening on the basis that this is still the original bug which is not yet fixed)

I can verify that the installer works, but the app is still broken on 0.70.3

First the command is mispelled - it should be 'jitsi' and not 'jitisi' as pointed out above

If we then run the command like this we get the wrong URL:

```/jitisi test```

Join the video call: https://jitsi.mydomain.comtest

That should be https://jitsi.mydomain.com/test

This really needs sorting quickly......

**Comment by himpierre** [comment]
@reetp You have to set the last slash in the settings page. Then it works.

**Comment by geekgonecrazy** [comment]
Going to close as this repo is for rocket.chat related bugs(like apps functionality not working etc) not apps in the marketplace.

Do you have a repo they could report bugs in the Jitsi app @rodrigok ?

**Comment by reetp** [comment]
@geekgonecrazy there are two issues here.

One is the miss spelling of 'jitsi' in the app and yes it isn't a server issue but it does need a separate place to report it as it needs fixing PDQ (or we'll just get more bugs here on the same thing)

Second is the rocketchat interface should have some sort of warning to add a trailing '/' to the URL, either a written warning on the admin page or an error check. I could leave this closed and open a new bug for this particular bug?

**Comment by geekgonecrazy** [comment]
The app should handle the missing trailing / too.

**Comment by graywolf336** [comment]
@rodrigok can you open source the code to this App, that way the community can see it and help fix issues with it?

**Comment by rodrigok** [comment]
@graywolf336 https://github.com/RocketChat/Apps.Jitsi
