### ISSUE TITLE
Mentions are not highlighted anymore

### ISSUE THREAD

**Issue by libussa** [RocketChat/Rocket.Chat#12267]
### Description:

When mentioning someone or the room (@all and @here), the mentions work (notifications, pinging noise). The issue is that there is no syntax highlighting happening, and you can't click on @nick. The color appears for a split second and then disappears.
The colors are present in the android app, but not on web or desktop.

### Steps to reproduce:

1. Mention someone or the room
2. No coloration, no clickable nick

### Expected behavior:

Colored and clickable mentions.

### Actual behavior:

Here is a screen recording of the bug: [mp4 link](https://i.imgur.com/3YPHIlw.mp4)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 3.4.17

### Relevant logs:

`[34mI20181005-10:40:49.299(0) rocketchat_logger rocketchat_logger.js:278 [34mIntegrations ➔ Outgoing WebHook.debug Execute Trigger: sendMessage`

`[34mI20181005-10:40:49.301(0) rocketchat_logger rocketchat_logger.js:278 [34mIntegrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage { event: 'sendMessage',   message:     { _id: '<id>',      rid: '<id>',      msg: 'hello @test.testing ',      ts: 2018-10-05T10:40:49.220Z,      u:        { _id: '<id>',         username: '<me>',         name: '<my name>' },      mentions: [ [Object] ],      channels: [],      _updatedAt: 2018-10-05T10:40:49.238Z,      sandstormSessionId: null },   room:     { _id: '<id>',      name: 'test2',      fname: 'test2',      t: 'p',      msgs: 11,      usersCount: 2,      u: { _id: '<id>', username: 'test.testing' },      customFields: {},      broadcast: false,      encrypted: false,      ts: 2018-10-05T10:14:29.512Z,      ro: false,      sysMes: true,      _updatedAt: 2018-10-05T10:40:44.645Z,      lm: 2018-10-05T10:40:44.599Z,      username: '<me>' } }  `

**Comment by localguru** [comment]
can not confirm on 0.69.2 and on 0.70.1 (open.rocket.chat)

**Comment by libussa** [comment]
Update: the problem doesn't happen when sending a message through a webhook

**Comment by wemu** [comment]
We see the same thing on 0.71.0
Mentions work in multiline messages, but not in single line messages.

**Comment by libussa** [comment]
indeed, multiline works

**Comment by libussa** [comment]
update: mentions work on a single line if you don't include a space after it; type @all, type ESC to escape the completion pop up, and enters, mention works.

This is still happening in 0.72.1

**Comment by engelgabriel** [comment]
I believe this has been fixed, please let me know otherwise.

**Comment by wemu** [comment]
@engelgabriel Running 0.74.3 mentions still don't work. Both original and marked markdown parser behave the same. It sort of seems to shortly works and is then removed. Not sure if there is another setting interfering with this.
