### ISSUE TITLE
Message retention policy is not deleting files, only messages are getting deleted.

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#13249]
### Description:

We have retention policy enabled in our RC instance, with a maximum age of 7 days.  The settings are configured to include private groups, channels, and direct messages.  We don't exclude pinned messages from this policy.  And we have "Only delete files" set to false.  Messages older than 7 days are getting successfully deleted.  However, old files are not getting deleted.  We have some files that still remain from as far back as 2016.  But, to be clear, none of our files are getting removed.

### Steps to reproduce:

1. Enable message retention policy and set a maximum age.  
2. Attach a file to a message.
3. Let message/file get older than maximum age policy.
2. Let policy activate and run
3. Click on files list and see the files still exist.

### Expected behavior:

We expect the files to be removed, along with the messages.

### Actual behavior:

Files do not get removed.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.9.3
- MongoDB Version: 3.2

### Additional context

![image](https://user-images.githubusercontent.com/6833993/51685002-fb2a3d80-1fb2-11e9-8fc6-d0be739cc13a.png)

![image](https://user-images.githubusercontent.com/6833993/51685022-0f6e3a80-1fb3-11e9-8eb7-916a3d954bee.png)

### Relevant logs:

Logs seem to show the policy working for messages:

Jan 24 00:00:00 chat rocketchat2: rocketchat_logger.js:299 #033[34mSyncedCron ➔ info#033[39m Starting "Prune old messages by retention policy".
Jan 24 00:00:52 chat rocketchat2: rocketchat_logger.js:299 #033[34mSyncedCron ➔ info#033[39m Finished "Prune old messages by retention policy".

**Comment by vynmera** [comment]
Can you test a manual prune, and see if files disappear then? (e.g., create a channel, post some files, prune the channel, then see if the files are left). Perhaps someone updated the file storage logic without changing the references in the prune function.

**Comment by mddvul22** [comment]
When I do a manual prune, in a test channel, the files are deleted, also.

**Comment by tars21** [comment]
more or less the same here.

```
Rocket.Chat v1.1.2
```
Retention Policy settings:
```
applies to channels: true
applies to private groups: true
applies to direct messages: true
only delete files: true
```
"File removed by prune" worked on private chats and some Channels, but not all of them. A manual prune works there. Didn't test "Private Groups" so far.

**Comment by ggazzo** [comment]
@mddvul22 and @tars21 I think this pr fixes your problems  https://github.com/RocketChat/Rocket.Chat/pull/15252 could you test please? I will close this issue because I'm very confident we fixed, but any problem open it again..

**Comment by mddvul22** [comment]
We still have this problem.  https://github.com/RocketChat/Rocket.Chat/pull/15252 does not appear to have fixed our problem.  Is there something that we need to do to enable the pruning, by cron, that is mentioned on that page?   As mentioned in this ticket, we have a default retention policy of 7 days for everything.  But we have files in channels, that are still viewable, going back several years.

**Comment by mddvul22** [comment]
Apparently commenting to the issue doesn't automatically reopen it, and I'm not allowed to reopen it explicitly because I didn't close it myself. So, please reopen it :)

**Comment by mddvul22** [comment]
@ggazzo can you please re-open?   Thanks!

**Comment by mddvul22** [comment]
@ggazzo can you please re-open?   Thanks!
