### ISSUE TITLE
Failed to complete OAuth handshake with keycloak

### ISSUE THREAD

**Issue by danielmcc123** [RocketChat/Rocket.Chat#14134]
### Description:

I am trying to authenticate Rocket-Chat with Keycloak using OpenID Connect. I have been through all the related posts but can't work out what is wrong with my setup. I am getting the same issue as #7418 but I have looked at the solution on that post and it matches up to what I have. I am hosting in docker, both Rocket-Chat and Keycloak are on the same `docker-compose.yml` file. 

#### Keycloak Setup:
Client ID: rocket
Enabled: ON
Client Protocol: openid-connect
Access Type: confidential
Standard Flow Enabled: ON
Implicit Flow Enabled: ON
Direct Access Grants Enabled: ON
Valid Redirect URIs: http://localhost:3000/_oauth/keycloak
Web Origins: http://localhost:3000

#### Rocket-Chat Setup
URL: http://localhost:8080/auth 
Token Path: /realms/eshc/protocol/openid-connect/token
Token Sent Via: Header
Identity Token Sent Via: Header
Identity Path: /realms/eshc/protocol/openid-connect/userinfo
Authorize Path: /realms/eshc/protocol/openid-connect/auth
Scope: openid
Id: rocket
Secret: Matches the id given in Keycloak for the client
Login Style: redirect 
Username Field: preferred_username

### Expected behavior:

I can login into Rocket-Chat with my credentials. 

### Actual behavior:

I am able to to go to http://localhost:3000 I am then presented with a login page (see below). I am then redirected to the Keycloak page and I can login but I then get directed right back with the following error in the terminal: 

```
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with keycloak at http://localhost:8080/auth/realms/eshc/protocol/openid-connect/token. connect ECONNREFUSED 127.0.0.1:8080
rocketchat_1          |     at CustomOAuth.getAccessToken (packages/rocketchat:custom-oauth/server/custom_oauth_server.js:118:18)
rocketchat_1          |     at Object.OAuth.registerService.query [as handleOauthRequest] (packages/rocketchat:custom-oauth/server/custom_oauth_server.js:174:29)
rocketchat_1          |     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
rocketchat_1          |     at middleware (packages/oauth/oauth_server.js:161:5)
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_1          |   message: 'Failed to complete OAuth handshake with keycloak at http://localhost:8080/auth/realms/eshc/protocol/openid-connect/token. connect ECONNREFUSED 127.0.0.1:8080' }
```

![image](https://user-images.githubusercontent.com/35777751/56084837-437a2e80-5e31-11e9-8d44-bce753bac2b3.png)
****

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: MacOS 10.14.2
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 4.0
- Keycloak Version: 5.0.0

**Comment by danielmcc** [comment]
I found the problem, docker networking issues on MacOS.
This issue was solved by replacing `http://localhost:8080/auth` with `http://docker.for.mac.localhost:8080/auth` in Rocket-Chat.

**Comment by geekgonecrazy** [comment]
Yes localhost is pointing to the container it’s self.  

Closing since solved

**Comment by aminr99** [comment]
> Yes localhost is pointing to the container it’s self.
> 
> Closing since solved

I changed the site-url(in general)=http://<ip-server:port>
and url= http://<ip-server:port>/auth
but I am still not redirected to Rocket i truly appreciate the help.

### Keycloak Setup:

![Screenshot 2023-08-10 150023](https://github.com/RocketChat/Rocket.Chat/assets/52712713/497b69d5-8102-4b3d-80ab-296eb0413460)

![Screenshot 2023-08-10 150113](https://github.com/RocketChat/Rocket.Chat/assets/52712713/08736977-3ecb-4bc2-a9fc-d3caa7683f81)

### Rocket Setup:

![Screenshot 2023-08-10 145711](https://github.com/RocketChat/Rocket.Chat/assets/52712713/50942b51-4398-4341-8035-7afa8ce7bb12)
![Screenshot 2023-08-10 145813](https://github.com/RocketChat/Rocket.Chat/assets/52712713/4bd82158-a0ec-431f-8661-c6d882658b26)
