### ISSUE TITLE
Livechat feature deletes all conversations/rooms for all users

### ISSUE THREAD

**Issue by pharmacare** [RocketChat/Rocket.Chat#14506]
### Description:

After testing the "Forget/Remove my data" feature in the _new_ livechat widget options the following happened:

- all conversations were gone
- all rooms were gone
- all private rooms were gone
- **for all users of the server**

All clients showed a clean server with no data anymore.

Additional Info:

The agent the livechat user was connected to has full admin rights on the server.

The livechat widget was tested in an MS Edge windows.

Logs are not accessible anymore, because we had to immediately recover from backup (people freaking out)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 18.04.2 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.20

<img width="176" alt="ApplicationFrameHost_2019-05-15_15-00-13" src="https://user-images.githubusercontent.com/46776660/57778456-65165080-7724-11e9-842b-2b2f2025a749.png">

**Comment by renatobecker** [comment]
Hi @pharmacare.
Yes, we've found an important security issue when removing the Livechat guest data.
I want to say that we've already fixed it, so I want to thank you for reporting this issue.

Thanks.

**Comment by vocalviews** [comment]
Hi, I had the same issue today which means it is definitely not fixed :(

**Comment by renatobecker** [comment]
> Hi, I had the same issue today which means it is definitely not fixed :(

Share your server info here and describe your case, then we'll be able to help you investigate your issue.
Thanks.

**Comment by vocalviews** [comment]
Thank you 


Version | 1.0.3
Apps Engine Version | 1.4.2
OS Platform linux 
OS Arch | x64
OS Release 4.15.0-1035-aws
Node Version v8.11.3
Mongo Version 3.4.20
Mongo StORAGE engine wiredTiger

same case as above, 

all conversations were gone
all rooms were gone
all private rooms were gone
for all users of the server
All clients showed a clean server with no data anymore.

**Comment by renatobecker** [comment]
> Thank you
> 
> Version | 1.0.3
> Apps Engine Version | 1.4.2
> OS Platform linux
> OS Arch | x64
> OS Release 4.15.0-1035-aws
> Node Version v8.11.3
> Mongo Version 3.4.20
> Mongo StORAGE engine wiredTiger
> 
> same case as above,
> 
> all conversations were gone
> all rooms were gone
> all private rooms were gone
> for all users of the server
> All clients showed a clean server with no data anymore.

As you can see above, we delivered the fix for this issue on the `1.1.0` version and you're running the `1.0.3` version.

Thanks.

**Comment by vocalviews** [comment]
oh apologies, I didn't know it was a server side issue, if I update rocket chat as per the instructions provided by Rocket Chat, will this install a completely fresh version of Rocket Chat, thus loosing all saved settings and chat history?
