### ISSUE TITLE
AppArmor errors after Snap Update

### ISSUE THREAD

**Issue by otw-sem** [RocketChat/Rocket.Chat#14562]
Since last weeks automatic Snap Update to Rocket.Chat 1.0.3 my log is flooded with AppArmor MongoDB errors:

> May 20 18:07:55 xxx kernel: [259218.926984] audit: type=1400 audit(1558368474.997:518703): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1458/net/netstat" pid=1738 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> May 20 18:07:55 xxx kernel: [259218.927019] audit: type=1400 audit(1558368474.997:518704): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1458/net/snmp" pid=1738 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

PID 1458 is the mongod process.

Base System: Ubuntu 16.04.6 LTS

```
core               16-2.38.1  6818
rocketchat-server  1.0.3      1377

snap    2.38.1
snapd   2.38.1
series  16
ubuntu  16.04
kernel  4.4.0-131-generic
```

All system packages are updated.

**Comment by reinfire** [comment]
Same here, RocketChat is running in LXC Container, Log from Host:

`May 25 20:40:02 srv01 kernel: [22885.276932] audit: type=1400 audit(1558809601.997:45728): apparmor="DENIED" operation="open" namespace="root//lxd-sh-rocketchat_<var-lib-lxd>" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc`

**Comment by 88fingerslukee** [comment]
I also have this issue. Same two program names (snmp and netstat). Anybody know how to fix this?

**Comment by reinfire** [comment]
Found a similar problem on CentOS with the mogodb:
https://bugs.centos.org/view.php?id=15137

**Comment by 88fingerslukee** [comment]
So I have a workaround for this:

`nano /var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-mongo
`
go to the "Miscellaneous accesses" line

Add in the following two lines:

```
 @{PROC}/@{pid}/net/snmp r,
 @{PROC}/@{pid}/net/netstat r,
```

Then reload the profile

`apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-mongo`

**Comment by scoopex** [comment]
Same here with rocketchat 1.1.3.
Thanks for posting the rules. Are there reasons why the rules should not be part of the snap package?

**Comment by Wirone** [comment]
Same here after upgrading Ubuntu 18.04 to 19.04. Thank you very much @88fingerslukee :beers:

**Comment by 88fingerslukee** [comment]
It still needs to be fixed though. The errors return after every snap update.

**Comment by suharevA** [comment]
88fingerslukee 

thank you very much. Works

**Comment by repentles** [comment]
- @otw-sem

**Comment by repentles** [comment]
https://github.com/otw-sem

**Comment by neilkane** [comment]
Is this resolved now? My snap updated 3 days ago and I don't see the kern.log errors.

**Comment by scoopex** [comment]
Same with 1.3.2.

Further issues with the last releases:

- Automatic snap update leads to a unreachable rocketchat instance.
  The node rocketchat sever starts to fast after upgrading the snap package.
  Mongodb not seems to be ready fast enough and the rocketchat server does not wait long enough  to be connected to mongodb. Probably there is a trivial fix in just increasing connection pool timout values.
- Caddy complains, trivial to fix
  ```
Oct 15 06:33:33 rocketchat-c1-001 rocketchat-server.rocketchat-caddy[1851933]: WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192"."
  ```

**Comment by reetp** [comment]
> Same with 1.3.2.
 
You have showed no evidence of an apparmor issue which is what this one is about.

Unless your issues are DIRECTLY related to this Issue please open a new one after carefully searching to see if has already been opened.

Thanks.

**Comment by 88fingerslukee** [comment]
updated to 2.1.1 and this still persists. Does anybody read this?

**Comment by geekgonecrazy** [comment]
@LuluGO any ideas on this?  Do we need to add a plug or something ?  I think these are non critical errors.  But they are noisy

**Comment by scoopex** [comment]
>     * Automatic snap update leads to a unreachable rocketchat instance.
>       The node rocketchat sever starts to fast after upgrading the snap package.
>       Mongodb not seems to be ready fast enough and the rocketchat server does not wait long enough  to be connected to mongodb. Probably there is a trivial fix in just increasing connection pool timout values.

i created a report for this: https://github.com/RocketChat/Rocket.Chat/issues/15806

> 
>     * Caddy complains, trivial to fix
> 
> 
> Oct 15 06:33:33 rocketchat-c1-001 rocketchat-server.rocketchat-caddy[1851933]: WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192"."

already reported, see https://github.com/RocketChat/Rocket.Chat/issues/6979

**Comment by 88fingerslukee** [comment]
> > ```
> > * Automatic snap update leads to a unreachable rocketchat instance.
> >   The node rocketchat sever starts to fast after upgrading the snap package.
> >   Mongodb not seems to be ready fast enough and the rocketchat server does not wait long enough  to be connected to mongodb. Probably there is a trivial fix in just increasing connection pool timout values.
> > ```
> 
> i created a report for this: #15806
> 
> > ```
> > * Caddy complains, trivial to fix
> > ```
> > 
> > 
> > Oct 15 06:33:33 rocketchat-c1-001 rocketchat-server.rocketchat-caddy[1851933]: WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192"."
> 
> already reported, see #6979

@scoopex This is NOT what this thread is about, please stop commenting on these issues in this thread.

**Comment by nodje** [comment]
I'm having the same symptoms with Ubuntu Snap.
Eager to see my logs clean again, right now get this type of logs 2-3 times per second:
```
Dec 13 06:33:17 rocket kernel: [747494.022369] audit: type=1400 audit(1576218796.998:1462109): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/30208/net/netstat" pid=30208 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by zzeesstt** [comment]
ubuntu snap install v2.3.1 up!

**Comment by mvvvmd** [comment]
Same issue with v2.3.1 on Ubuntu 18.04 here.

**Comment by buckyball** [comment]
The issue is still there on Snap:
`rocketchat-server     2.4.2                       1420   stable        rocketchat✓ `
The apparmor fix from @88fingerslukee is also still working though.

**Comment by ajcollett** [comment]
Hello, this is quite the annoying issue. Currently when the snap updates, this fix no longer works, which by default, happens often. Can someone please have a look? Is this not an easy fix?

**Comment by vanmachin** [comment]
To get rid of theses messages, I've disabled mangodb diagnostics :
`snap run --shell rocketchat-server` to enter into a shell in snap environment
`$SNAP/bin/mongo` to launch the mongodb client
`db.adminCommand( { setParameter: 1, diagnosticDataCollectionEnabled: false } )`
`exit` to exit mongodb client
`exit` to exit snap shell
The change is immediate and should be permanent as the mongo admin db is persistent

**Comment by Marx1st** [comment]
How is this still not fixed when @88fingerslukee has posted an easy 2 line fix MONTH ago?

**Comment by scoopex** [comment]
> How is this still not fixed when @88fingerslukee has posted an easy 2 line fix MONTH ago?

Depressing. It seems that nodejs hackers do not have very much affinity to system-engineering  problems ;-)

**Comment by paulkernstock** [comment]
I'm seeing the same issue (Rocket.Chat snap 2.4.11 on Ubuntu 18.04).

**Comment by stevensedory** [comment]
Our rocketchat just went down because of this a few hours ago out of nowhere :/ We're out cold. Going to try some of these work arounds

**Comment by scornet256** [comment]
> Our rocketchat just went down because of this a few hours ago out of nowhere :/ We're out cold. Going to try some of these work arounds

Same here, but in our case its not related to this Github issue... Snap version 2.4.12 got (accidentally) released on the latest/stable channel (but is retracted already). "Refreshing" back to version 2.4.11 worked for me.

**Comment by captainwasabi** [comment]
I just got this issue on Ubuntu 18.04.04 after this morning's apt update.  The workaround doesn't seem to work for me.  I'm still down

**Comment by stevensedory** [comment]
> 
> 
> I just got this issue on Ubuntu 18.04.04 after this morning's apt update. The workaround doesn't seem to work for me. I'm still down

Try disabling apparmor. That did it for us. OR, when you "refresh", give it like five minutes afterwards, and try in a new browser or private tab, to eliminate cache issues. It will still have the gateway error on the webservice for a few minutes while it starts up (ours was about a minute I think).

**Comment by captainwasabi** [comment]
Did that and nothing would start. 

I think it stalls because:

After=snap-rocketchat\x2dserver-1433.mount network.target snapd.apparmor.service

moving to the 3.x/stable track fixed me.  I had been considering moving anyway.

**Comment by stevensedory** [comment]
> 
> 
> Did that and nothing would start.
> 
> I think it stalls because:
> 
> After=snap-rocketchat\x2dserver-1433.mount network.target snapd.apparmor.service
> 
> moving to the 3.x/stable track fixed me. I had been considering moving anyway.

Oh? Are we on a dev track or something? Is there any easy way to move and preserve our current setup?

**Comment by captainwasabi** [comment]
new installs are defaulting to 3.x/stable already.

snap run rocketchat-server.backupdb

Then move that file somewhere safe, then

snap switch rocketchat-server --channel=3.x/stable
snap refresh

Worked perfect for me, as far as I can tell.  YMMV

**Comment by stevensedory** [comment]
Awesome thanks!

**Comment by math-uzh** [comment]
Ubuntu 18.04, RC as snap package:

After snap update this night, RC (3.5.2) is down again - fix from https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-498321790 solved the problem (as it did in the past)  for us. 

Are there any concerns that the fix is not applied already to RC?

**Comment by ajcollett** [comment]
I have just lost Logs because of this. I seem to only have the last days logs, and I suspect it's because of the log getting so full with these messages. Nothing lasts, none of the fixes here last after an update:

```
rocketchat-server  3.6.2      1442  3.x/stable     rocketchat✓  -
```

```
Sep 28 09:53:41 <snip> kernel: audit: type=1400 audit(1601279620.997:3610932): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:41 <snip> kernel: audit: type=1400 audit(1601279620.997:3610931): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:40 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:40 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:39 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:40 <snip> kernel: audit: type=1400 audit(1601279619.997:3610930): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:40 <snip> kernel: audit: type=1400 audit(1601279619.997:3610929): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:39 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:38 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:39 <snip> kernel: audit: type=1400 audit(1601279618.997:3610928): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:39 <snip> kernel: audit: type=1400 audit(1601279618.997:3610927): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:39 <snip> kernel: kauditd_printk_skb: 2 callbacks suppressed
Sep 28 09:53:38 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:37 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:37 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:37 <snip> kernel: audit: type=1400 audit(1601279616.997:3610924): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:37 <snip> kernel: audit: type=1400 audit(1601279616.997:3610923): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:36 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:36 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:35 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:36 <snip> kernel: audit: type=1400 audit(1601279615.997:3610922): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:36 <snip> kernel: audit: type=1400 audit(1601279615.997:3610921): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:35 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:34 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:35 <snip> kernel: audit: type=1400 audit(1601279614.997:3610920): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:35 <snip> kernel: audit: type=1400 audit(1601279614.997:3610919): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:34 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:34 <snip> kernel: audit: type=1400 audit(1601279613.997:3610918): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:34 <snip> kernel: audit: type=1400 audit(1601279613.997:3610917): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> kernel: audit: type=1400 audit(1601279613.001:3610916): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> kernel: audit: type=1400 audit(1601279613.001:3610915): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:33 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:31 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:32 <snip> kernel: audit: type=1400 audit(1601279611.997:3610914): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:32 <snip> kernel: audit: type=1400 audit(1601279611.997:3610913): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:31 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:30 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:31 <snip> kernel: audit: type=1400 audit(1601279610.997:3610912): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:31 <snip> kernel: audit: type=1400 audit(1601279610.997:3610911): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:30 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:29 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:30 <snip> kernel: audit: type=1400 audit(1601279609.997:3610910): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:30 <snip> kernel: audit: type=1400 audit(1601279609.997:3610909): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:29 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:29 <snip> kernel: audit: type=1400 audit(1601279609.001:3610908): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:29 <snip> kernel: audit: type=1400 audit(1601279608.997:3610907): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:29 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:28 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:27 <snip> audit[31946]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:28 <snip> kernel: audit: type=1400 audit(1601279607.997:3610906): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/snmp" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:28 <snip> kernel: audit: type=1400 audit(1601279607.997:3610905): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/31946/net/netstat" pid=31946 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 28 09:53:28 <snip> kernel: kauditd_printk_skb: 2 callbacks suppressed
```

**Comment by ajcollett** [comment]
@rodrigok I don't know whats going on here, but can someone please be directed to this issue?

**Comment by 88fingerslukee** [comment]
How epically terrible must a response to an issue be when a guy has to write a script to do this? I mean, this script took longer to write than the pull request to fix the error FFS.

**Comment by PH-Bluechain** [comment]
How is this still happening, especially with such a simple workaround existing?

**Comment by iammattmartin** [comment]
I reported this a long time ago and really didn't get much of a look in from RC.

Today just got a disk usage alert as those logs have taken up huge amounts of space and have now just found this. Glad I'm not alone.

**Comment by nanocat-net** [comment]
I also have this problem.

```
root@koala:/var/log# grep apparmor syslog | grep rocketchat | tail
Jan  9 21:33:29 koala kernel: [53237.488832] audit: type=1400 audit(1610224408.999:106795): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/netstat" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:29 koala kernel: [53237.488896] audit: type=1400 audit(1610224408.999:106796): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/snmp" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:30 koala kernel: [53238.489818] audit: type=1400 audit(1610224409.999:106797): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/netstat" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:30 koala kernel: [53238.489883] audit: type=1400 audit(1610224409.999:106798): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/snmp" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:31 koala kernel: [53239.489013] audit: type=1400 audit(1610224410.999:106799): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/netstat" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:31 koala kernel: [53239.489091] audit: type=1400 audit(1610224410.999:106800): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/snmp" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:32 koala kernel: [53240.488827] audit: type=1400 audit(1610224411.999:106801): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/netstat" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:32 koala kernel: [53240.488891] audit: type=1400 audit(1610224411.999:106802): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/snmp" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:33 koala kernel: [53241.488581] audit: type=1400 audit(1610224412.999:106803): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/netstat" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan  9 21:33:33 koala kernel: [53241.488657] audit: type=1400 audit(1610224412.999:106804): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1386/net/snmp" pid=1386 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
root@koala:/var/log# snap list rocketchat-server
Name               Version  Rev   Tracking       Publisher    Notes
rocketchat-server  2.4.14   1453  latest/stable  rocketchat✓  -
root@koala:/var/log#
```

**Comment by scoopex** [comment]
Unsubscribe, it's frustrating :-)

**Comment by geekgonecrazy** [comment]
Guys the work around here are great.  But unfortunately we can't just add this to snap.  Snapd manages the creation of the systemd files and app armour. 

We actually cannot automatically even adjust any of the files mentioned from inside of the snap due to the restrictions that make snap an appealing technology.

This will have to be solved by giving which ever arbitrary plug is associated with this app armour permission in the snap.  If anyone is able to track that down and open PR I'd be happy to test and merge

**Comment by 88fingerslukee** [comment]
W00T!!!

**Comment by gusarg81** [comment]
Still this exist on v3.15.0, Ubuntu 20.04...

**Comment by cadirol** [comment]
Still exists with v3.16.3, Ubuntu 16.04

**Comment by therealZottel** [comment]
Still exists with v3.17.1, Ubuntu 20.04

**Comment by cadirol** [comment]
"fixed" it with https://gist.github.com/Majunko/81e8b45f2a7588975d48be156fd38173#file-rocket-chat-denied-mask-sh

**Comment by CvH** [comment]
@geekgonecrazy I still have the same problem with the current version and the desired fix is not working

```
root@chat:~# snap connect rocketchat-server:network-observe
error: snap "rocketchat-server" has no plug named "network-observe"
```

```
root@chat:~# snap info rocketchat-server
name:      rocketchat-server
summary:   Rocket.Chat server
publisher: Rocket.Chat (rocketchat*)
store-url: https://snapcraft.io/rocketchat-server
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Have your own Slack like online chat, built with Meteor. https://rocket.chat/
commands:
  - rocketchat-server.backupdb
  - rocketchat-server.mongo
  - rocketchat-server.restoredb
services:
  rocketchat-server.rocketchat-caddy: simple, enabled, inactive
  rocketchat-server.rocketchat-mongo: forking, enabled, active
  rocketchat-server:                  simple, enabled, active
snap-id:      wdBUbiEuMNHmAHLBCXQXOcXaOCvbWS1e
tracking:     4.x/stable
refresh-date: 21 days ago, at 06:59 CET
channels:
  3.x/stable:       3.18.3 2021-11-28 (1491) 289MB -
  3.x/candidate:    3.18.3 2021-11-28 (1491) 289MB -
  3.x/beta:         3.18.3 2021-11-28 (1491) 289MB -
  3.x/edge:         3.18.3 2021-11-28 (1491) 289MB -
  latest/stable:    3.18.3 2021-12-06 (1491) 289MB -
  latest/candidate: 3.18.3 2021-12-06 (1491) 289MB -
  latest/beta:      3.18.3 2021-12-06 (1491) 289MB -
  latest/edge:      4.1.2  2021-12-06 (1497) 285MB -
  4.x/stable:       4.2.2  2021-12-15 (1502) 255MB -
  4.x/candidate:    4.2.2  2021-12-15 (1502) 255MB -
  4.x/beta:         4.2.2  2021-12-15 (1502) 255MB -
  4.x/edge:         4.2.2  2021-12-15 (1502) 255MB -
  2.x/stable:       2.4.14 2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14 2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14 2020-12-23 (1453) 267MB -
  2.x/edge:         ^
installed:          4.2.2             (1502) 255MB -

```

**Comment by geekgonecrazy** [comment]
@debdutdeb what do you think on this one?

**Comment by CvH** [comment]
still the same problem at latest

```
root@chat:~# snap connect rocketchat-server:network-observe
error: snap "rocketchat-server" has no plug named "network-observe"
```

```
root@chat:~# snap info rocketchat-server
name:      rocketchat-server
summary:   Rocket.Chat server
publisher: Rocket.Chat (rocketchat*)
store-url: https://snapcraft.io/rocketchat-server
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Have your own Slack like online chat, built with Meteor. https://rocket.chat/
commands:
  - rocketchat-server.backupdb
  - rocketchat-server.mongo
  - rocketchat-server.restoredb
services:
  rocketchat-server.rocketchat-caddy: simple, enabled, inactive
  rocketchat-server.rocketchat-mongo: forking, enabled, active
  rocketchat-server:                  simple, enabled, active
snap-id:      wdBUbiEuMNHmAHLBCXQXOcXaOCvbWS1e
tracking:     4.x/stable
refresh-date: 7 days ago, at 08:17 CET
channels:
  4.x/stable:       4.3.1  2022-01-09 (1505) 238MB -
  4.x/candidate:    4.3.1  2022-01-09 (1505) 238MB -
  4.x/beta:         4.3.1  2022-01-09 (1505) 238MB -
  4.x/edge:         4.3.1  2022-01-09 (1505) 238MB -
  latest/stable:    3.18.3 2021-12-06 (1491) 289MB -
  latest/candidate: 3.18.3 2021-12-06 (1491) 289MB -
  latest/beta:      3.18.3 2021-12-06 (1491) 289MB -
  latest/edge:      4.1.2  2021-12-06 (1497) 285MB -
  3.x/stable:       3.18.3 2021-11-28 (1491) 289MB -
  3.x/candidate:    3.18.3 2021-11-28 (1491) 289MB -
  3.x/beta:         3.18.3 2021-11-28 (1491) 289MB -
  3.x/edge:         3.18.3 2021-11-28 (1491) 289MB -
  2.x/stable:       2.4.14 2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14 2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14 2020-12-23 (1453) 267MB -
  2.x/edge:         ^
installed:          4.3.1             (1505) 238MB -
```

**Comment by Majunko** [comment]
@therealZottel that line it's already added to the script, did you tried to download the latest gist and execute it ?

**Comment by therealZottel** [comment]
@Majunko Thanks for the tip. I had not seen that.

**Comment by gusarg81** [comment]
Hi, same problem here... Ubuntu server 20.04. Rocketchat-server snap keeps filing syslog with these:

> ...
> Mar 29 09:36:06 server kernel: [607569.873864] audit: type=1400 audit(1648557366.000:1215430): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/3161/net/netstat" pid=3161 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Mar 29 09:36:06 server kernel: [607569.873887] audit: type=1400 audit(1648557366.000:1215431): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/3161/net/snmp" pid=3161 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> ...

rocketchat-server  3.18.3         1491   3.x/stable     rocketchat✓  -

**Comment by Majunko** [comment]
@gusarg81 Did you tried to use my script ?
https://gist.github.com/Majunko/81e8b45f2a7588975d48be156fd38173

**Comment by gusarg81** [comment]
@Majunko I will try, thanks!

Also upgraded to 4.x stable branch and the same thing does happens.

**Comment by genebean** [comment]
Glad @Majunko has a solution because this was an unexpected error directly after setup.

**Comment by J0kerFace** [comment]
`Feb 14 13:56:21 server kernel: audit: type=1400 audit(1676379381.001:379): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/2350/mountinfo" pid=2350 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

Still persist after Using @Majunko ´s Script. Any Idea?

**Comment by mmerickel** [comment]
Similarly, logs are being spammed with `Mar 02 06:31:34 redacted kernel: audit: type=1400 audit(1677738693.997:662): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1235/mountinfo" pid=1235 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`.

Adding the apparmor configs suggested above haven't helped. Tested on 4.x/stable and 5.x/stable channel (5.4.3 right now).

**Comment by gusarg81** [comment]
Will this ever be fixed some day?

**Comment by mmerickel** [comment]
@gusarg81 FWIW I was able to suppress this final apparmor warning via my comment last night at https://gist.github.com/Majunko/81e8b45f2a7588975d48be156fd38173?permalink_comment_id=4488954#gistcomment-4488954.

However, obviously putting this script into a cronjob is quite bad and undocumented. I was experiencing this on a very barebones ubuntu 20.04 LTS instance. This issue should really be reopened until at least something is added to the documentation or someone tells me what all of these folks in the issue tracker are doing wrong when installing the snap to trigger apparmor violations.

**Comment by gusarg81** [comment]
Thats why I said that... this "bug" is Eternal.

**Comment by captainwasabi** [comment]
Perhaps Infernal is a better term ;)  The fact that this has been closed is crazy, but probably means that if you are a commercial customer you don't have this problem.

**Comment by geekgonecrazy** [comment]
I've reopened this so we can investigate.

Does the snap actually fail or just spam with warnings in the logs?

Unfortunately while fixing externally the apparmor policy does workaround.  Those things are generated automatically with snaps.  So we can't simply add something inside the snap to modify it.  Since due to the isolation it couldn't update apparmour.

So we have to find the appropriate "plug" or flag to generate the snap so that snapd will properly set those app armor policy.

With it appearing to not actually break but just spam the logs and with it being a bit of a complex problem to dig into it hasn't been a priority to look at it.

That being said I've reopened and have it on our radar to try and dig.  If someone happens to find the appropriate plug we can add to the snap to make this happy please let us know and we can quickly and easily make that sort of change.

**Comment by geekgonecrazy** [comment]
https://snapcraft.io/docs/debug-snaps This might be useful if someone wants to dig.  There does seem to be a file you can create with the apparmour profile to make it more permanent that might be worth looking into

**Comment by captainwasabi** [comment]
Mongo fails to start, then you look in the logs to see why and it's full of those messages.

**Comment by mmerickel** [comment]
Yeah I couldn't upgrade the snap from 3.x to 4.x without changing the apparmor config. Mongo didn't start.

The final issue around https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-1451368226 was just spamming the logs at least once per second but didn't appear to be breaking anything.

**Comment by Peppershade** [comment]
Fix doesn't seem to work any more, can't update to RocketChat 6

**Comment by debdutdeb** [comment]
can anybody give access to their server (new user with separate install) so that we can test this? I have tried multiple times but failed to repro this.

**Comment by Peppershade** [comment]
> can anybody give access to their server (new user with separate install) so that we can test this? I have tried multiple times but failed to repro this.

I'm not sure if I can reproduce the server errors, as this Rocket Chat server is already ~5-7 years old. When I'm able to, I'll share all technical information about the server, and I'll give it a try to reproduce the error. If I can, it's no problem to share a VPS with you to find the exact issue.

**Comment by Fiodin** [comment]
I had the same problem with my installation by switching from 4.x/stable to 5.x/stable.

After a few tries and trying the solutions from
vanmachin:https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-607301974
88fingerslukee:https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-498321790
therealZottel:https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-1061699865
I was frustrated.

Then I upgraded my Debian 10 to 11 and everything went fine. So probably the problems with apparmor are within the OS....

**Comment by sporqist** [comment]
@geekgonecrazy The snap doesn't fail. It spams the logs. Using this [snappy-observe guide](https://snapcraft.io/docs/debugging-building-snaps#heading--identifying-missing-interfaces), I figured out the snap is missing the plugs `mount-observe` and `system-observe`:

```
= AppArmor =
Time: 2023-10-06T11:3
Log: apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/48530/mountinfo" pid=48530 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /proc/48530/mountinfo (read)
Suggestions:
* adjust program to not access '@{PROC}/@{pid}/mountinfo'
* add one of 'mount-control, mount-observe, steam-support' to 'plugs'

= AppArmor =
Time: 2023-10-06T11:3
Log: apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=48530 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /proc/vmstat (read)
Suggestions:
* adjust program to not access '@{PROC}/vmstat'
* add one of 'browser-support, system-observe' to 'plugs
```

Until now, I "fixed" this by adding permissions to rocketchat-mongo.

```apparmor
# /var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-mongo
profile "snap.rocketchat-server.rocketchat-mongo" (attach_disconnected,mediate_deleted) {
  ...
  @{PROC}/@{pid}/mountinfo r,
  @{PROC}/vmstat r,
  ...
}
```

I can give (supervised) access to my test server if you want to have a look at this. Feel free to contact me.

**Comment by captainwasabi** [comment]
Can't believe ya'll have not fixed this yet.

**Comment by slyk** [comment]
> @geekgonecrazy The snap doesn't fail. It spams the logs. Using this [snappy-debug guide](https://snapcraft.io/docs/debugging-building-snaps#heading--identifying-missing-interfaces), I figured out the snap is missing the plugs `mount-observe` and `system-observe`:
> 
> ```
> = AppArmor =
> Time: 2023-10-06T11:3
> Log: apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/48530/mountinfo" pid=48530 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> File: /proc/48530/mountinfo (read)
> Suggestions:
> * adjust program to not access '@{PROC}/@{pid}/mountinfo'
> * add one of 'mount-control, mount-observe, steam-support' to 'plugs'
> 
> = AppArmor =
> Time: 2023-10-06T11:3
> Log: apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=48530 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> File: /proc/vmstat (read)
> Suggestions:
> * adjust program to not access '@{PROC}/vmstat'
> * add one of 'browser-support, system-observe' to 'plugs
> ```
> 
> Until now, I "fixed" this by adding permissions to rocketchat-mongo but the file gets overwritten every now and then, turning this into a real headache.
> 
> ```
> # /var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-mongo
> profile "snap.rocketchat-server.rocketchat-mongo" (attach_disconnected,mediate_deleted) {
>   ...
>   @{PROC}/@{pid}/mountinfo r,
>   @{PROC}/vmstat r,
>   ...
> }
> ```
> 
> I can give access to my test server if you want to have a look at this. Feel free to contact me.

worked for me, got flood in logs because of that messages.
thank you

**Comment by geekgonecrazy** [comment]
https://github.com/RocketChat/server-snap/blob/develop/snap/snapcraft.yaml#L36 if anyone wants to contribute and test this fix.  Can find the source for the snap here

**Comment by slyk** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/10034821/6431ee7a-137a-4bc6-bed4-56f762ffb2cf)
got journal full of app armor errors and that is filing up logs.
every update had to fix apparmor files. Are you sure the issue is closed?

**Comment by reetp** [comment]
> every update had to fix apparmor files. Are you sure the issue is closed?

What version are you on?

Have you checked the settings as per the PR above?

**Comment by slyk** [comment]
> > every update had to fix apparmor files. Are you sure the issue is closed?
> 
> What version are you on?
> 

v 6.9.3 updated couple day ago and again got logs full of that app armor flood.
![image](https://github.com/user-attachments/assets/a16ddf49-b869-4880-b17e-ea111c4a4a23)

![image](https://github.com/user-attachments/assets/c9abc8ea-0ad7-46bc-a714-3de5ff2d097a)

> Have you checked the settings as per the PR above?
Don't see a PR that is proposing to edit some settings. Settings in admin of the rocketchat?

seems like 4 days agot the patch is merged, so hope for next version it will work %)

**Comment by reetp** [comment]
I'll ask the team.

**Comment by sporqist** [comment]
The fix was merged into 6.10.0 which is available on the 6.x/edge snap channel:
```console
$ snap info rocketchat-server
...
channels:
  6.x/stable:       6.9.3  2024-07-17 (1614) 368MB -
  6.x/candidate:    ↑
  6.x/beta:         ↑
  6.x/edge:         6.10.0 2024-07-17 (1615) 413MB -
```

I just tested it again to calm my nerves:
```console
$ journalctl -f    # notice lots of audit messages
$ snap refresh rocketchat-server --channel=6.x/edge

$ snap connect rocketchat-server:mount-observe
$ snap connect rocketchat-server:system-observe
$ snap connect rocketchat-server:network-observe
$ journalctl -f    # notice lack of audit messages 🥳
```

**Comment by joaomezzari** [comment]
I'm on 6.11.1 and this issue still persists. I have to adjust the apparmor profile file everytime RocketChat snap updates.

**Comment by slyk** [comment]
Same for me, snap 6.11.1 again this spamming of the logs. Every update manually fix files to add permissions.

Why the issue is closed?

**Comment by reetp** [comment]
If this still exists please provide some info eg this from the PR

https://github.com/RocketChat/server-snap/pull/70

Just saying "me too" with no additional information is not helpful.

Exactly what errors are logged?

Devs need to understand exactly why you might be different.

**Comment by joaomezzari** [comment]
> ![image](https://private-user-images.githubusercontent.com/10034821/344131799-6431ee7a-137a-4bc6-bed4-56f762ffb2cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODMxNzIsIm5iZiI6MTcyNDY4Mjg3MiwicGF0aCI6Ii8xMDAzNDgyMS8zNDQxMzE3OTktNjQzMWVlN2EtMTM3YS00YmM2LWJlZDQtNTZmNzYyZmZiMmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE0MzQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNGFmYTU1MmU1YzAwN2UyNDM0ODIyMTVjNzcwOTI3YjlkOTVhZDkzYWRkNWRhYTM2NjMzMzYzODQ2ZTI5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.szBjpHX9YuA-g2HcCslS16i9yXqrD6LXF3rW145ENFI) got journal full of app armor errors and that is filing up logs. every update had to fix apparmor files. Are you sure the issue is closed?

Exactly this.

**Comment by reetp** [comment]
> Exactly this.

See my comment above.

We need to try and find out why you might be different as the original issue appeared to be fixed under testing.

> If this still exists please provide some info eg this from the PR

^^^^^^^

Please help us to help you.

Do you have any remote mounts?

**Comment by sporqist** [comment]
@slyk @joaomezzari Did you connect the new snap plugs already? Please run the following command and check if `mount-observe`, `system-observe` and `network-observe are connected`:
```console
snap connections rocketchat-server
```

If they are not, you can connect them by running this command for each of them:
```console
snap connect rocketchat-server:mount-observe
```

Please also provide your OS, snap and AppArmor version just in case.

**Comment by joaomezzari** [comment]
> @slyk @joaomezzari Did you connect the new snap plugs already? Please run the following command and check if `mount-observe`, `system-observe` and `network-observe are connected`:
> 
> ```
> snap connections rocketchat-server
> ```
> 
> If they are not, you can connect them by running this command for each of them:
> 
> ```
> snap connect rocketchat-server:mount-observe
> ```
> 
> Please also provide your OS, snap and AppArmor version just in case.
Hi, this is the output of `snap connections rocketchat-server`
OS: Ubuntu Server (18.04)
Snap:  2.61.4
Apparmor: 2.12-4ubuntu5.3 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/5c1354e0-b179-481a-880c-cc48e686b9c5">

Problem came back by itself and this time it didn't even need the Rocketchat to update (I disabled the auto update because this problem is just freezing the server, I have to go to the AWS console to reboot it)

**Comment by sporqist** [comment]
@joaomezzari Thank you for providing this information. So the snap plugs and slots help defining the AppArmor profile that gets generated for the snap. This allows us to restrict, what files and processes a snap can access. Accesses that are not allowed will be denied by AppArmor. 

I see you already connected `rocketchat-server:mount-observe` but `network-observe` and `system-observe` are not connected yet. Please connect them like I described in my comment above:
```console
snap connect rocketchat-server:mount-observe # already done on your side
snap connect rocketchat-server:network-observe
snap connect rocketchat-server:system-observe
```

The errors should stop showing up after doing so.

**Comment by joaomezzari** [comment]
@sporqist Thank you very much for your help! I connected all the plugs, and I'll monitor if the problem stops, I'll keep u updated

**Comment by sporqist** [comment]
@joaomezzari If you are unsure about what interfaces to connect or the errors continue to show up in the log, you can run [snappy-debug](https://snapcraft.io/snappy-debug) in another shell. It will tell you what paths a snap app tries to access and which [slot](https://snapcraft.io/docs/interface-management) corresponds to that path.

**Comment by sporqist** [comment]
@Faria1212 This problem will keep popping up as these snap plugs won't auto-connect unless someone puts in a request to allow auto-connection [like described here](https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks).

I would love to document this in [Deploy -> Deploy Rocket.Chat -> Deploy with Snaps](https://docs.rocket.chat/docs/deploy-with-snaps) but sadly the docs are not open source anymore. This is my proposal:

~~~markdown
# Snap interface connections
After installing Rocket.Chat via Snap, connect the following Snap interfaces to ensure proper functionality:

```console
sudo snap connect rocketchat-server:mount-observe
sudo snap connect rocketchat-server:network-observe
sudo snap connect rocketchat-server:system-observe
```

This step is crucial for enabling necessary permissions during setup. Skipping this step results in AppArmor denying access to critical system resources, leading to numerous "AppArmor denied" errors. These errors can flood system logs and consume lots of disk space if log-retention is not configured on your system.
~~~

**Comment by reetp** [comment]
> @Faria1212

Pleasw don't @ people. You are more likely to be ignored or muted than listened too.

> This problem will keep popping up as these snap plugs won't auto-connect unless someone puts in a request to allow auto-connection [like described here](https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks).

It's open source. Anyone can do that, including you.

Github is like the tip of an iceberg. You  can't see the enormous machinery behind it. Including paying customers, who come first.

> I would love to document this in [Deploy -> Deploy Rocket.Chat -> Deploy with Snaps](https://docs.rocket.chat/docs/deploy-with-snaps) but sadly the docs are not open source anymore. 

> This is my proposal:

Did you read these links?

https://developer.rocket.chat/docs/documentation-contribution-guidelines

https://github.com/RocketChat/docs

Add your comments or changes accordingly.

-----------------------


I'm sure the devs will look at this in due course, in line with Product, Sales, Marketing and paid Support....

**Comment by sporqist** [comment]
@reetp Fair point but please be aware of the context. This is not the first time I contribute to RC or it's docs. The docs (docs and developer-docs) have been archived recently and contributions via GH are not possible anymore. I felt confident to directly tag Faria1212 as she also reviewed my last contribution to the docs before they archived the repo. I think the '❤️' on my comment suggests I'm not completely wrong about this.

The "Was this article helpful?" does not feel like a proper way to propose changes and I did have a proper text ready to share so there is that.

I will not open a request for snap interface auto-connects as this is a sensitive security topic and I think this should be done by the snap's maintainer or someone else from Rocket.Chat and not by some random contributor like me. Apart from this, my time is limited and I worked on this Issue mainly because the log spam was a problem for our server. Not that this is fixed upstream and we are able to configure servers to not get their logs spammed in a non-hacky way, I'm more than satisfied and don't expect to continue to work on this specific topic. However, I felt it was necessary to conclude this topic by assisting joaomezzari and contributing the last missing piece of information to the docs.

**Comment by reetp** [comment]
> @reetp 

What did I just tell you not to do? Thanks.

> The "Was this article helpful?" does not feel like a proper way to propose changes 

` But you can still contribute to the evolution of our documentation by following these [new guidelines](https://developer.rocket.chat/docs/documentation-contribution-guidelines)`

It is now THE way to do it, like it not (no, I am no fan but it's their choice, not mine)

> I will not open a request for snap interface auto-connects

Snap is open source..... Whether Rocket will or not I have no idea. They are aware of this.

> my time is limited

Yup, that applies to all of use. You are not definitely not unique.

**Comment by joaomezzari** [comment]
@sporqist Imagine taking your time to help the community and having to read all this lol. 

Thanks again for your help.
