### ISSUE TITLE
Cannot download free apps from marketplace

### ISSUE THREAD

**Issue by the4ndy** [RocketChat/Rocket.Chat#15086]
### Description:

Previously, I had no trouble installing apps from the marketplace to my locally hosted instance of rocket.chat. Now when I go to install an app from the marketplace, free or otherwise, it asks for a "payment method" and has fields to fill in a credit card. If i skip those fields and check the TOS box the "GET" button is active, but clicking it does nothing. Even with valid payment information, nothing happens.

### Steps to reproduce:

1. Go to Administration
2. Click Marketplace
3. Attempt to install any app (with or without payment info)

### Expected behavior:

The app installs

### Actual behavior:

Nothing happens. The pop over window doesnt close, no toast notifications, nothing in the log viewer.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 18.04
- Deployment Method: Snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: n/a
- MongoDB Version: n/a

### Additional context

The only noticable difference between when it did and didnt work was the addition of the "Payment information" section in the install screen of the app.

Also i have tried disconnecting / logging out of the Rocket.Chat Cloud service and logging back in on my instance. No change.

### Relevant logs:

Unsure which logs are relevant, let me know which ones are needed and I can gather them.

**Comment by jherman** [comment]
I am having the same exact issues.

**Comment by geekgonecrazy** [comment]
we rolled out some new changes for the upcoming release looks like something went wrong.  We are taking a look at this now

**Comment by geekgonecrazy** [comment]
Should now be resolved 👍  Closing

**Comment by jherman** [comment]
Just an FYI, I no longer see the CC inputs, however it still won't install apps and this shows in the chrome dev console:
![image](https://user-images.githubusercontent.com/276792/62238188-50db0a80-b387-11e9-8c17-b1fa039489c2.png)

**Comment by geekgonecrazy** [comment]
Looks like hadn't fully rolled out on the backend sorry about that.  It should now work

**Comment by jherman** [comment]
Success!
