### ISSUE TITLE
Block third-party cookies

### ISSUE THREAD

**Issue by vivekkhatri** [RocketChat/Rocket.Chat#15616]
As per the news, Google is planning to block third-party cookies in chrome browser by default. If that happens, I guess Rocket Chat won't be able to load while integrated within an iframe in a system hosted on different domain.
I have tried modifying that setting in browser to reproduce the possible issue and certainly Rocket Chat in iframe didn't load. Although, the error occurred on "app/ui-utils/client/config.js" line no. 5 and the error in browser console says "failed to read the 'localstorage' property from 'window' access is denied for this document". Hence, regardless the browser setting name says "cookies", it will block all the storage areas of the browser.
Anyone have any thoughts or workarounds when this setting is turned on by default in browsers?

Reference: https://www.bleepingcomputer.com/news/google/google-chrome-starts-testing-third-party-cookie-blocking/

**Comment by neil-119** [comment]
Any news on this?

**Comment by obonyojimmy** [comment]
This was fixed , and is configurable in the admin side of chat server. Go to administration -> General or `https://chatserver-domain/admin/General` , check off the _**Restrict access inside any Iframe**_  option .

**Comment by radukg** [comment]
Even having "Restrict access inside any Iframe" set to off issue still can be reproduced, any suggestions or plans to fix iframe integraion?

**Comment by MetahumanFamily** [comment]
Issue still persisting with option disabled. Any updates?

**Comment by wizhippo** [comment]
I still have this also on 3.11.0 with "Restrict access inside any Iframe" disabled

**Comment by wizhippo** [comment]
I believe the the issue stems from

https://github.com/RocketChat/Rocket.Chat.Livechat/blob/03bee24daf382ccf555f1a1937624727689203da/src/store/Store.js#L4

Here when window is destructed it try to access window.localStorage which throws the error.

We could check for this such as

`try {
	const { localStorage, sessionStorage } = window;
} catch (e) {
	// Failed to read the 'localStorage' property from 'Window'
	const { sessionStorage } = window;
}
`

And later in persist skip persisting if  localStorage is not available.

Thoughts?

**Comment by jschirrmacher** [comment]
I would really appreciate if this would be included in Rocket.Chat!
