### ISSUE TITLE
Search bar doesn't fit to end of sidebar

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#15720]
### Description:
The search bar doesn't fit to the end of the sidebar.
![image](https://user-images.githubusercontent.com/6295044/68073805-5bcc7f00-fd6a-11e9-9b00-dff16bb45cb1.png)

### Steps to reproduce:

1. Press on the magnifying glass in the top left of the sidebar.
2. Search doesn't fit to the sidebar

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/68073848-b2d25400-fd6a-11e9-82e4-9f81c871296e.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/68073852-b960cb80-fd6a-11e9-87f7-26ac9de15276.png)

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat - 2.3.0-develop

### Client Setup Information

- Desktop App or Browser Version: 2.15.5
- Operating System: Windows 10

**Comment by nishantwrp** [comment]
@wreiske I can't reproduce this issue too, this seems to be fixed

**Comment by ashwaniYDV** [comment]
@wreiske I think this issue is fixed. Kindly close this issue :)

**Comment by wreiske** [comment]
This is still an issue.

![image](https://user-images.githubusercontent.com/6295044/72915459-526e0580-3d0e-11ea-81f9-42a7202a0462.png)

**Comment by wreiske** [comment]
This is still an issue as of today on open.

![image](https://user-images.githubusercontent.com/6295044/88545399-f18af700-cfe8-11ea-99b4-a1a25784770f.png)

**Comment by wreiske** [comment]
I hate you, stalebot!!! 😠 😤

**Comment by gabriellsh** [comment]
Hey @wreiske, on the latest release we introduced the new sidebar written in react, and this should be fixed now. Sorry for stalebot being so persistent :p

**Comment by wreiske** [comment]
@gabriellsh it looks beautiful!
![image](https://user-images.githubusercontent.com/6295044/99457138-b853fb00-28e7-11eb-9fce-df8f17b8a450.png)

Thank you :)

**Comment by gabriellsh** [comment]
I'm glad you liked it, I'll tag @ggazzo so he can read the compliment too!

**Comment by ggazzo** [comment]
:v:
