### ISSUE TITLE
Better Syntax highlighting

### ISSUE THREAD

**Issue by joshkel** [RocketChat/Rocket.Chat#1593]
Syntax highlighting for ``` code blocks would be nifty.

My personal preference would be for something like [GitHub Flavored Markdown's syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting), simply because that's what I'm most familiar with, but I don't have a strong opinion on this.

**Comment by geekgonecrazy** [comment]
So turns out this is kind of here.  But it needs improved a lot before its really going to be useful.

**Comment by engelgabriel** [comment]
I don't understand.. we already have the feature.. so what is the request here?

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/11659006/231f8f42-9dad-11e5-899f-811b2091372f.png)

**Comment by joshkel** [comment]
From playing around with this, there are several shortcomings. For example:

I don't see the ``` syntax documented anywhere in the current software. (The only information I can find on formatting in general is a bullet point mention of "Markdown" under features and a very brief list of some syntax in the lower right corner of chat.)

I can't find any list of supported languages.

The syntax highlighting isn't very good. For example:
* In your example, `require` should be highlighted as a keyword.
* `array` shows up as a built-in in C++ code. (It isn't.)
* The attached screenshot shows the same code highlighted differently C and C++, but C and C++ should be highlighted the same in this case. (The C version is mostly correct - printf shouldn't be highlighted as a built-in, IMO, and highlighting `%i` within the string is correct - although neither version correctly gives keywords `for` and `int` a different appearance than the variable name `i`).
![2015-12-09 11_25_26-rocket chat](https://cloud.githubusercontent.com/assets/476338/11691113/9d55c2bc-9e67-11e5-87d8-1e4a8c3cfcd8.png)

None of this is a high priority for us right now, but if you'd like me to open any of these as separate issues, please let me know.

**Comment by engelgabriel** [comment]
Did you specify the language after the ```? 

We currently use https://github.com/stubailo/meteor-highlight.js/tree/master

But we can add support to https://github.com/codemirror/codemirror if you think it is more powerful?

**Comment by fduraibi** [comment]
I think we need an option to not highlight the code, currently it always highlights which is not always the right thing. for example it highlights command line instructions incorrectly:
![rocket](https://cloud.githubusercontent.com/assets/432460/12360565/ba3a119e-bb86-11e5-97bd-45f82bace78d.png)

my work around is to label it as java (and that works most of the time, might not always be true)

![rocket1](https://cloud.githubusercontent.com/assets/432460/12360583/d4567068-bb86-11e5-81ac-9ed30be8c6ea.png)

also as you see it is not working correctly under Firefox, as the backtick is causing some problem. While in chrome it works fine (same output on chrome)
![rocket2](https://cloud.githubusercontent.com/assets/432460/12360617/fcce7be4-bb86-11e5-88f5-1f0654a5a171.png)

**Comment by geekgonecrazy** [comment]
Seems like maybe we should look at codemirror.  Or something with a bit better syntax highlighting

**Comment by vetash** [comment]
+1

**Comment by Deadlyhacker** [comment]
Yes add this please +1

**Comment by jseadragon** [comment]
+1, I'd love to see this get improved. Being a C++ developer,  I second everything that @joshkel said about the C / C++ syntax highlighting.

**Comment by engelgabriel** [comment]
@rodrigok now that we have codemirror, should we use it for the Syntax highlighting?

**Comment by reyman** [comment]
I try to highlight scala code, but it seems not supported using ```scala :/
Any news here ?

**Comment by Franziskus1988** [comment]
Do you have an up-to-date documentation about the code highlighting topic with a list of supported languages and explanation on how to use this. It seems this site is outdated: https://sourceforge.net/p/rocketchat/wiki/markdown_syntax/

**Comment by geekgonecrazy** [comment]
@Franziskus1988 i'm not sure where that particular documentation came from.  But our official documentation can be found here:  https://rocket.chat/docs  And nothing more detailed then that currently, sorry.

**Comment by b0c1** [comment]
The main problem with using meteor highlight js is: the integrated highlight js is 2 years old.
Not plan to upgrade the highlight js (in a forked repository) or using highlight.js directly in the application.

**Comment by Rohlik** [comment]
This is solved in https://github.com/RocketChat/Rocket.Chat/commit/ffc0bdaed34af88bddc16d7eedb2cfeb635cd0d3, right?

**Comment by joshkel** [comment]
@Rohlik - From testing the Docker image of 0.54.0, most of the problems I listed [here](https://github.com/RocketChat/Rocket.Chat/issues/1593#issuecomment-163316575) are still an issue:

1. Whatever theme or stylesheet is being applied fails to give keywords their own color.
2. I can't find any official list of supported languages. ([This](https://github.com/isagalaev/highlight.js/tree/master/src/languages) and [this](https://highlightjs.org/static/demo/) seem to work.)
3. `array` shows up as a built-in in C++ code. (It isn't.)
4. The issue I mentioned about C versus C++ no longer exists, because Highlight.js doesn't support C as a separate language. (That's surprising, but I can live with it.)

3 and 4 are issues in Highlight.js itself, but I believe 1 and 2 are within Rocket.chat and its docs.

**Comment by xenithorb** [comment]
I just want to be able to have "text" highlighting, In any other highlighter this would be synonymous with "Disable highlighting, but still have preformatted text blocks".

Generally I would expect
```
:::text
:::txt
```text
```txt 
```
But those don't do anything. Note how on github, it doesn't get confused by the use of triple backticks inside triple backticks, either.

**Comment by dannysauer** [comment]
Lack of message formatting documentation is referenced in RocketChat/docs#971

**Comment by brahmaparush** [comment]
> Did you specify the language after the ```?
> 
> We currently use https://github.com/stubailo/meteor-highlight.js/tree/master
> 
> But we can add support to https://github.com/codemirror/codemirror if you think it is more powerful?

How to specify the language after the ```?

**Comment by Rohlik** [comment]
@brahmaparush Something like that:
```
```js
or
```java
```

**Comment by Franziskus1988** [comment]
@Rohlik 
![image](https://user-images.githubusercontent.com/5774027/52855902-15bf8480-3123-11e9-9263-38df00d25abd.png)

==>>

![image](https://user-images.githubusercontent.com/5774027/52855923-2ff96280-3123-11e9-9554-ddee7e818711.png)

I think it doesn't work as desired...

**Comment by MacGyver27** [comment]
@Franziskus1988 haha definitely.. came here to report this problem..

have an example from the webex teams chat.. we use it internally and its markdown is almost perfect.. 
` ```{language}` it accepts syntaxes like: js, ts, java, py, bash, regex, html, css, scss, scala, c,...

please fix.. also what about giphy and similar?? no memes no fun ;)

**Comment by engelgabriel** [comment]
We are not going to use the Codemirror for this because it is a full-blown text editor, and it would be heavy, and not something that can be used in the React Native apps. 

*We want to keep it fast and consistent between platforms.*

_Please notice that `js` is not a valid syntax definition, you should use `javascript`. The full list can be found at https://highlightjs.org/static/demo/ and we are currently using the `Github` color style._

**Comment by octoxan** [comment]
This doesn't seem to work?
![image](https://user-images.githubusercontent.com/4382195/78906009-cd60d580-7a4c-11ea-87a7-fab93a5250d1.png)

**Comment by feitosa-daniel** [comment]
@octoxan I think it works. It seems that the default format is HTML,XML (don't include the language). 

![Screenshot_2020-08-11_21-35-33](https://user-images.githubusercontent.com/1847734/89942042-2bc8db00-dc1c-11ea-872a-4dcc17a88768.png)


However, the bold formatting of code blocks damages the `Github` style. Some languages (e.g., Python) use bold font for keywords. I adjusted that by adding the following snippet to *Administration* > *Layouts* > *Custom CSS*:

```css
.rc-old code {
	font-weight: normal;
}
```

**Comment by dpr989** [comment]
This absolutley does not work.. unless someone can (please) prove me wrong. Is not a super complicated feature. Would be nice to have. Current syntax highlighting behavior is pretty much non-existent, might as well not have it.

**Comment by leagris** [comment]
@engelgabriel would it be considered to re-open this issue as it is not fixed or would you mind commending on the close reason or what is the intent from the rocket.chat team about this syntax highlighting issue?

**Comment by sschneider-ihre-pvs** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/5c1a7623b3ef9d65b169e245a3a5b918c114bd5a/app/markdown/lib/hljs.js
just to let you know what languages seem to be supported and what to write after ```

**Comment by sschneider-ihre-pvs** [comment]
Alas, not all of them also work.
