### ISSUE TITLE
Once pinned the message cant be unpinned.

### ISSUE THREAD

**Issue by milannshrestha** [RocketChat/Rocket.Chat#16543]
### Description:

I'm not sure if I'm the only one to face this problem but, once i pinned the message on any channel, i cant unpin the message although there is option for 'Unpin' 

### Steps to reproduce:

Pin message

Message in channel 'user Pinned a message:'

Open Pinned list.

See Pinned message.

Unpin message.

Message still in Pinned list.

No notification in channel messages.

Close Pinned list.

Open Pinned list and message has disappeared from list (presumably the Pinned list has now been refreshed)

### Expected behavior:

message should unpin

### Actual behavior:

nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by MartinSchoeler** [comment]
Also does any errors happen? can you see the message on the pinned sidebar after unpinning? Thanks!

**Comment by milannshrestha** [comment]
So, this is the issue, 
[](https://imgur.com/978BlP9)

**Comment by milannshrestha** [comment]
Would you please look into POC [here](https://imgur.com/978BlP9)

**Comment by reetp** [comment]
On 3.0.7

Pin message

Message in channel 'user Pinned a message:'

Open Pinned list.

See Pinned message.

Unpin message.

Message still in Pinned list.

No notification in channel messages.

Close Pinned list.

Open Pinned list and message has disappeared from list (presumably the Pinned list has now been refreshed)

**Comment by milannshrestha** [comment]
Thank you @reetp for figuring out the issue according to Issue Guidelines, I hope @MartinSchoeler got this one and acknowledge the bug,

**Comment by reetp** [comment]
This bug still exists in open.rocket.chat - presumably on 3.7.x

Only difference I can see is you get a little green notifier top right to say it has been unpinned, but the rest is exactly the same.

Martin added "Waiting for response"  and I responded with a description of the issue so I am not sure why it has been ignored.

**Comment by MartinSchoeler** [comment]
This one got under the radar, sorry for that. Updated the issue description and reopened it

**Comment by milannshrestha** [comment]
Thanks :D

**Comment by MartinSchoeler** [comment]
@milannshrestha should be working now, there is only a small visual bug to fix, the pinned messages sidebar wont automatically update. Hopefully the pr above fixes this. Thanks!

**Comment by billynoah** [comment]
This is not fixed.  I pinned a message today and after unpinning the message it disappears out of Pinned Msgs sidebar but the pin is still there.  I've even deleted the original but the pin continues to show my original message.
