### ISSUE TITLE
Discussion link, when clicked, says "invalid or expired invite token"

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#16975]
### Description:

Immediately after generating an invitation link and then trying to use it, the following is shown:

![image](https://user-images.githubusercontent.com/4859660/77326899-dafa2980-6cf0-11ea-9be5-57c0b789744f.png)

### Steps to reproduce:

1. go to a discussion
2. click the Members List
3. click Invite Users
4. copy the generated link
5. paste the link in a new tab
6. "invalid or expired invite token" error is shown

### Expected behavior:

Invite link should not expire immediately.

### Actual behavior:

Invite link appears to expire immediately, or otherwise does not work.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1
- Operating System: RHEL7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.17.0
- MongoDB Version: 4.0.9

### Client Setup Information

- Desktop App or Browser Version: Chrome 80.0.3987.132
- Operating System: Manjaro Linux 19.0.2

### Additional context

We host RC in a sub-directory and have a proxy server in front of RC.

**Comment by bbrauns** [comment]
duplicate #16852

**Comment by pierre-lehnen-rc** [comment]
Fixed by #17226

**Comment by brie-gilvin** [comment]
This is still broken and has been since we put the ticket in. Can someone let us know the true status

**Comment by rosscdh** [comment]
still even now

**Comment by krumelmonster** [comment]
Still in 4.5.2. This is bad

**Comment by 87113** [comment]
I confirm, it's still there in the 4.5.2 ! 

The strange thing is the route `api/v1/validateInviteToken` send `{"valid":true,"success":true}` !!
