### ISSUE TITLE
Searching for an invalid RegExp shows UNDEFINED

### ISSUE THREAD

**Issue by jinnear** [RocketChat/Rocket.Chat#1721]
When searching for a string such as '(', which is an invalid regular expression the message 'Showing undefined results' is displayed.
![screen shot 2015-12-21 at 17 45 15](https://cloud.githubusercontent.com/assets/10801000/11935943/e91e9104-a80a-11e5-8d6a-ea8e77f5e6c7.png)
I think there should be some error checking in order to display the 'Showing 0 results' message when an invalid regex is entered.
##

**Comment by Joshua-Anderson** [comment]
I think that could be confusing because that would lead me to think that my regexp was valid but not finding anything. Maybe use a better error message like `Invalid Regexp` instead of `Undefined`?

An option to choose whether or not you want to search using a regexp would also be nice, because in this case it doesn't look like you intended `)` to be treated as a regexp.

**Comment by matthias-brun** [comment]
Good point actually. I didn't realize that searching with regexes was a thing until I got that error message. An option to choose whether or not to use a regex for searching would probably be the best solution indeed.

**Comment by alexbrazier** [comment]
I think this has been resolved in #3850

**Comment by ggazzo** [comment]
@RocketChat/core the problem still persists on ```history/private``` but the link doesn't exist anymore.
What should I do? Fix the problem? delete the route?

**Comment by sampaiodiego** [comment]
I think we don't need this page anymore.. that's why the link were removed.

**Comment by MartinSchoeler** [comment]
@sampaiodiego so should this issue be closed?

**Comment by sampaiodiego** [comment]
@MartinSchoeler no.. we have to decide to whether remove the page or fix it.
