### ISSUE TITLE
Bug SAML logout 

### ISSUE THREAD

**Issue by 1rV1N-git** [RocketChat/Rocket.Chat#17319]
### Description:
Bug SAML logout 

I think there is

https://github.com/RocketChat/Rocket.Chat/blob/8e6fa4a051ab4f3080f7e45ae967e8000ae14087/app/meteor-accounts-saml/server/saml_utils.js#L389

need use NameID instead saml:NameID or both tagName 

`const nameIdNode = request.getElementsByTagName('NameID')[0];`

because ADFS send that LogoutRequest

`<samlp:LogoutRequest ID="_393dee5c-1475-4e98-a503-233778f66ba7" Version="2.0" IssueInstant="2020-04-15T19:46:59.424Z" Destination="https://chat.domain.com/_saml/logout/chat_auth/" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" NotOnOrAfter="2020-04-15T19:51:59.424Z" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://adfs.domain.com/adfs/services/trust</Issuer><NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">o.test@domain.com</NameID><samlp:SessionIndex>_ebf844e5-9f11-4d1f-9a95-eb9d675fefaa</samlp:SessionIndex></samlp:LogoutRequest>`

Similar issues
https://github.com/RocketChat/Rocket.Chat/issues/14881
https://github.com/RocketChat/Rocket.Chat/issues/7194

**Comment by pierre-lehnen-rc** [comment]
Was this logout initiated from Rocket.Chat or was the request sent to Rocket.Chat from the IdP?

**Comment by pierre-lehnen-rc** [comment]
@1rV1N-git Can you help us test if the linked PR alone fixes the logout or if there's any other incompatibility?

**Comment by 1rV1N-git** [comment]
@pierre-lehnen-rc Yes. I have tested now. It is working!  Thanks.

**Comment by 1rV1N-git** [comment]
I noticed what when users logout through SAML. 
It is clear all token for all devices. 

And logout work 50\50 :) and I down know why)
After a bad log out I see services.saml.inResponseTo in user doc in DB

**Comment by Guile17** [comment]
@1rV1N-git how did you make it work? I'm able to see the request from Rocket Chat in the Logs, but it does log the user out from the ADFS portal.

**Comment by pierre-lehnen-rc** [comment]
Do you have any logs from the request on ADFS?

**Comment by Guile17** [comment]
I don't see any request there.
But now, I'm kind of lost.
My configurations between RC and ADFS are not correct.

**Comment by pierre-lehnen-rc** [comment]
Can you enable debug mode on the SAML settings and try again to get the request xml from the logs?

**Comment by Guile17** [comment]
@pierre-lehnen-rc 
![image](https://user-images.githubusercontent.com/58185841/83301926-72379d80-a1c8-11ea-8f04-84ebf2fd2355.png)

**Comment by pierre-lehnen-rc** [comment]
Based on these logs, Rocket.Chat sent a LogoutRequest to adfs, who replied with a sloRedirect.

When we receive an sloRedirect we only redirect the browser, without doing anything else. Maybe we should be logging the user out on that step. I'll look into it.

**Comment by Guile17** [comment]
@pierre-lehnen-rc do you have an ETA? no pressure.

**Comment by pierre-lehnen-rc** [comment]
HI @Guile17, do you have more service providers connected to the same SAML server? are all of them logging the user out properly?

**Comment by pierre-lehnen-rc** [comment]
Oh, I just realized that that sloRedirect was initiated by the SAML client on our side, so there was no response from the ADFS at all on those logs you provided. Can you check if there's anything else in there after that part?

**Comment by Guile17** [comment]
@pierre-lehnen-rc I'm getting the following log on ADFS side ( MSIS0038: SAML Message has wrong signature )
I'm not sure if RC configuration is correct? What certificate and key should I use?

**Comment by Guile17** [comment]
@pierre-lehnen-rc  I've figured out why I was getting that error, and I fixed it. But I still don't see any logs on my ADFS and the user doesn't log out. I'm wondering if the request that RC sends to ADFS is right.

**Comment by Guile17** [comment]
@pierre-lehnen-rc After a while, the error that is been presented in ADFS side is:

![image](https://user-images.githubusercontent.com/58185841/83535612-29316300-a4c0-11ea-8938-a0a62728d9e7.png)

**Comment by Guile17** [comment]
@pierre-lehnen-rc Using a SAML tracer on my browser, I found out the request, which doesn't have the email address, as you can see. Do you know what I should change on the RC side to make it work?

![image](https://user-images.githubusercontent.com/58185841/83537789-09e80500-a4c3-11ea-90f2-eb6a3f578971.png)

**Comment by pierre-lehnen-rc** [comment]
Ah, that's the same bug as issue #7194
I've fixed it on #17742, which will probably be included on the next monthly release.

**Comment by Guile17** [comment]
Thank you.

**Comment by Guile17** [comment]
Hi @pierre-lehnen-rc, 
Sorry to bug you again, but after the update to 3.3.0 version the logout still not working. 
The NameID is not showing the email address.

**Comment by pierre-lehnen-rc** [comment]
Yes, sorry, I meant 3.4. The 3.3 version was already closed in the release candidate stage at that point, so that PR couldn't be included in it.

**Comment by pierre-lehnen-rc** [comment]
We've included the fix on 3.3.1:
#17860

**Comment by Guile17** [comment]
Hi @pierre-lehnen-rc, I've updated to 3.3.3 and still not working. 
The first image is the error event that appears on my ADFS. The second one is the request from RC.
I have no idea what the NameQualifier value is on the error.

Is there anything else that I need to configure on RC?

![image](https://user-images.githubusercontent.com/58185841/84528087-0ae01a00-acad-11ea-9039-d79513ad3196.png)
![image](https://user-images.githubusercontent.com/58185841/84528379-98236e80-acad-11ea-9be1-53e612979484.png)

**Comment by pierre-lehnen-rc** [comment]
My guess is that adfs expects Rocket.Chat to send a NameQualifier on the initial login request as well. Can you open a new issue about this and tag me?
