### ISSUE TITLE
cronProcessDownloads: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#17714]
### Description:

Seeing the log message below repeatedly.

### Steps to reproduce:

No steps, noticed this while viewing the log.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: RHEL 7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.9

### Relevant logs:

> === UnHandledPromiseRejection ===
> TypeError: Cannot read property 'filter' of undefined
>     at app/user-data-download/server/cronProcessDownloads.js:50:57
>     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1102:16)
>     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:882:44)
>     at loadUserSubscriptions (app/user-data-download/server/cronProcessDownloads.js:46:9)
>     at app/user-data-download/server/cronProcessDownloads.js:498:3
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
>  => awaited here:
>     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
>     at app/user-data-download/server/cronProcessDownloads.js:567:2
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by JoshMcCullough** [comment]
Also what is this CRON job even for?

**Comment by sampaiodiego** [comment]
this cron job is in charge of processing users' "download my data" requests..

**Comment by pierre-lehnen-rc** [comment]
Fixed by #17577

**Comment by maiconbaumx** [comment]
I'm facing a similar issue after upgrading to 3.5.0.

```
 === UnHandledPromiseRejection ===
 TypeError: Cannot read property 'filter' of undefined
 at app/user-data-download/server/cronProcessDownloads.js:51:59
 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1138:16)
 at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:918:44)
 at loadUserSubscriptions (app/user-data-download/server/cronProcessDownloads.js:47:9)
 at app/user-data-download/server/cronProcessDownloads.js:499:3
 at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
 at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
 at app/user-data-download/server/cronProcessDownloads.js:577:2
 at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ---------------------------------
 Errors like this can cause oplog processing errors.
 Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
 Future node.js versions will automatically exit the process
 =================================
```

**Comment by sampaiodiego** [comment]
@maiconbaumx what version were you using before upgrading? the `uids` field was created by https://github.com/RocketChat/Rocket.Chat/pull/16761/ released on version 3.1.0 .. I wonder if you missed a migration 🤔
