### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by wtsarchive** [RocketChat/Rocket.Chat#1793]
There is a serious issue when uploading files. First time when a session starts it works fine, but if you try to upload another file, the same file gets uploaded for some reason. Also, when you try to delete a message afterwards, it will upload the file again!
Steps to reproduce:
1. Login to chat / refresh the page to get clean results
2. Upload a file
3. The file should be uploaded successfully
4. Try uploading a different file
5. Observe that it was the previous file that is uploading now
6. Try to delete last message with uploaded file
7. Observe that the file gets uploaded again, and the message is NOT deleted (!)

There is a similar issue with deleting messages. Deleting first one works, but when you try to delete another one, it doesn't do anything.

_NOTE: This is a regression, it was working fine until one of recent updates (v0.10 I think)._

**Comment by Megatronic79** [comment]
Hey @wtsarchive i just tried with v0.11.0 and uploading and deletions seems to be working ok with the desktop app and the browser,can you try latest version and confirm it fixed in that version?

**Comment by wtsarchive** [comment]
@Megatronic79 I just tried on v0.11.0 and it's still not working for me. It was also not working for other chat users, so that's definitely not an issue with my computer. Here's the `/api/info` output:

```
"version": "0.11.0",
  "compile": {
    "date": "2016-01-03T02:30:01.234Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "darwin",
    "osRelease": "15.2.0",
    "totalMemmory": 8589934592,
    "freeMemmory": 43220992,
    "cpus": 4
  }
```
