### ISSUE TITLE
apparmor config is incorrect in snap

### ISSUE THREAD

**Issue by zedsinn** [RocketChat/Rocket.Chat#18086]
### Description:

The following errors persistently appear in the system log.

```
audit[1046]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1046/net/netstat" pid=1046 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit[1046]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1046/net/snmp" pid=1046 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

### Steps to reproduce:

1. Install rocket chat using the snap.
2. Allow the server to run for any length of time. 
3. Inspect system log by running command `journalctl -f`.

### Expected behavior:

No errors in system log.

### Actual behavior:

Many errors in system log that are continually generated - See description for errors that appear persistently.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu 18.04 LTS (AWS)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ???
- NodeJS Version: Not installed.
- MongoDB Version: ???

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context

The workaround fix is documented here - please include this in the next snap update
https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-498321790

### Relevant logs:

See description.

**Comment by zedsinn** [comment]
This is still an issue and should not be marked stale.

**Comment by PH-Bluechain** [comment]
Issue has been happening for a year and a half now, really could do with it being fixed.

**Comment by RodrigoFerrazsc** [comment]
Same problem here...and it keeps happening

**Comment by metalcated** [comment]
Here too.

**Comment by tribetrb** [comment]
Same issue here,
< audit: type=1400 audit(1613349376.996:2594): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1010/net/snmp" pid=1010 comm="ftdc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
>

**Comment by SuperRoach** [comment]
I have this error too, and have jumped between three different issues flagged that had nothing come up and got marked as stale. This is a workaround that has been mentioned, but shouldn't it be standard?

https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-718067600

**Comment by Nono-m0le** [comment]
This is still true with Snap version 3.12.1

**Comment by J-U-B** [comment]
...and now also  with Snap version 3.13.1

**Comment by andweber** [comment]
still true for snap version 3.13.2

The fix mentioned in https://github.com/RocketChat/Rocket.Chat/issues/14562#issuecomment-498321790 doesn't seem to work as expected.

**Comment by andweber** [comment]
I digged a little bit deeper into this:

the network-observe plug is defined, but it is not auto-connected. Meaning - its not active by default.

`sudo snap connect rocketchat-server:network-observe`

solves this at least as a workaround. I'm not yet sure if this stays active during updates of the snap packages.

if so it should just be mentioned in the docs right before:
https://docs.rocket.chat/installation/snaps#how-do-i-add-option-to-mount-media

**Comment by CvH** [comment]
> snap connect rocketchat-server:network-observe

solved it for me too, running RocketChat with snaps in a LXC container (proxmox), do we know if this change is persistent ?

**Comment by andweber** [comment]
as far as I know its persistent

**Comment by andweber** [comment]
this issue is fixed and can be closed

**Comment by nonno-cicala** [comment]
Actually I still have the same problem on arm64.
It looks like the network-observe plug is not defined in `/snap/rocketchat-server/current/meta/snap.yaml` in the snap built for arm64

**Comment by cadirol** [comment]
same here on snap in versoin 3.17.1

**Comment by debdutdeb** [comment]
Hi there .. This **just** came to my knowledge. I'll take a look at this later this week.

**Comment by L-uva** [comment]
I'm not a user of RocketChat, I have another app that was giving me the same warning.
You can disable FTDC (https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/)  completely and the warning should disappear.
When you start up mongodb do it with this flag set.

mongod --setParameter diagnosticDataCollectionEnabled=false

Hope it helps someone!

**Comment by Ancillius** [comment]
> I digged a little bit deeper into this:
> 
> the network-observe plug is defined, but it is not auto-connected. Meaning - its not active by default.
> 
> `sudo snap connect rocketchat-server:network-observe`
> 
> solves this at least as a workaround. I'm not yet sure if this stays active during up

Can one tell me what this acutally does? And what it changes?

**Comment by tk-suzuki** [comment]
Same here on RC 4.8.3 with snap on Ubuntu 20.04/22.04.
And similarly, there are DENIED logs for the fonts directory, etc.
So I added the following lines manually.

/var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-server
- /usr/local/share/fonts r
- /usr/share/fonts r

/var/lib/snapd/apparmor/profiles/snap.rocketchat-server.rocketchat-mongo
- @{PROC}/vmstat r

**Comment by KodoGit** [comment]
> Can't seem to fix this issue, having massive trouble to update to RocketChat 6.

Had similar issue. 
Fixed by returning to my current major version snap channel and refresh to the latest minor version (5.x/stable:       5.4.10)
Only after refresh to the latest minor you can switch to the next major.

The next problem was MongoDB5 that needs CPU instructions (avx/avx2). I had to change CPU type to HOST in my proxmox vm.

**Comment by YiannisBourkelis** [comment]
Same here. 
These are some log entries from just the last 4 seconds in our server. Log is flooded with these errors.
However rocket.chat instance works fine.

`
journalctl --since "2024-11-11 11:31:00" --until "2024-11-11 18:00:00"
`

OS: Debian 11
snap: 2.61.4
Rocket.Chat: v6.13.0 
mongodb: 5.0.15 / wiredTiger (oplog Enabled)


How can we fix this?

`
Nov 11 11:31:05 server1 kernel: audit: type=1400 audit(1731317464.999:104237): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/nets>
Nov 11 11:31:05 server1 kernel: audit: type=1400 audit(1731317464.999:104238): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp>
Nov 11 11:31:04 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:04 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:05 server1 kernel: audit: type=1400 audit(1731317464.999:104239): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinf>
Nov 11 11:31:04 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
Nov 11 11:31:05 server1 kernel: audit: type=1400 audit(1731317464.999:104240): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1>
Nov 11 11:31:05 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/netstat" pid=1853 comm="ftdc" requested_ma>
Nov 11 11:31:05 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:06 server1 kernel: audit: type=1400 audit(1731317465.999:104241): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/nets>
Nov 11 11:31:06 server1 kernel: audit: type=1400 audit(1731317465.999:104242): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp>
Nov 11 11:31:05 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:06 server1 kernel: audit: type=1400 audit(1731317465.999:104243): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinf>
Nov 11 11:31:05 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
Nov 11 11:31:06 server1 kernel: audit: type=1400 audit(1731317465.999:104244): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1>
Nov 11 11:31:06 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/netstat" pid=1853 comm="ftdc" requested_ma>
Nov 11 11:31:06 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:07 server1 kernel: audit: type=1400 audit(1731317466.995:104245): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/nets>
Nov 11 11:31:07 server1 kernel: audit: type=1400 audit(1731317466.995:104246): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp>
Nov 11 11:31:06 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:06 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
Nov 11 11:31:07 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/netstat" pid=1853 comm="ftdc" requested_ma>
Nov 11 11:31:07 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:07 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:07 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
Nov 11 11:31:08 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/netstat" pid=1853 comm="ftdc" requested_ma>
Nov 11 11:31:08 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:08 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:08 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
Nov 11 11:31:09 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/netstat" pid=1853 comm="ftdc" requested_ma>
Nov 11 11:31:09 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/net/snmp" pid=1853 comm="ftdc" requested_mask=>
Nov 11 11:31:09 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/1853/mountinfo" pid=1853 comm="ftdc" requested_mask>
Nov 11 11:31:09 server1 audit[1853]: AVC apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/vmstat" pid=1853 comm="ftdc" requested_mask="r" den>
`

**Comment by stleitner** [comment]
Try this script to repair Rocket Chat snap apparmor logging: https://gist.github.com/stleitner/3ba8beff5c49a7996855712919be150d #
