### ISSUE TITLE
Integration - copy to clipboard doesn't work with Firefox

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat#1855]
I created a new integration and I'm tyring to copy the webhook URL by using the COPY TO CLIPBOARD link. It does not work with Firefox but it works well with Chromium.

Also I can't select the webhook URL manually.

Rocket.Chat 0.13.0
Firefox 43 (also tried in safe mode)

**Comment by rodrigok** [comment]
Maybe related with this issue https://github.com/zenorocha/clipboard.js/issues/155

**Comment by engelgabriel** [comment]
Fixed

**Comment by shek8034** [comment]
I am still facing the issue on firefox with bootstrap modal. Can someone confirm ?
I have posted the details in the main thread
https://github.com/zenorocha/clipboard.js/issues/155
