### ISSUE TITLE
No valid server found at the URL with latest flatpak update (3.0.0)

### ISSUE THREAD

**Issue by paolostivanin** [RocketChat/Rocket.Chat#19107]
#19107  # Description:

I'm using Rocket.Chat via flatpak on openSUSE Tumbleweed (GNOME 3.36).
Today I updated RC to version `3.0.0`, and now I'm no longer able to connect to the server. When I input the URL, I get:

`No valid server found at the URL`

Using the browser or the android app, everything works fine.

### Steps to reproduce:

1. install Rocket.Chat 3.0.0 using flatpak
2. try to connect to `chat.suse.de`
3. error received

### Expected behavior:

I should be able to reach the server

### Actual behavior:

![bug](https://user-images.githubusercontent.com/1040943/94897655-63236d80-0490-11eb-8f3b-a74fa79ddc74.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: SLES/openSUSE

### Client Setup Information

- Desktop App or Browser Version: desktop flatpak 3.0.0
- Operating System: openSUSE Tumbleweed x64 GNOME

**Comment by ankar84** [comment]
Same as https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743

**Comment by kasingal** [comment]
> Same as [RocketChat/Rocket.Chat.Electron#1743](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743)

You mentioned same as #1743, but what is the resolution ? 
I added servers.json with default servers, still not connecting to my RocketChat

Though I can access same via web browser: http://onap-integration.eastus.cloudapp.azure.com:3000/home

**Comment by paolostivanin** [comment]
this issue is fixed with 3.0.1

**Comment by kasingal** [comment]
> this issue is fixed with 3.0.1

@paolostivanin  Issue is not fixed, and facing invalid server still.. !!
Not sure why you closed the issue!

**Comment by fdellwing** [comment]
Because this is an issue of the Electron app and this is the repo for the server. So post your issue there (or take one of the many already open issues to this topic).
