### ISSUE TITLE
Black Page on certain links (ie: Twitter)

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat#19294]
### Description: 

When posting a twitter link, the "description" automatically added below contain the text, a link to the image, and the date (with its permalink url).
Clicking on the image or date link does nothing or let RocketChat in a black page (no server/room/discussion are visible anymore).

### Steps to reproduce:

1. post a twitter.com link
2. click on the date/image link
3. get a black page within the RC Window

### Expected behavior:

Openning the link on the default browser

### Actual behavior:

Black page, see : 
![image](https://user-images.githubusercontent.com/3726435/96472982-68730d00-1231-11eb-8c4f-847f0b3e0f04.png)
![image](https://user-images.githubusercontent.com/3726435/96473007-6dd05780-1231-11eb-84f6-5ea98181a57f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 3.6.14
- Proxy: caddy

### Client Setup Information

- Desktop App or Browser Version: 2.11.0 & 3.x (until 3.0.4 tested)
- Operating System: Windows 10

### Additional context

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1832

**Comment by Nono-m0le** [comment]
still true on Client version 3.0.5

**Comment by godfather2** [comment]
This issue seems to have been resolved in version 3.9 (I couldn't reproduce it, in gitpod). So it needs to be closed, right?

**Comment by Nono-m0le** [comment]
It's not fixed on the latest available over snap : 
Server: 3.8.2
Client: 3.0.7

**Comment by himani-mehra** [comment]
Hi @Nono-m0le  , I would love to take on this issue and contribute to the project. Could you please assign it to me if it's available? Looking forward to your response. Thanks!

**Comment by Nono-m0le** [comment]
> Hi @Nono-m0le , I would love to take on this issue and contribute to the project. Could you please assign it to me if it's available? Looking forward to your response. Thanks!

I'm sorry I don't use rocketchat anymore, so feel free to take it over or close it.

**Comment by Canepro** [comment]
\nI confirmed this as reproducible from the report and marked it as triaged. This looks customer-impacting, so I am escalating this to CSB Engineering for further review.
