### ISSUE TITLE
Quoting doesn't work

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat#19293]
### Description:

When I quote a text, only my additional text is visible, like a 'normal' text... no quote is working (see https://forums.rocket.chat/t/quoting-doesnt-work/8917 )

### Steps to reproduce:

1. Quote a text
2. Add additionnal text
3. Get only the additionnal text (not the original quote attached)

### Expected behavior:

Quoting to work

### Actual behavior:

quoting doesn't work.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 3.6.14
- Proxy: caddy

### Client Setup Information

- Desktop App or Browser Version: 2.11.0 & 3.x (until 3.0.4 tested)
- Operating System: Windows 10

### Additional context

Could be server side as suggested here: https://github.com/RocketChat/Rocket.Chat/issues/19291

**Comment by yasirrose** [comment]
+1

I am facing the same issue using 3.7.1 release.

**Comment by Nono-m0le** [comment]
still true with client 3.0.5

**Comment by Nono-m0le** [comment]
still true with client 3.0.6

**Comment by damian-centrone** [comment]
This is already fixed. tested on 3.8.0

**Comment by Nono-m0le** [comment]
@damian-centrone do you know when this will be available for snap install ?

**Comment by yasirrose** [comment]
@damian-centrone it is not fixed. I have tested with 3.8.0. 
Screencast: https://drive.google.com/file/d/1CybjV_D1G0GEUBfdI-hM5YuppaRiRCke/view?usp=sharing

@Nono-m0le

**Comment by Nono-m0le** [comment]
Thanks for having checked @yasirrose !

**Comment by Nono-m0le** [comment]
@tassoevan maybe you could reopen this?

**Comment by Nono-m0le** [comment]
I'm on 3.8.1 and quote still doesn't work.
@damian-centrone can you please re-open this ticket ?

**Comment by georgschoelly** [comment]
We also have this issue with 3.9.7. It might be because it's an old installation that was upgraded from version to version.

I debugged a bit and it looks like it has something to do with with the usernames. When looking at it in a browser, I can see that the quote is a URL:

https://rocket.example.net:123456/direct/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?msg=yyyyyyy

When I open this URL manually, the following error is displayed on the screen:

![No user with username "random looking string" was found!](https://user-images.githubusercontent.com/1846232/107199379-a077a900-69f6-11eb-9398-f2ebb63dd709.png)

    

(but interestingly, the correct chat opens)

The server throws an exception when browsing to this page which is shown in the logs:

> Exception while invoking method createDirectMessage Error: Invalid user [error-invalid-user]  
>       at server/methods/createDirectMessage.js:44:11

https://github.com/RocketChat/Rocket.Chat/blob/f753e7a127bd77049a4057989f2d1f8ba501a3c6/server/methods/createDirectMessage.js#L44

This is due to `Users.findOneByUsernameIgnoringCase(username)` failing to find a user, which is a bit weird given that the URL works if I leave out the `&msg=yyyyyyyyyyyyyy` part, i.e.

https://rocket.example.net:123456/direct/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I believe it might have something to do with the changes to multi-user direct messages: https://github.com/RocketChat/Rocket.Chat/pull/9106

**Comment by yasirrose** [comment]
@georgschoelly In 3.11.0, this issue has been fixed. I have to update the site url to correct one to make it work. I am using self signed certificate with internal domain. So i need to update internal domain in site url. 

But yesterday, it was not working for some messages. I wasn't able to quote some messages but it is working for others.

**Comment by georgschoelly** [comment]
@yasirrose Thank you. We will test this once 3.11.0 is available as a snap.

**Comment by georgschoelly** [comment]
The new snap version 3.12.1 did not fix the issue. However, we noticed now that the problem was due to a wrong siteurl. Our app is accessible at https://rocket.example.net:30000 but the `siteurl` variable of snap was set to https://rocket.example.net without the port.

We fixed it by adding a `.env` file in `/var/snap/rocketchat-server/common` as suggested by [the documentation][envfile]

This was easy to fix in the end, but the error messages were completely counter-intuitive.

 [envfile]: https://docs.rocket.chat/guides/administrator-guides/troubleshooting
