### ISSUE TITLE
Outgoing webhook does not process Body of response

### ISSUE THREAD

**Issue by SudoHenk** [RocketChat/Rocket.Chat#1939]
I've added `Content-Type: application/json` as a header, used payload={"text": "jsdkl"} and some variations but they are never actually showing up in the chat.

Yes, the script gets called (I can see it in the database). Btw, there is almost no documentation about what format outgooing webhooks use, I had to use pasteb.in to get an Idea but documentation should be nice.

**Comment by Venomen** [comment]
@SudoHenk Did you forced it to work somehow? Because I have the same problem..

**Comment by SudoHenk** [comment]
I've solved it at the moment by creating a Incoming webhook and post to there instead of outputting the JSON in the response body.

**Comment by rodrigok** [comment]
@SudoHenk which version are you using? You can see the version going to `/api/info`

**Comment by rodrigok** [comment]
Maybe this was fixed via https://github.com/RocketChat/Rocket.Chat/pull/1894?ts=2

**Comment by Morgul** [comment]
I reported the exact same issue to @sampaiodiego in the dev channel the over day. I'm running a version with that fix. It still doesn't generate a response message.

**/api/info**

```
{
  "version": "0.13.0",
  "compile": {
    "date": "2016-01-15T23:06:45.444Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 4961341440,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "3009",
    "branch": "develop",
    "tag": ""
  },
  "commit": {
    "hash": "e31b6889ae983f78957a5d25661f1604ff98b028",
    "date": "Fri Jan 15 20:42:29 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1933 from RocketChat/hotfix/#1923"
  },
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}
```

Regarding documentation, @SudoHenk, it's supposed to follow the same documentation as Slack. It would be nice if that were notated somewhere, but just use [slack's docs](https://api.slack.com/outgoing-webhooks) for now.

**Comment by rodrigok** [comment]
@Morgul any error logs? Your service is replying with content type?

**Comment by Morgul** [comment]
@rodrigok No errors in the logs, and the service is responding with the correct content type. (Verified with [Postman](https://www.getpostman.com/))

**Comment by Morgul** [comment]
In fact, these are the headers returned:

```
Connection → keep-alive
Content-Length → 118
Content-Type → application/json; charset=utf-8
Date → Mon, 18 Jan 2016 20:16:15 GMT
ETag → W/"76-HiV9W+OSTSk8sb1kghWI7A"
Server → nginx/1.8.0
X-Powered-By → Express
```

**Comment by rodrigok** [comment]
@Morgul maybe can I test your service? If yes send me the hook details via PM at demo.rocket.chat.

**Comment by Morgul** [comment]
@rodrigok Sure.

**Comment by SudoHenk** [comment]
@Morgul @rodrigok Thanks for the fix! About the docs, I looked into that, but the slack docs are confusing, they state the following: "When a chat message is received that matches the conditions, a POST will be sent to all of the URLs defined like so: ... ". I assumed the POST sent were all seperate POST vars and not in a JSON body.

**Comment by Morgul** [comment]
@SudoHenk No problem. Really thank @rodrigok; I just gave him a json endpoint to test with.

I do agree slack's documentation is rather confusing on that point; I still don't know what Slack does. But Rocket.Chat is json (as I would expect), and that was reasonably painless to verify.

It's still a little awkward developing outgoing Webhooks at the moment; I'd recommend a local Rocket.Chat instance in a VM or Docker that you use for testing while you develop.
