### ISSUE TITLE
Blank screen on private chat

### ISSUE THREAD

**Issue by narayanansampath** [RocketChat/Rocket.Chat#19417]
### Description:

only group chats are working, private chat shows blank screen and when sending messages in private chat,it's greyed out.
### Steps to reproduce:

1. 
Rocket chat desktop app 

2. 
any private chat

3. 

### Expected behavior:

Show chat with all messages.

### Actual behavior:
Blank screen with no messages.

![bug report ](https://user-images.githubusercontent.com/19869271/97739033-9ff57b00-1ab5-11eb-9df1-ddf837818a45.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  1.17.0
- Operating System: 
- Deployment Method:  
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 3.0.5
- Operating System: MacOS Catalina 10.15.7

### Relevant logs:

[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 298"  data: no] FaviconLoader.jsm:298:24
    onStopRequest resource:///modules/FaviconLoader.jsm:298
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674

**Comment by stleitner** [comment]
We have the same issue:

Rocket.Chat
Version	3.6.2
Apps Engine Version	1.17.0
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.15.0-122-generic
Node Version	v12.16.1
Mongo Version	3.6.14

Client:
Mac App Store Version 3.0.3

**Comment by damian-centrone** [comment]
This is already fixed. Tested on 3.8.0

**Comment by narayanansampath** [comment]
> This is already fixed. Tested on 3.8.0

Do you mean 3.7.0? I do not see 3.8.0, the latest release was 3 days ago but I still have the same issue.

**Comment by narayanansampath** [comment]
This issue should not be closed, I still have this issue.

**Comment by damian-centrone** [comment]
It solved on the next version, 3.8.0. It will be available in a few days

**Comment by Hanoos** [comment]
we are running 3.8.1 and still see the same issue.

**Comment by CrestApps** [comment]
I am having the same exact problem with 3.14.2! @narayanansampath

**Comment by banoleb** [comment]
I am having the same exact problem with 3.14.4

**Comment by CrestApps** [comment]
@banoleb I isolated the problem to the moderator role. It’s most likely that there is something wrong with the moderator role. When any role chats with a moderator, this problem happens. Try changing the role and see if that fixes this issue on your end.

**Comment by CrestApps** [comment]
@damian-centrone this issue should get re-opened. Please read my previous comment about the moderator role which is the cause of this problem. This is still a problem even in version 3.16.4

**Comment by glebPo** [comment]
Same problem on 3.14.5. Please help to resolve this issue

**Comment by CrestApps** [comment]
@glebPo are you able to confirm that this issue happen only when a user with the role “moderator” is involved in the chat? And when no “moderator” is involved this does not happen?

**Comment by glebPo** [comment]
@CrestApps  
No its user without any role, also it reproduces in direct chats
