### ISSUE TITLE
Name does not change correctly  in sidebar or topbar

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#19728]
### Description:
If someone changes their name (not their "@" username, rather just name), it will not update for certain users on the top panel, or on the side panel. For example "Anon" changes his name to "Anonymous", but for the other user it still says "Anon" on the side panel and top bar. But in the main chat, the name will display correctly. This happens on mobile, desktop client, and browser version. I have attempted to log in to other users accounts on the browser version, where the name displays incorrectly for me too. Logging in and out or refreshing does not fix it.

### Steps to reproduce:

1. Have other person change their username
2. Check top bar/side panel
![Clipboard - December 1, 2020 7 10 PM](https://user-images.githubusercontent.com/42281789/100780738-61cbde00-340a-11eb-80d5-65aa902a3052.png)
![Clipboard - December 1, 2020 7 21 PM](https://user-images.githubusercontent.com/42281789/100780815-7f994300-340a-11eb-9b5b-840c090f6a6b.png)

### Expected behavior:

Username correctly refreshes to the new one for all users, in all locations.

### Actual behavior:

Username remains the same on the side and top panel:

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Operating System: Ubuntu
- Deployment Method: docker

- Number of Running Instances: 1
- MongoDB Version: v3.6.3

### Client Setup Information

- Desktop App or Browser Version: 3.0.7, **AND** in browser
- Operating System: Windows 10 and Fedora

**Comment by H4x1** [comment]
This is an issue on our server too, which is on the same version.

**Comment by andres-mauricio** [comment]
Hello Folks!

One quick check here, do you display the "real name" or the "username" on the RC instance?
I ask because I noticed that before changing the "name" both fields have the same info at least in the specified case here. 
I was able to replicate the behavior you experience because by default RC does not display the "name" field, but the "username" field instead. 

to fix this, go to Administration>Layout>User Interface, and the select "use real name" 

This way any changes a user makes to their "name" field, will be reflected. 

Try this out and let me know in case you still experience some issues and we can take a look.

**Comment by mmgoilf** [comment]
> 
> 
> Hello Folks!
> 
> One quick check here, do you display the "real name" or the "username" on the RC instance?
> I ask because I noticed that before changing the "name" both fields have the same info at least in the specified case here.
> I was able to replicate the behavior you experience because by default RC does not display the "name" field, but the "username" field instead.
> 
> to fix this, go to Administration>Layout>User Interface, and the select "use real name"
> 
> This way any changes a user makes to their "name" field, will be reflected.
> 
> Try this out and let me know in case you still experience some issues and we can take a look.


Real name is selected:
![Clipboard - December 19, 2020 9_38 PM](https://user-images.githubusercontent.com/42281789/102699134-d6907c00-4242-11eb-9ea3-4d7449a6ec69.png)

**Comment by MJPGPleasant** [comment]
We have the same issue as well. We Display "Real Name". If you have any existing conversations under the old name, they will update momentarily in the UI, but on log out / log in / refresh cache (?) these conversations will revert to the previous name.  Full name in the "User Info" field displays correctly, as does any chat history. Only the Left Pane and the chat title displays the historical name.

Anyone who opens a net new room after the name change sees the correct information.

**Comment by MJPGPleasant** [comment]
Workaround - If you change the UserID as well (and then if need be change it back after saving) The displayed username properly updates and holds it new value.

**Comment by mmgoilf** [comment]
> 
> 
> Workaround - If you change the UserID as well ~(and then if need be change it back after saving)~ the displayed username properly updates and holds it new value.
> 
> Correction: For OAuth users you cannot change the Username back, otherwise the system will throw the following error:
> 
> ![image](https://user-images.githubusercontent.com/73244744/103028937-f7dcbb00-4515-11eb-8df9-b4a22be6fc68.png)
> 
> Not sure if this is a separate issue.

What do you mean by "userID", the @?

**Comment by MJPGPleasant** [comment]
Yes the "@" name. Sorry for mixing up terminologies above...

To correct above:

"Name" field in RC = What I refer to as "User Name" = What is displayed when "Show Real Name" is enabled
"Username" field in RC = What I refer to as "User ID" = The "@" name and what is displayed when above is disabled.

**Comment by MJPGPleasant** [comment]
It looks like the issue of the real name not being properly updated has been resolved via https://github.com/RocketChat/Rocket.Chat/pull/19834, which is released in https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.0

Test and enjoy :)

**Comment by mmgoilf** [comment]
> 
> 
> It looks like the issue of the real name not being properly updated has been resolved via #19834, which is released in https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.0
> 
> Note that you need to update the name _after_ you applied the update. It does not retroactively fix names.
> 
> Test and enjoy :)

Yes that works, although now there seems to be another bug that changing names takes a very long time to go through and makes the server temporarily disconnect. I will test that more and make a bug report for it.

**Comment by mmgoilf** [comment]
> 
> 
> > It looks like the issue of the real name not being properly updated has been resolved via #19834, which is released in https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.0
> > Note that you need to update the name _after_ you applied the update. It does not retroactively fix names.
> > Test and enjoy :)
> 
> Yes that works, although now there seems to be another bug that changing names takes a very long time to go through and makes the server temporarily disconnect. I will test that more and make a bug report for it.

The issue is actually not fixed. For all other users, changing their name fixes the issue. For me though, my name on the sidebar is still a very old nick I had for other users. Changing my nick does not make it go away. Also here is the new issue: https://github.com/RocketChat/Rocket.Chat/issues/19994

**Comment by mmgoilf** [comment]
> 
> 
> > It looks like the issue of the real name not being properly updated has been resolved via #19834, which is released in https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.0
> > Note that you need to update the name _after_ you applied the update. It does not retroactively fix names.
> > Test and enjoy :)
> 
> Yes that works, although now there seems to be another bug that changing names takes a very long time to go through and makes the server temporarily disconnect. I will test that more and make a bug report for it.
> 
> Edit: here is the bug report: #19994
> 
> All users names successfully changed on the sidebar, but changing my own name took several attempts for the sidebar to update for people.

It took a minute to confirm, but this is still an issue for me, but only for my own username. It went something like this (FYI our usernames on this server are inside jokes):

I had the nick "Internet Shaman" a while ago. Then I changed it to several other nicks. Right now I have the nick "Indigo Cat of Divination". I changed it to "Indigo Cat of Divinations", and then back again to attempt to fix it. No change, still shows "Internet Shaman". Change it to "Indigo Cat". It shows "Indigo Cat" for other people now! Change it back to "Indigo Cat of Divination". It shows "Internet Shaman" for other people again.

**Comment by mmgoilf** [comment]
Seems to have been fixed in 3.10.3, will reopen if problem appears again.
