### ISSUE TITLE
Reactions not working sporadically - Too many requests error in logs.

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat#20518]
### Description:

At every other attempt, users can't set reactions - the click on an emoji doesn't work (sometimes the counter increases for a split second but then goes back). I checked the logs and there are multiple instances of this error:

Exception while invoking method setReaction Error: Error, too many requests. Please slow down. You must wait 2 seconds before trying again. [too-many-requests]     at Object.post (app/api/server/v1/misc.js:255:11)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

### Steps to reproduce:

1. Try to add a reaction to a message, by clicking on a pre-existing emoji
(only happens every other time, not always, so maybe try repeatedly)

### Expected behavior:

Emoji counter increases

### Actual behavior:

Emoji counter does not increase

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: -
- MongoDB Version: -

### Client Setup Information

- Desktop App or Browser Version: any
- Operating System: any

### Additional context

It seems the rate limiter is restricting the action. Could that mean that there are too many (unnecessary) requests happening in the background? This worked fine for many months, only since this week (maybe since I upgraded to 3.10.4) is not working properly any more

### Relevant logs:

see logs posted above

**Comment by aKn1ghtOut** [comment]
Please check with latest release and develop branch. Was fixed in #20159

**Comment by pbenkoe** [comment]
Thank you. I just now updated and checked with 3.10.5, and it is still happening. That's the latest release though, yes?

**Comment by aKn1ghtOut** [comment]
Appears the merge first appears in 3.11.0(release candidate).
You can check https://github.com/RocketChat/Rocket.Chat/releases/tag/3.11.0-rc.5 in a non-production environment.

**Comment by pbenkoe** [comment]
Gotcha, thank you, I'll wait for the final release of 3.11 👍
