### ISSUE TITLE
OTR Not working without error message in Console

### ISSUE THREAD

**Issue by Hyabusa1990** [RocketChat/Rocket.Chat#20684]
### Description:

If i will start OTR on Rocket Chat i will get an Timeout. I can't see Errors in the Debug Console. On The Other side of the Direkt Message there will not see an Invention of the OTR Message.

### Steps to reproduce:

1. Go to the Chat I will Start the OTR
2. Click on OTR
3. Start OTR
4. Wait ~10 secounds
5. get a Timeout Message

### Expected behavior:

Start OTR

### Actual behavior:

I get an Timeout and the other didn't see anithing. (Both directions) And after the Timeout on the OTR Tab the 3 dots won't go away so i have to reload the Browser/Client to resend an OTR request.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.10.5
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Client and Microsoft Edge (Chromium)
- Operating System: Windows 10 

### Additional context

-

### Relevant logs:

-

**Comment by yash-rajpal** [comment]
This was fixed in latest 3.11.1 release.

**Comment by Hyabusa1990** [comment]
Thanks for the Info!
Could you get me an Info about the Release Date of the Snap Package of this Version?

Thanks!

**Comment by himpierre** [comment]
> This was fixed in latest 3.11.1 release.

@yash-rajpal I'm still having the OTR timeout issue with 3.11.1. Is this supposed to work?

cheers!

**Comment by yash-rajpal** [comment]
Yes, it is supposed to work. In my testing it worked like a charm, thanks to @ggazzo .

Just so you know when you request an OTR, other user has to accept within 10 seconds otherwise it would return Timeout.

Make sure other user accepts the OTR request, then it should work.

**Comment by himpierre** [comment]
@yash-rajpal Ok, on my setup I still have the timeout error. The user gets no confirmation dialog. Here my setup.

rocketchat 3.11.1
docker via k8s
browser firefox latest

Nothing in the logs.

**Comment by TomaszDom** [comment]
Same here using 3.11.1, manual install, OTR is broken exactly as described.
