### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by crashbr** [RocketChat/Rocket.Chat#20694]
When click in download button, the file opens in the rocket.chat instead download it, and it's not possible to return to the list of channels and chats. It just returns forcing refresh or restarting rocket.chat.

**Comment by yash-rajpal** [comment]
This was fixed in latest release.

**Comment by crashbr** [comment]
I have updated and still have the same problem.


Att,

Erik Silva Sobral
