### ISSUE TITLE
Myself and several users report seeing "Encrypted Message"

### ISSUE THREAD

**Issue by robpedersendev** [RocketChat/Rocket.Chat#20884]
### Description:

When a user is fully logged into the mobile app and has already entered the Encryption key when prompted they have access to rooms that are encrypted and almost all messages that are within that room. Some messages are showing as "Encrypted Message" See screenshot below 

If you tap the key icon to the right, you see the message below

When the user gets logged in to the web browser they see a large string of garbled text. 

To be clear they used to have no problem receiving chats in this channel. 

Some users have this issue off and on, this current user can not see any message that comes in. 

### Steps to reproduce:

1. Log in to app as the user
2. Access room X
3. Attempt to read chats from any user in the past 24 hours
4. See "Encrypted Message" displayed or if on the website, see "urinvpqiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q3095jv-q98hvqunvq[-9u78nvq847bvnq[ or likewise text where a message would be

### Expected behavior:

Log in to app as the user
2. Access room X
3. Attempt to read chats from any user in the past 24 hours
4. Be able to actually read the chats

### Actual behavior:

1. Log in to app as the user
2. Access room X
3. Attempt to read chats from any user in the past 24 hours
4. See "Encrypted Message" displayed or if on the website, see "urinvpqiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q30qiuvnqpuvhqpivh[q3q3095jv-q98hvqunvq[-9u78nvq847bvnq[ or likewise text where a message would be
![image](https://user-images.githubusercontent.com/40696979/108941138-c9f91d00-7611-11eb-87c1-5b13fb966a9d.png)
![image](https://user-images.githubusercontent.com/40696979/108941354-2f4d0e00-7612-11eb-86ea-630878116a18.png)

5. When you click on the key you get this message
![image](https://user-images.githubusercontent.com/40696979/108941130-c6fe2c80-7611-11eb-9ad1-9f1df3258145.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 
- Deployment Method: Cloudron
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19 / unknown (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Mobile App, 
- Operating System: iOS 14.4

### Additional context

We have tried clearing users local server cache, tried logging out and logging back in all useless.
Yes, this was all done while another user was online.

**Comment by JustinTimperio** [comment]
I can also confirm this bug. This has made our Rocket Chat unuseable

**Comment by JustinTimperio** [comment]
I have found the following log
```
 Exception while invoking method e2e.setRoomKeyID Error: E2E Key ID already exists [error-room-e2e-key-already-exists]     at MethodInvocation.e2e.setRoomKeyID (app/e2e/server/methods/setRoomKeyID.js:18:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
 ```

**Comment by robpedersendev** [comment]
I now have this affecting myself and another user in a private message.

**Comment by JustinTimperio** [comment]
@robpedersendev This issues has been fixed for us by the latest release

**Comment by robpedersendev** [comment]
I still have this occurring, Mobile app on iOS is 4.14.1, ios V 14.4

**Comment by robpedersendev** [comment]
We are using Rocket.Chat 3.12.1

**Comment by robpedersendev** [comment]
Any other advice or ideas here?

**Comment by Brendan-McCoy** [comment]
Having a similar issue. The messages only decrypt for users on the mobile app, but the desktop app or webapp, even after inputting the key on the prompt, are not decrypting messages.

**Comment by ggazzo** [comment]
these problems should be fixed in versions > 3.12.0.

to be honest, i'm not sure how mobile works behind the scenes (but it should work the same as the web). But please confirm me with the latest versions, all the code has been refactored so some old issues are no longer valid.

Pay attention: if you are resetting your key, you need someone else in the room to log in to receive a new key. If both resets their passwords, it will be impossible to decrypt the room. It is a limitation of the protocol and we are studying new ways to do this.

please let me know if the problem is still there. maybe lets talk more and try to reproduce local.
