### ISSUE TITLE
[3.13.0] Presence state error

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#20957]
### Description:

There is an instability in the state of presence of the user. In some cases it is not updated correctly or does not maintain a relationship in the indicators.

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 4.0.22 / wiredTiger (oplog Habilitado)
- NodeJS Version: v12.18.4
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

![image](https://user-images.githubusercontent.com/35962168/109592527-65403580-7add-11eb-985e-e71ea13eb28e.png)
![image](https://user-images.githubusercontent.com/35962168/109592982-2fe81780-7ade-11eb-89b9-677a9875083f.png)

**Comment by ankar84** [comment]
I saw that a couple times on open server on previous versions, but I thought it was fixed in recent versions.

**Comment by teak421** [comment]
It is not fixed.  It seems to happen on the client and not in the web version.  My end-users are wanting to toss all sorts of vegetables at me...So, I hope this gets resolved quickly.

**Comment by teak421** [comment]
Not fixed. See attached video.

https://user-images.githubusercontent.com/13898029/109706347-b0922c80-7b4d-11eb-91fe-53e7aa4245c4.mp4

**Comment by aleadco** [comment]
@ankar84 

![20210302_200000.jpg](https://user-images.githubusercontent.com/35962168/109736361-2fa95400-7b92-11eb-8a60-6c67721f5887.jpg)

**Comment by ankar84** [comment]
Could be related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1812
@aleadco @teak421 can you check that bug in Web version?

**Comment by ankar84** [comment]
open server have that bug too 
![image](https://user-images.githubusercontent.com/4023037/109805899-10173780-7c35-11eb-8015-bcc0d35322ba.png)
@ggazzo please take a look

**Comment by aleadco** [comment]
@ankar84 The two images shown at the beginning are in the web version

**Comment by teak421** [comment]
@ankar84 That looks like the bug over on the electron client.  Come to think of it, I don't remember it happening inside of the web version.  I will be on the look out for it.

**Comment by grthr** [comment]
still an issue in 3.12.1

**Comment by ankar84** [comment]
> still an issue in 3.12.1

Yeap
![image](https://user-images.githubusercontent.com/4023037/111751857-07b23400-88a6-11eb-95bc-e5b9ec79c5b2.png)

**Comment by mmgoilf** [comment]
Still an issue in 3.12.3

**Comment by foss-** [comment]
This has still not been addressed in 3.13.0 and Rocket.Chat team not responding for over a month makes me wonder if they are even aware of this regression.

**Comment by grthr** [comment]
> Status in sidebar is actual status.
In my case the status in the sidebar is not updated

**Comment by teak421** [comment]
This is happening in our environment as well.

![image](https://user-images.githubusercontent.com/13898029/114104072-0fe70900-987f-11eb-8826-9dcd3770eaeb.png)

**Comment by aleadco** [comment]
@ggazzo and @diegolmello Hi, we are concerned that they are not aware of this because we do not see attention on this error after 4 updates.

**Comment by ggazzo** [comment]
hey @aleadco I was aware, and thanks for you concerning. We had only one minor release since you opened the issue. And usually we dont prevent patch releases from being published because there are different issues waiting, usually we try to release soon as possible, thats why you noticed some patch releases without a proper fix for your problem.

Btw: the fix is coming! just waiting for review ;) 


thank you all for the information.
