### ISSUE TITLE
Rocket.Chat fails to deliver messages when MongoDB switches the primary

### ISSUE THREAD

**Issue by qchn** [RocketChat/Rocket.Chat#21013]
### Description:

Whenever the underlying MongoDB switches it's primary server, Rocket.Chat instantly fails to deliver messages, sent messages will be greyed out until the MongoDB middleware servers will get restarted. In the past, this wasn't a thing.
Steps to reproduce:

### Steps to reproduce:
1.    reboot mongodb primary
2.    After that, when you send a message to someone via Rocket.Chat, the message is greyed out and won't get delivered Notifications still get delivered
3.   after restarting the middleware server, everything is going back to normal

### Expected behavior:

Rocket.chat middleware servers automatically find out who is the new primary server

### Actual behavior:

Rocket.Chat fails to deliver messages after MongoDB primary switch.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.2
- Operating System: Debian Linux
- Deployment Method: tar
- Number of Running Instances: 8
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.18

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Windows, Linux, MacOS

### Additional context

-

### Relevant logs:

-

**Comment by anyway111** [comment]
i have same issues

**Comment by fdellwing** [comment]
You have some important info missing from your Server Setup block. How many instances of RC and Mongo are you running?

**Comment by qchn** [comment]
>How many instances of RC and Mongo are you running?

Sorry, copy-paste misfortune. 
I have 8 middleware servers and 5 MongoDB nodes.

Best
Robert

**Comment by qchn** [comment]
Hi @ggazzo, @geekgonecrazy, @engelgabriel, @rodrigok

can someone help me with this, please?

Best
Robert

**Comment by qchn** [comment]
Hi @ggazzo, @geekgonecrazy, @engelgabriel, @rodrigok

I can reproduce this behaviour with version **3.13.3**

Can someone help me with this, please? This is a major impact to our setup.

Best
Robert

**Comment by geekgonecrazy** [comment]
Make sure your connection strings have ?replicaSet=rs01 replace rs01 with your replicaset name.

**Comment by cschockaert** [comment]
hello @rodrigok could that be related to the changestream usage?

**Comment by cschockaert** [comment]
FYI tested with IGNORE_CHANGE_STREAM : true
it's doesnt work after a primary re-election.

Then tested with USE_NATIVE_OPLOG (meteor oplog) and... it seems that its working fine after a re election messages are not grayed.

So it appears that changestream implementation and custom oplog implementation are not taking in count a topology change in the mongodb replicatset (master re election for example).

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/29195

**Comment by IvanOtkidach** [comment]
Hello, @sampaiodiego ! 
I have a HomeLab setup of Rocket.Chat 6.7.3 with MongoDB ReplicaSet (Primary, Secondary, Arbiter) with WriteConcern = 1.
It seems that problem is not solved, after re-election, if I use `IGNORE_CHANGE_STREAM=true`, messages are delivered only after refreshing of a page. Restart of RC Server helps.

After some tests, I can assume, that if you turn off the database that was primary at the time of Rocket.Chat deployment, then messages will only arrive after the page is reloaded.
At the same time, when restoring the original primary, you also need to reboot Rocket.Chat

With `USE_NATIVE_OPLOG=true` all works file

**Comment by sampaiodiego** [comment]
hi @IvanOtkidach .. what happens if you don't set either `IGNORE_CHANGE_STREAM` and `USE_NATIVE_OPLOG` ? this will be the rocket.chat's default configuration, it should work in that case.

**Comment by IvanOtkidach** [comment]
If I don't set either `IGNORE_CHANGE_STREAM` and `USE_NATIVE_OPLOG` in my setup (with WriteConcern = 1), when the Primary or Secondary MongoDB node is turned off, messages are sent/received only after the page is reloaded

**Comment by IvanOtkidach** [comment]
@sampaiodiego Hello! Do you have any news about this topic? Are you sure it works fine without `IGNORE_CHANGE_STREAM` and `USE_NATIVE_OPLOG` ?
@nmagedman @cschockaert @qchn , Hello! Do you still have this problem (if you don't set either `IGNORE_CHANGE_STREAM` and `USE_NATIVE_OPLOG)?`

As I have read in https://github.com/RocketChat/Rocket.Chat/pull/27281, `USE_NATIVE_OPLOG=true` can cause performance issues since v 5.0.0.

**Comment by cschockaert** [comment]
Hello 

we dont use anymore IGNORE_CHANGE_STREAM = true and/or USE_NATIVE_OPLOG = true since we migrated to a self managed gke mongodb db (bitnami helm chart)
no problem now and we pay far more less $ / month.

self >> atlas

**Comment by sampaiodiego** [comment]
> @sampaiodiego Hello! Do you have any news about this topic? Are you sure it works fine without IGNORE_CHANGE_STREAM and USE_NATIVE_OPLOG ?

@IvanOtkidach it is totally fine.. we use all default config in production (without any of those env vars) and that works fine.. it might be something related to our MongoDB deployment, please see my message in this other issue https://github.com/RocketChat/Rocket.Chat/issues/19905#issuecomment-1340882554
