### ISSUE TITLE
users.list REST API does not allow count=0 parameter to fetch all results

### ISSUE THREAD

**Issue by mawe42** [RocketChat/Rocket.Chat#22082]
### Description:

The Rocket.Chat REST API allows to use a `count=0` parameter if `API_Allow_Infinite_Count` is enabled. This works on API endpoints like `groups.listAll`, for example. But the `users.list` endpoint throws an error: "400 - the limit must be positive".

I think this is due to the recent changes to the `users.list` endpoint, specifically the change to use `$limit` aggregations in the MongoDB queries. Those `$limit` queries require the value to be a "positive integer", which I assume excludes 0:
https://docs.mongodb.com/manual/reference/operator/aggregation/limit/

### Steps to reproduce:

1. Enable `API_Allow_Infinite_Count` in the REST settings
2. Make a REST API request to `http://rc.host/api/v1/groups.listAll?count=0` => works
3. Make a REST API request to `http://rc.host/api/v1/users.list?count=0` => throws an error

### Expected behavior:

I would expect `users.list` (and all other API endpoints) to honour the `count=0` parameter if `API_Allow_Infinite_Count` is enabled.

### Actual behavior:

`users.list` throws error: "400 - the limit must be positive"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Linux
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.16

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Is it possible you could give it a quick test on 3.15 RC to make sure it is still there??

**Comment by mawe42** [comment]
Will do next week, but my guess is that it is still there. Even on current master the `user.list` endpoint [takes the `offset` and `count` parameters from `getPaginationItems()`](https://github.com/RocketChat/Rocket.Chat/blob/512020795a900496165b6af6f78ddc261b960b1e/app/api/server/v1/users.js#L231) and passes them [directly to the `$limit` and `$skip` MongoDB aggregations](https://github.com/RocketChat/Rocket.Chat/blob/512020795a900496165b6af6f78ddc261b960b1e/app/api/server/v1/users.js#L264).

**Comment by mawe42** [comment]
Just to clarify: with "3.15 RC" you mean current master, correct? Or does "RC" stand for release-candidate?

**Comment by SGU-1** [comment]
I have tested the bug with the current development branch. The problem persists:

```
2021-05-27 09:08:44,950 DEBUG: http://localhost:3000 "GET /api/v1/users.list?count=0 HTTP/1.1" 400 None
2021-05-27 09:08:44,996 ERROR: Error during GET http://localhost:3000/api/v1/users.list: 400 - the limit must be positive
Error during GET http://localhost:3000/api/v1/users.list: 400 - the limit must be positive
```

Testet with:

**Version:** 3.15.0-develop

**Node:** v12.22.1

**Commit Details:**
HEAD: (5a6475eb4), Zweig: develop

**Comment by sternenseemann** [comment]
> Hi and thanks for reporting this.
> 
> Is it possible you could give it a quick test on 3.15 RC to make sure it is still there??

still the case in Rocket.Chat 3.15 release

**Comment by Shailesh351** [comment]
The fix is available in https://github.com/RocketChat/Rocket.Chat/pull/22555 😄

**Comment by alueers118** [comment]
The problem still persists.

**Comment by Schillilex** [comment]
Problem still persists.
`"error": "the limit must be positive"`
Version 3.17.0
