### ISSUE TITLE
thumbnail of uploaded PNG files is not shown in the channel and picture doesn't load on click

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#2243]
When uploading a PNG to a channel it shows no thumbnail of the content. Furthermore when clicking on it, it shows a grey loading circle forever and ever
![unbenannt](https://cloud.githubusercontent.com/assets/5287181/13077436/09fc3914-d4b9-11e5-839c-f424d2ea44d3.JPG)

**Comment by engelgabriel** [comment]
Is this still happening?

**Comment by manuelbachl** [comment]
seems to be fixed for now, but now thumbs are really big - at least those from github integrations messages

**Comment by manuelbachl** [comment]
![unbenannt-4](https://cloud.githubusercontent.com/assets/17936331/13893440/a55fa216-ed5e-11e5-8516-a74c8fe7ce3e.png)

**Comment by manuelbachl** [comment]
Issue seems to be back - pulled newest dev - in client the images still dissapear

**Comment by geekgonecrazy** [comment]
@manuelbachl is this in the desktop app?

**Comment by manuelbachl** [comment]
yes on os x

**Comment by geekgonecrazy** [comment]
@manuelbachl I think this is desktop specific.  I get this too @engelgabriel happens frequently on the demo server.  The box shows up where the image is supposed to be.  But the image doesn't actually finish loading.  I'm thinking some kind of security issue in the desktop app.

**Comment by manuelbachl** [comment]
really weird is the fact, that sometimes the image appears. But (without being able to reprosuce or find out any rule this behaviour follows) then it appears. somtimes immideately, sometimes after a few seconds, sometimes when uploading another image

**Comment by manuelbachl** [comment]
ok strange behaviour. I'm running both instances in the same client - our server and the demo server, both on the same build afaik. in the demo server images are shown

**Comment by engelgabriel** [comment]
Demo is now using S3 for file storage, just for info

**Comment by geekgonecrazy** [comment]
@manuelbachl can you open the dev tools and see if you see any errors come up when the image doesn't show?

**Comment by geekgonecrazy** [comment]
relevent logs:

```
<censored for privacy>/overview.png Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
<censored for privacy>/Clipboard Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
<censored for privacy>/overview.png Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
```

**Comment by sampaiodiego** [comment]
This is probably related to #2545
@finius are you using GridFS as file storage? check at `Administration > File Upload > Storage Type`.

**Comment by engelgabriel** [comment]
This should be fixed on version 0.23.0
Please reopen otherwise.

**Comment by dimti** [comment]
Problem still exists in browser 
![b6e13a0c](https://cloud.githubusercontent.com/assets/582144/24692737/7e29e282-19eb-11e7-8e49-bb5a1e8e8029.png)

Version 0.36.0

**Comment by geekgonecrazy** [comment]
@dimti a lot has changed between 0.36.0 and our current release.  Can you let us know if you see it in the latest release?

**Comment by dimti** [comment]
I updated to 0.52.0
Problem still exists minimum on two separated members in my chat server.
Images not showing, and in addition, member unable to upload any files.
![c68ecd2b](https://cloud.githubusercontent.com/assets/582144/25112749/e4f830ee-23fb-11e7-827a-e70856e68b7e.jpg)

**Comment by guillaumegarcia13** [comment]
Hi,

**OS** : Windows 10
**Client** : Chrome 65.0.3325.181, Chrome Androïd (One Plus 3T), Win10 App
**Storage** : GridFS

Got it regularly (on a weekly-basis)
![image](https://user-images.githubusercontent.com/2786038/38755319-9de163b6-3f65-11e8-93b2-454e479eb3e9.png)
When it occurs, it affects all of my clients (desktop, Windows 10 app, mobile).

In my case, seems to only occur to the uploader of the picture, though.
Got this error in console (unsure whether this is related)
```
Uncaught TypeError: Cannot set property 'input' of undefined
    at Object.focus .js-input-message (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:245)
    at 53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79
    at Function.e._withTemplateInstanceFunc (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79)
    at f.View.<anonymous> (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79)
    at 53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79
    at Object.f._withCurrentView (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79)
    at f._DOMRange.<anonymous> (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79)
    at HTMLTextAreaElement.<anonymous> (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:79)
    at HTMLElement.dispatch (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:11)
    at HTMLElement.h.handle (53456bb8cd8916d1497d74fe0612b7b098ecab1a.js?meteor_js_resource=true:11)
```
