### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by homberger** [RocketChat/Rocket.Chat#2431]
_From @homberger on March 4, 2016 20:21_

I don't receive any push notifications of Rocket.Chat on my iPhone anymore.
Since I applied the "fix" (https://github.com/RocketChat/Rocket.Chat/issues/2399 : setting a word in the "highlight" field) to not receive a push notification for every message in any channel even from myself, I don't receive *any* push notifications - even when I am mentioned.
Look at attached screenshot to see my profile preferences. Setting a word in the highlight field changes nothing.

<img width="655" alt="screen shot 2016-03-04 at 21 18 07" src="https://cloud.githubusercontent.com/assets/681335/13539126/c74dddfe-e24e-11e5-9908-8b9a4520737e.png">

On the next screenshot you can see our push notification preferences.

<img width="647" alt="screen shot 2016-03-04 at 21 20 58" src="https://cloud.githubusercontent.com/assets/681335/13539189/167dc6d2-e24f-11e5-91be-2c137f3ceaa0.png">

We are using Rocket.Chat 0.20.0 on server side. On my iPhone is the latest release of the iOS cordova app.

_Copied from original issue: RocketChat/Rocket.Chat.Cordova#81_

**Comment by homberger** [comment]
I deleted and reinstalled the app on my iPhone. When asked for permission to send push notifications I agreed (like before). Still no push notifications.
How can I debug this?

**Comment by homberger** [comment]
_From @rodrigok on March 5, 2016 11:20_

Hi @homberger, this problem is not related with the mobile app it self.

Can you open this issue in this repository https://github.com/RocketChat/Rocket.Chat?

**Comment by rodrigok** [comment]
@marceloschmidt you did this fix, can you take a look here?

**Comment by homberger** [comment]
@lochiiconnectivity and @royalaid: are you affected by this too?

**Comment by royalaid** [comment]
I am not. I am guessing the test push doesn't work?

**Comment by homberger** [comment]
> I am guessing the test push doesn't work?
It says "Success - Pushed to 2 devices". But it is lying. No device I know received anything. :(

**Comment by graywolf336** [comment]
What version of Rocket.Chat are you on?

**Comment by homberger** [comment]
We are using Rocket.Chat 0.20.0 on server side. On my iPhone is the latest release of the iOS cordova app.

**Comment by engelgabriel** [comment]
It is fixed now? We had some issues with our push gateway.

**Comment by homberger** [comment]
>It is fixed now? We had some issues with our push gateway.
No, the problem persists. All users of our instance seem to be affected.
Do you have an idea how to debug this?

**Comment by engelgabriel** [comment]
Can you turn the push debug on, click the send test button and see the View Logs section on the admin panel?

**Comment by homberger** [comment]
This is the result:
`Push: Send message "@homberger" via query { userId: 'GuctpCA5nhMtdQHms' }
send to token { apn: '85edcfa04efc690e58b4582951665d963dab4dd043c6fa84dfc1f782476a1348' }
send to token { apn: '4f7ce6eff47bb8b2eccb3e373dd1cea4193d117eef31dd34503f1037d2a5cec7' }`
![screen shot 2016-03-11 at 16 41 38](https://cloud.githubusercontent.com/assets/681335/13707100/57d25c34-e7a8-11e5-9278-192903ee284a.png)

But I still didn't receive a notification.

**Comment by engelgabriel** [comment]
We have to do a test together, as I have to monitor our gateway logs to check if we are receiving your push notification here. Lets schedule that?

**Comment by homberger** [comment]
yeah, no problem :)
DM me in #dev or #support on https://demo.rocket.chat/ please

**Comment by mide** [comment]
I've also noticed a recent lack of push notifications. I haven't done any of the tests, but I will when I get a chance.

**Comment by homberger** [comment]
We upgraded to Rocket.Chat 0.22.0 and the problem persists :(

**Comment by rodrigok** [comment]
The problem was with a wrong `Push Gateway` URL, was `https://rocket.chat/` and should be `https://rocket.chat`

**Comment by mide** [comment]
My push notifications are working again. My `Push Gateway` URL is `https://rocket.chat`.

**Comment by Syirrus** [comment]
So, are push notification enabled (do they work) in Cordova builds of Rocket.Chat for Android and for iOS?

**Comment by mide** [comment]
I have observed working Rocket.Chat notifications on both [Android](https://play.google.com/store/apps/details?id=com.konecty.rocket.chat&hl=en) and [iOS](https://itunes.apple.com/us/app/rocket.chat/id1028869439?mt=8). I can not speak for @homberger, but my notifications are now working.

**Comment by Syirrus** [comment]
You have observed push notification work on "cordova" builds of Rocket.Chat (not native)?

Is there are guide that you could point me to? I would be most appreciative.

**Comment by homberger** [comment]
We are using the official apps from the Google Playstore and Apple Appstore and push notifications are working very well (again). These are "cordova" builds as far as i know.

**Comment by Syirrus** [comment]
I see, I've successfully compiled cordova version of Android and iOS. I cannot seem to get the push notifications to work. When I login to rocketChat via the my compiled android app, and do a test push, it says that it was successfully sent to my device, yet I don't receive anything. 

Before I compiled the cordova build I was sure to insert my Google projectID here:

echo 'window.ANDROID_SENDER_ID = "<My Google Project ID>";'

Has anyone out there compiled their own version of the Cordova  Rocket.Chat and gotten it to work?

**Comment by graywolf336** [comment]
@Syirrus You have to use the one already compiled and from the respective stores. If you compile it yourself, you're going to have to go through the entire process of setting up Push Notifications for each respective store.

**Comment by Syirrus** [comment]
@graywolf336 I understand.  
Is there a guide you could point me to in order to do this. I have integrated push notification aggregators before into apps, so I do have some experience, but I have never setup my own push notification gateway like (https://rocket.chat) I'm assuming.

**Comment by graywolf336** [comment]
@Syirrus I don't believe an actual push notification gateway is required, you just need to configure your Rocket.Chat instance with the proper settings under the push notifications settings. But as far as a guide, I don't know if we have one setup for it.

**Comment by Syirrus** [comment]
@graywolf336 hmmmm, I will continue to investigate. What is the gateway field -> under the push section of Rocket.Chat?  By default it's https://rocket.chat 
rocket.chat is not a GCM server too is it? I'm just trying to learn how everything is put together. :)

**Comment by rodrigok** [comment]
@Schniz The gateway fields is to use your rocket chat server with our mobile apps. If you are compiling your apps you should disable the gateway and fill the certificates.

**Comment by Syirrus** [comment]
@rodrigok So in order to get push notification to work with my own compiled Cordova apps, I need to remove the rocket chat server gateway and fill out the Certificate and Keys section with my own certs. Beyond that, I need to make sure my project Google ID is used in my cordova app compile and I should be good to go?  I don't need to set up my own push notification server correct?

**Comment by rodrigok** [comment]
@Syirrus correct

**Comment by lochiiconnectivity** [comment]
@homberger , Using 0.22.0 but with gateway and don't see the problem.

**Comment by skizzors** [comment]
I am having an issue as well not receiving mobile notifications. I tried turning the gateway off, changing the gateway to https://rocket.chat instead of our server address. I am receiving notifications to my mac, but not my phone. When I go to the push settings and test a push, it goes through when I have https://rocket.chat set as gateway and gateway enabled. However I still receive no notifications to my phone aside from the test. Also strange is I am not receiving the test notification on my mac when I test the push.

**Comment by maxlinux2000** [comment]
Hi,

same problem.
I filled the gcm fields with my google api and proj#  and disabled the gateway.
I've build the cordova app and filled correctly the 2 files for push notification.
But no push message is send.
If I press the test push button, RC tell me that the message was send successfully but in my phone no push message arrive.

I'm frustrating because this summer rocketchat push messages was working, and now... :(

**Comment by lexarvn** [comment]
I'm having basically the same issue as @skizzors. Have push enabled, gateway enable, gateway set to `https://gateway.rocket.chat`, and when I push send a test push notification from my desktop, my mobile gets a notification. But if another user DMs me or I get mentioned in a channel, no notification. I even set the mobile push notification preference for the #general channel to `All messages`, but still don't get anything.

**Comment by zacharyrohrbach** [comment]
I'm having similar issues. I get all private message notifications, but I don't get channel notifications. I don't get private channel messages and open channel messages. I'll be happy to provide any logs necessary!

**Comment by sanjeevghimire** [comment]
I added all teh APN keys in the push section and still the notification to cordova ios app doesn't work? is there anything else i need to do.

**Comment by tekprepper** [comment]
Just want to post the answer for the people who overlook the simple things (like I did) 

**Make sure DNS is resolving on your server.** Everything has been working perfectly for weeks and the only noticeable issue was the push notifications. Can't send a push notification if you can't resolve gateway.rocket.chat ;)

**Comment by alandroid** [comment]
This notifications issue needs to be fixed asap, because it makes the entire project unusable and all your adopters will drop like flies. Starting with me.

**Comment by rodrigok** [comment]
Hi @alandroid 

What's happening? We have no comments here since 1 year ago.
We have no but issues related to notifications as far we know, can you explain your case and add details about your installation like version, OS, installation method, etc?

Thanks
