### ISSUE TITLE
Script field is always error in integrations

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2504]
As show in the below image, eventhough the script field is correct it is showing error in red color and not working the integration. 
![chat error](https://cloud.githubusercontent.com/assets/6078669/13768201/35226dac-ea99-11e5-9feb-2c730c55a2bf.png)

**Comment by bott0r** [comment]
sadly after updating my 2 very easily written scripts stopped working as well, guess i have to invest some time to get them fixed...

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (455/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:55783 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmdj-000ePK-P0
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:55:59 +0100
Date: Tue, 15 Mar 2016 03:55:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458039310;
	bh=hkambq9Y/Hb4asvAq22fQVaINlLd7t5dAyJMBuY9qbI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zdoAEsGvHWXJVgolEDKG+VfakcUS0dlf9sDI3CEhZ3NB/d13pyxZ5iGqZ1zTIy6JW
	 zW52lWeKJV2n+TphMa8fKSPB2iTQhB552XhoLI+LeUUTdZCdy5Df3ZxtQW1EsZFJGL
	 B7yjfCwuItUuSvLZaOmzwmfeqWVjqbQqIOlqCSsQ=

**Comment by sandish2222** [comment]
the same for me.  

i updated from 0.21 to 0.22, and then i saw the error.  Its always error even if i create a new web hook.

**Comment by pavankumarkatakam** [comment]
I didn't understand the @yanndupuy 's message.

**Comment by bott0r** [comment]
I think it means, they have plenty of support tickets open.

**Comment by fabiomontefuscolo** [comment]
I'm getting this error too. I would like to know how to debug this to provide more info, because this error appears but no errors was show on logs.

**Comment by rodrigok** [comment]
@pavankumarkatakam I can't reproduce your error, can you paste your code here?

**Comment by rodrigok** [comment]
@fabiomontefuscolo can you paste your code and a print screen here?

**Comment by fabiomontefuscolo** [comment]
Hi @rodrigok,

I'm using Rocket.Chat on Docker at version 0.22. Also, I used the script for github from Wiki[1]

![Uploading rocketchat-webhook-errors.png…](Red error bar)

[1] - https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by rodrigok** [comment]
@fabiomontefuscolo can you update your docker to latest develop image? This problem was solved.

If you can't, please add a new ENV var to your docker `HOME=/tmp`

**Comment by bighair** [comment]
This is still a problem for me for Outgoing Webhooks (I haven't tried Incoming) using a manually installed instance on CentOS with v0.39.0. I've tried with my own script and with the example GitHub integration script from the Wiki and I always have a blank error underneath the script field.

I've attached some screenshots if they're any use. Interestingly I was testing my integration scripts with the same version of RC installed locally on an Ubuntu VM and didn't have the problem at all.

Any suggestions?
![screen shot 2016-09-15 at 08 19 45](https://cloud.githubusercontent.com/assets/3220072/18541999/6688179e-7b20-11e6-81b9-cb6262df5f53.png)
![screen shot 2016-09-15 at 08 17 03](https://cloud.githubusercontent.com/assets/3220072/18542000/668c5f3e-7b20-11e6-98e0-b1ecb2b7e7d2.png)
