### ISSUE TITLE
Newly created integrations (incoming webhook) do not function

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2524]
Your Rocket.Chat version: develop

Title says it all, in order to reproduce:
create new webhook, send curl, see nothing in log :( 

However, previously created integration function flawlessly!

**Comment by engelgabriel** [comment]
You now have to turn the integration ON, did you do that?

![image](https://cloud.githubusercontent.com/assets/1000217/13879530/a1fcf122-ecf6-11e5-91b7-674e2c458afe.png)

**Comment by bott0r** [comment]
Hey,

that is not the issue. as i mentioned. What I noticed however is that the token for newly generated webhooks is longer than the older versions 

working > A9qSw8LcJaYcuDxQM/rocket.cat/0pBk48K2d1zYWy0IZc8uoi3SWrxc9B8pienv2WVHxAM%3D
notworking >qPZWDnonakynQzaXZ/rocket.cat/IU2n5RKzSG7spM%2Fub7ztJOA4L%2BNIK2dkTIZj0gP7yck%3D

**Comment by rodrigok** [comment]
@bott0r if you decode the tokens as URL you will get the correct length
```
A9qSw8LcJaYcuDxQM/rocket.cat/0pBk48K2d1zYWy0IZc8uoi3SWrxc9B8pienv2WVHxAM=
qPZWDnonakynQzaXZ/rocket.cat/IU2n5RKzSG7spM/ub7ztJOA4L+NIK2dkTIZj0gP7yck=
```

**Comment by engelgabriel** [comment]
@rodrigok can't we generate token that have ONLY hexadecimal characters? This encoding/decoding is always a headache.

**Comment by rodrigok** [comment]
@engelgabriel why is always a headache?

**Comment by engelgabriel** [comment]
Because some systems will decode before submitting the request... there is not advantage on having this point of failure.

**Comment by rodrigok** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/2553

**Comment by engelgabriel** [comment]
@bott0r can you update with the latest form develop and try again?

**Comment by bott0r** [comment]
will do as we speak, ill give an update in 10 mins

**Comment by bott0r** [comment]
works like a charm now! however the layout is funky,
![caplkkkture](https://cloud.githubusercontent.com/assets/17119942/13892282/9f8aa690-ed56-11e5-8758-6b6184e9c2e2.jpg)
 here a picture

**Comment by engelgabriel** [comment]
Can you refresh and to a full screen print? I can really understand what part this is supposed to be. 
Is there anything on the browser console logs?

**Comment by bott0r** [comment]
The console log is empty, full refresh does not fix it here is a bigger picture
![caplkkkture](https://cloud.githubusercontent.com/assets/17119942/13892636/05333d3e-ed59-11e5-97eb-43b8a9e4b7e0.jpg)

**Comment by bott0r** [comment]
Bump

**Comment by engelgabriel** [comment]
Did you try the latest from develop? It should be fixed now. We will release the version 0.23.0 today.

**Comment by bott0r** [comment]
I updated this morning, (600am GMT), still the same. I'll update when 0.23 is released :) and report back!

**Comment by bott0r** [comment]
I updated to the develop 0.23 this morning and i still have the same visual bug. 

I deploy with docker, with a simple bash script that removes rocket chat, fetches the new version and installs it. Not sure if that has anything to do with it :)

**Comment by rodrigok** [comment]
@bott0r We found the issue, it's related with our theme package, we are fixing it right now, thanks.

**Comment by bott0r** [comment]
You guys are doing amazing work! i am just a mere bug finder :dancers:
