### ISSUE TITLE
"Oops! Something went wrong" while opening some channels via web/desktop since 5.0.0

### ISSUE THREAD

**Issue by iglooom** [RocketChat/Rocket.Chat#26365]
### Description:

Since 5.0.0 we can't open some chats. Got "Oops! Something went wrong." on web/desktop only.
Android works fine.
No errors in logs, even in debug mode.
In browser console: "TypeError: j.replies is undefined"

All this channels was imported from slack earlier and worked just fine. But since 5.0.0 if chat has a thread from slack - this chat can't be opened.
When viewing from android app I've noticed that old threads from slack displayed as e.g. "Messages: 24, Users: 0". After I deleted all this threads - errors gone.

![photo_2022-07-26_18-32-23](https://user-images.githubusercontent.com/27060713/181036737-55296dad-5835-422a-b501-70938d024ca1.jpg)

### Steps to reproduce:

1. Install some old version like 4.6.*
2. Import data from slack
3. Upgrade every single release up to 5.0.0

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: Ubuntu 20.04 LTS
- Deployment Method: docker

If it needs some diagnostics, I can perform queries in mongo.

**Comment by aleadco** [comment]
I can confirm this in 5.0.0-rc12 with manual implementation... In our case no channel was imported, it happens with all rooms created in the service

**Comment by lovekyleman** [comment]
Confirm that

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/26352

**Comment by iglooom** [comment]
I already saw the #26352 but I thought it is different bug, since my related to room/chat, not user profile.

**Comment by treebes** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/26352#issuecomment-1198361464

**Comment by charisteed28** [comment]
I still think that this is a different problem than in [#26352](https://github.com/RocketChat/Rocket.Chat/issues/26352)
Perhaps they are related.

We noticed that the error pops up at the moment when messages imported from Slack appear.
For example, we imported messages in February - and the channels work fine, but when you scroll through the history and scroll to the last imported message, an error pops up.

Error:
```
Uncaught Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at O (/client/views/room/MessageList/components/MessageContent.tsx:1:2814)
    at Dc (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:59696)
    at gi (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:69176)
    at di (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:68510)
    at li (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:68168)
    at Rs (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:114835)
    at nu (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98840)
    at ru (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98768)
    at eu (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98631)
    at Gs (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:95485) {componentStack: '\n    at O (/client/views/room/MessageList/componen…esource=true:1218:63317)\n    at Suspense\n    at f'}
```

**Comment by terR0Q** [comment]
> I still think that this is a different problem than in [#26352](https://github.com/RocketChat/Rocket.Chat/issues/26352) Perhaps they are related.
> 
> We noticed that the error pops up at the moment when messages imported from Slack appear. For example, we imported messages in February - and the channels work fine, but when you scroll through the history and scroll to the last imported message, an error pops up.

Same here. We have this error in all channels when scrolling up to old messages imported from Slack.

**Comment by terR0Q** [comment]
Comparing "normal" rocket messages and imported from Slack I see "username" missing from latter ones.
Slack msg:
```
{
    "_id" : "slack-C01D51RARK7-1646321856-610739",
    "rid" : "5nv7Rf4FijDRbRTmh",
    "u" : {
        "_id" : "gh42iuxxyNZ4NY93Y"
    },
    "msg" : "some text",
    "ts" : ISODate("2022-03-03T15:37:36.000+0000"),
    "tmid" : "slack-C01D51RARK7-1646321186-451239",
    "urls" : [

    ],
    "_updatedAt" : ISODate("2022-03-10T11:35:41.405+0000")
}
```

Rocket message from same room:
```
{
    "_id" : "9spD9eG3uWxdJPJPW",
    "t" : "uj",
    "rid" : "5nv7Rf4FijDRbRTmh",
    "ts" : ISODate("2022-03-10T15:36:47.404+0000"),
    "msg" : "vk",
    "u" : {
        "_id" : "ZRfHYwqjyFC76NTt6",
        "username" : "Saimon"
    },
    "groupable" : false,
    "_updatedAt" : ISODate("2022-03-21T14:04:24.697+0000")
}
```

**Comment by Weterok** [comment]
> > I still think that this is a different problem than in [#26352](https://github.com/RocketChat/Rocket.Chat/issues/26352) Perhaps they are related.
> > We noticed that the error pops up at the moment when messages imported from Slack appear. For example, we imported messages in February - and the channels work fine, but when you scroll through the history and scroll to the last imported message, an error pops up.
> 
> Same here. We have this error in all channels when scrolling up to old messages imported from Slack.

Same here.

**Comment by iglooom** [comment]
Seems I've found a root cause.
In 'normal' threads there is a field `replies` along with `tcount` and `tlm`
`        "replies" : [
                "YXFgesNuvbBpD5hnt",
                "QYSfQEECvgruQBLpS",
                "KXcDtcEqGzoGXaoo9",
                "jhZvN4nZeZkdEifKZ",
                "dHFpxLQRBdGGcwWmW",
                "jMNxBjrxuRGvosEzH",
                "sEDKfb2LqCzmhYjug"
        ],
        "tcount" : 14,
        "tlm" : ISODate("2022-06-10T14:39:35.485Z")
`

But in threads imported from slack there is not `replies`, but frontend expects it should be when `tcount` and `tlm` exists.

Some routine to fix this threads maybe needed. Or just simply unset `tcount` in this threads to bring rooms to live.

**Comment by iglooom** [comment]
Just tried this hack, and it works decent. On all this threads displayed only one participants, but at least all works now and channels/threads can be opened.
`db.rocketchat_message.updateMany({ _id:/slack-/, tcount: { $exists :1}, replies : { $exists: 0}},{ $set: { replies: [ "rocket.cat" ] } })`

**Comment by terR0Q** [comment]
Didn`t fix error for me. Got `matchedCount` and `modifiedCount` `0.0`.

**Comment by iglooom** [comment]
Try to do `use rocketchat` in mongo before query.

**Comment by terR0Q** [comment]
I thought i've selected db before query. modifiedCount: 2703
And this did the trick! All merged messages and threads are now in place and no error is present.

**Comment by dotty37** [comment]
Im having this issue with one channel. How do I implement this DB hack? Im new to Rocket.chat .

**Comment by iglooom** [comment]
@dotty37 if your rocketchat ran from docker-compose then you can run `docker-compose exec mongo mongo rocketchat` and apply command into opened console.

**Comment by dotty37** [comment]
Hi

I deployed using the AWS AMI, 4.0.7, imported the Slack ZIP file and then
upgraded to 5.0.3.
I didn't import on 5.0.3 directly because there is an issue with that
already reported on Github.
If you provide me with some insight on how to run this, then I will give it
a try.

Thanks !

**Comment by iglooom** [comment]
Unfortunately, I'm not familiar with AWS at all. You should find a way to go to mongo console and run queries.

**Comment by LeoColman** [comment]
> Just tried this hack, and it works decent. On all this threads displayed only one participants, but at least all works now and channels/threads can be opened. `db.rocketchat_message.updateMany({ _id:/slack-/, tcount: { $exists :1}, replies : { $exists: 0}},{ $set: { replies: [ "rocket.cat" ] } })`

This hack worked for me and I couldn't find any rooms that are still not working

**Comment by RyousukeUchino** [comment]
same error from ver 5.0.2  
If you installed or updated from Snap Package, you can fix it by doing the following

```
$ rocketchat-server.mongo
----
rs0:PRIMARY> show collections;
rs0:PRIMARY> db.rocketchat_message.updateMany({ _id:/slack-/, tcount: { $exists :1}, replies : { $exists: 0}},{ $set: { replies: [ "rocket.cat" ] } });
```

@iglooom  Thanks for your great tips!

> Just tried this hack, and it works decent. On all this threads displayed only one participants, but at least all works now and channels/threads can be opened. `db.rocketchat_message.updateMany({ _id:/slack-/, tcount: { $exists :1}, replies : { $exists: 0}},{ $set: { replies: [ "rocket.cat" ] } })`

**Comment by paulharris** [comment]
Is there a plan to fix this bug properly?  Or at least compute a better manual query fix?
ie so threads don't just show "only one participant" ?

**Comment by paulharris** [comment]
I've fixed it "more properly" by computing the replies properly.

I did it via python... so install pip,
ie on debian, `apt install python-pip`
and then install pymongo `python -m pip install pymongo` or probably just `pip install pymongo`

And then in python
```
from pymongo import MongoClient
client = MongoClient("localhost")
db = client.rocketchat
table = db.rocketchat_message
for m in table.find({'_id':{'$regex':'^slack-'}, 'tcount': {'$exists':1}, 'replies': {'$exists':0}}):
    r = table.distinct('u._id', {'tmid':m['_id']})
    table.update_one({'_id':m['_id']}, {'$set':{'replies':r}})
```

**Comment by dotty37** [comment]
> Unfortunately, I'm not familiar with AWS at all. You should find a way to go to mongo console and run queries.

I finally had the chance to work on it today. I just had to do mongo --port 27017 and bang, inside the db. Typed the query hack and everything works now. Tested across reboots too. :-)

**Comment by pierre-lehnen-rc** [comment]
Fixed by #26652

**Comment by shaymdev** [comment]
Thanks, you rock.
