### ISSUE TITLE
v5.0.* Code Block Highlighting No Longer Working As Expected

### ISSUE THREAD

**Issue by jadanah** [RocketChat/Rocket.Chat#26388]
There seems to be an issue when rendering a code block

e.g. if I post to `api/v1/chat.postMessage`
```json
{"channel":"testing","text":"```yaml\r\n\"Channel\": \"testing\"\r\n\"Guid\": \"66a242b6-6dc4-4c60-81c2-964d274e39df\"\r\n```"}
```

response:
```json
{"ts":1658738843882,"channel":"testing","message":{"alias":"","msg":"```yaml\r\n\"Channel\": \"testing\"\r\n\"Guid\": \"66a242b6-6dc4-4c60-81c2-964d274e39df\"\r\n```","attachments":[],"parseUrls":true,"groupable":false,"ts":"2022-07-25T08:47:23.748Z","u":{"_id":"f7KxnCCiJn96KAWFG","username":"ukgd.toolkit","name":"UKGD ToolKit"},"rid":"7BtzSPWzf2MQAJkbD","unread":true,"_id":"u9HQTfxNpTarvXSyZ","_updatedAt":"2022-07-25T08:47:23.829Z","urls":[],"mentions":[],"channels":[],"md":[{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"```yaml"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"\"Channel\": \"testing\""}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"\"Guid\": \"66a242b6-6dc4-4c60-81c2-964d274e39df\""}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"```"}]}]},"success":true}
```

without legacy messages:
![Screenshot 2022-07-25 094910](https://user-images.githubusercontent.com/15696150/180738098-d5da4970-a5e4-4223-9c9c-04167d0c23f1.png)

then the code block wont be highlighted unless I activate "Enable Legacy Messages"

with legacy messages:
![Screenshot 2022-07-25 094952](https://user-images.githubusercontent.com/15696150/180738122-e73edd6d-7808-42a9-968b-db3907aa7c26.png)

```
Version
5.0.0-rc.12
Apps Engine Version
1.33.0
Node Version
v14.19.3
Database Migration
279 (July 25, 2022 9:14 AM)
MongoDB
5.0.9 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (6a0fea4e1)
Branch: HEAD
```

_Originally posted by @jadanah in https://github.com/RocketChat/Rocket.Chat/issues/23971#issuecomment-1193772683_

**Comment by jadanah** [comment]
Tested also against version 5.0.1 and issue remains, the only workaround is to navigate to `/account/preferences` and then enable `Use legacy message templates` within the Global section.

**Comment by sketch242** [comment]
I noticed in 5.0.3 that if you put the code block markers on a separate line, it does render the code block properly.

I've also noticed this prior to 5.0 on the android app, not sure exactly when it started.  I assume the difference is that there is no option to use the legacy message parser on mobile apps.  I believe this bug actually predates 5.0, it's just that users' default message parser was changed when 5.0 was released.

**Comment by hugocostadev** [comment]
Fixed by https://github.com/RocketChat/fuselage/pull/739

**Comment by sketch242** [comment]
Just updated to 5.1.2, which does not fix this.  

Here's a screenshot example:  first block is three backticks, foo, three backticks.  Second block is three backticks, newline, foo, newline, three backticks.

With the new message template:

![image](https://user-images.githubusercontent.com/5010790/190280508-e3f721b8-fc0a-488c-ae3c-4c00eb8ee2c4.png)

With the legacy message template, both code blocks display properly.

**Comment by sketch242** [comment]
Apparently not, as 5.3.0 is still broken.  Do we know if it will be in 5.4.0?
