### ISSUE TITLE
5.0.1 Dropdown Menu Flicker

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#26506]
### Description:

After upgrading from 4.8.1 to 5.0.1, the dropdown menus have a flicker that makes selecting items difficult. This seems to happen when there isn't enough space for the dropdown menu to show fully. 

### Steps to reproduce:

1. Make your Rocket.Chat window smaller.
2. Click on any dropdown that takes up more than the available space on the screen.
3. Flicker

### Expected behavior:

No flicker. Easy scrolling. 

### Actual behavior:

https://user-images.githubusercontent.com/6295044/183298572-8fdab633-2191-4e13-9cbd-c29e65eefb53.mp4

(Please note that if your screen does not support 60FPS, you may not see a flicker!)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.1 and open.rocket.chat
- Operating System: Debian 10.12
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: Yup
- NodeJS Version: v14.19.3
- MongoDB Version: MongoDB 5.0.9 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 

<img width="340" alt="Screen Shot 2022-08-07 at 8 32 33 AM" src="https://user-images.githubusercontent.com/6295044/183298691-f9aab399-530a-4870-b16c-5b37398df5da.png">

- Operating System:

<img width="242" alt="Screen Shot 2022-08-07 at 8 32 51 AM" src="https://user-images.githubusercontent.com/6295044/183298709-9aa1b7a1-d390-4c8a-ad6e-d5444fa3fff5.png">

**Comment by TimmiORG** [comment]
I would say this is fixed in 5.0.3. At least I'm not able to reproduce it.

**Comment by TimmiORG** [comment]
Sorry but I'm able to reproduce again in 5.1.1.

**Comment by dudanogueira** [comment]
Hi!

Indeed, I could also reproduce it in latest 5.1.2

Our team is aware of this one, and should fix it soon.

 Thanks for pointing it out.

**Comment by wreiske** [comment]
Also - the flickering is reproducible on the storybook fuselage! https://rocketchat.github.io/fuselage/fuselage/master/?path=/story/navigation-dropdown--default

**Comment by hugocostadev** [comment]
This issue was fixed in our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) 
Thanks for contributing

**Comment by wreiske** [comment]
@hugocostadev , does https://rocketchat.github.io/fuselage/fuselage/master/?path=/story/navigation-dropdown--default need updating? I still see it flickering clear as day.
