### ISSUE TITLE
Problem for importing a channel from Slack

### ISSUE THREAD

**Issue by aleciane** [RocketChat/Rocket.Chat#26553]
Dear all

I have just registered to Rocket.chat, and I am trying to transfer a project from Slack. I am following the procedure you describe here: 

https://docs.rocket.chat/guides/administration/admin-panel/import/slack

However when I finally click on "Start importing", I have a message saying "Failed to start import operation". 

Could you please help me to solve this problem as soon as possible ?

Many thanks in advance.
Evelyne
![Capture d’écran 2022-08-12 à 11 47 11](https://user-images.githubusercontent.com/39910606/184330054-651024d2-f210-4c30-b175-647c6a5f734b.png)
![Capture d’écran 2022-08-12 à 11 47 06](https://user-images.githubusercontent.com/39910606/184330058-c771dd8a-2d2d-4c05-a570-62248303367a.png)
![Capture d’écran 2022-08-12 à 11 46 31](https://user-images.githubusercontent.com/39910606/184330062-c3426759-c6ff-45db-b554-8b623f42fddf.png)

PS: attached are screenshot of several different steps of the procedure.

**Comment by dotty37** [comment]
Hi, this issue was reported starting from 5.0.1, and still happening on 5.0.3
The previously reported issue was #26479
Thanks for adding to this, hopefully, the devs will have some time to solve this.

**Comment by dudanogueira** [comment]
Hi! It should be fixed in 5.1.0.

**Comment by aleciane** [comment]
Still not working. I am on a Mac, and the only version I can install is 3.8.4

Evelyne

**Comment by dudanogueira** [comment]
@aleciane version 5.1.0 is the server version, and it was not released yet.

**Comment by vinogradovia** [comment]
@alecian, do you have users without email in your Slack export file?

I haved similar problem, and i added field `user["profile"]["email"]` in  user.json for every user without email in my slack.zip. Fixed for me. 

version 5.1.0

**Comment by DarinDev1000** [comment]
I also fixed the issue by adding an email field to all the slack bots that didn't have an email

**Comment by wishx** [comment]
Would someone be kind enough to show us how to do this? I have the user.json open in VS Codium, but I don't see anywhere to add `user["profile"]["email"]` or even any actual email addresses from Slack users (no @something anywhere).
Thanks in advance!

**Comment by wishx** [comment]
> I also fixed the issue by adding an email field to all the slack bots that didn't have an email

How did you do it exactly? I can't get it to work in 5.0.3.

**Comment by DarinDev1000** [comment]
I added email like you have but fill in the value with a dummy email:
```
{
        "id": "U040AFSF5QF",
        "team_id": "THJ1RHKPV",
        "name": "slashgif",
        "deleted": true,
        "profile": {
            "title": "",
            "phone": "",
            "skype": "",
            "email": "botname@example.com",
. . .  etc.
```

**Comment by wishx** [comment]
> I added email like you have but filled in the value with a dummy email:
Thanks. I replaced the actual user email addresses with their real email addresses (exported from the Slack user CSV) and the bots with their bot emails, but no luck. It still craps out. I might just have to wait for 5.10.0 on the Cloud server.
If you have any other tips, I'm all ears.

**Comment by DarinDev1000** [comment]
Looks like you're need to wait for the 5.1.0 update

**Comment by DarinDev1000** [comment]
Looks like you're need to wait for the 5.1.0 update. I used 5.1.2
As long as the PR that closed #26479 works, this should be fine to close
