### ISSUE TITLE
Markdown link not recognized with a semicolon

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat#26661]
### Description:

When you create a link in Markdown with a semicolon, it will not be recognized.

### Steps to reproduce:

Write this message : 
![image](https://user-images.githubusercontent.com/12096081/186102903-3ddf8ce1-597f-4be5-b74d-619374110d1c.png)

### Expected behavior:

Link rendered : 
![image](https://user-images.githubusercontent.com/12096081/186103039-788a5f68-c93d-4ff4-99d1-7fc3fc329d01.png)

### Actual behavior:

Link not rendered : 
![image](https://user-images.githubusercontent.com/12096081/186102956-fca295d6-924c-4d83-bcc0-c36d787b7c01.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.4
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 279
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.16

### Client Setup Information

Desktop App and Browser Version:
Operating System: All

### Additional context

Nothing

### Relevant logs:

Nothing

**Comment by masterduster** [comment]
Got same thing on 5.0.3.

**Comment by magenbrot** [comment]
maybe related to #26405

**Comment by xmedeko** [comment]
Note: it works in a Thread view.

**Comment by AlecKinnear** [comment]
Face the same issue. Trying to link to comment section: `https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring#comments` does not generate a Markdown link. Remove the hash tag and it works as before: `https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring`

This works:

`[new post with commercial spam](https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring)`

This does not work:

`[new post with commercial spam](https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring#comments)`

The use case for URLs with hashmarks should be obvious. Apparently this is related to some kind of supercharged emoji script. We don't even allow emojis in our communication as emojis are basically an excuse to write inarticulate garbage. Please do not prioritise gimmicks like emojis over work tools like functioning Markdown.

**Comment by rmaksimov** [comment]
The same behavior with the underscore sign.
Neither `[link_a](https://github.com)` nor `[link\_a](https://github.com)` (escaped) is rendered

**Comment by mmattel** [comment]
Any timleine to fix this? we use a lot of anchors when refrencing and this is an important issue for us.

**Comment by xmedeko** [comment]
@mmattel Workaround is to Use legacy message template see https://github.com/RocketChat/Rocket.Chat/issues/26736#issuecomment-1235373856 (read all discussion to avoid some pitfals). Also note you must have 5.1.1 at least to avoid #26801 .

**Comment by AlecKinnear** [comment]
> Workaround is to Use legacy message template see [#26736 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/26736#issuecomment-1235373856)

This is a pretty awkward workaround. How about fixing a core feature instead in core?

**Comment by hugocostadev** [comment]
Fixed on [Release 5.1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.1.0) But I recommend keeping the product updated with the last stable release.

**Comment by mmattel** [comment]
Hmmm, we are running 5.1.0, but having a `#` in the anchor makes rendering fail.
Mind to give this in your instance a try befor closing?

**Comment by xoxys** [comment]
@hugocostadev can you please reference the exact commit that is intended to fix this? Even on 5.1.3 this issue is still not fixed.

**Comment by AlecKinnear** [comment]
Exciting that a fix is in. An exact commit/release number for the public open source version would be useful for us as well.

**Comment by hugocostadev** [comment]
@mmattel we are aware of this issue and there is already an open PR to fix this!

PR: https://github.com/RocketChat/fuselage/pull/855

**Comment by hugocostadev** [comment]
Hi guys, I think that this fix was introduced in Release Candidate `5.2.0-rc.0`,  by an update in dependencies for `message-parser`.

PR: https://github.com/RocketChat/Rocket.Chat/pull/26876
COMMIT: https://github.com/RocketChat/Rocket.Chat/commit/f4b56815c1caff5febce85f479319aa0be39d6b7

@xoxys and @AlecKinnear I ran a test in open.rocket.chat and gave me this output:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/20212776/193018630-61eb6a52-c70e-4de6-8c0f-22214f148dea.png">

**Comment by mmattel** [comment]
@hugocostadev can you also try
`[installation](https://github.com/RocketChat/Rocket.Chat#installation)`
to see if url's with anchors (`#`) render correct?

**Comment by xoxys** [comment]
It is really confusing how RocketChat handles issues:
- This one was closed https://github.com/RocketChat/Rocket.Chat/issues/26815 as duplicate of this one even if it was talking about HTML anchors using `#` and not `;` 
- this issue was closed, and release 5.1.0 was named as fixed release
- the PR https://github.com/RocketChat/fuselage/pull/855 was linked that should contain a fix, but this PR is not merged yet
- if the PR https://github.com/RocketChat/fuselage/pull/855 is not merged, how could this be fixed in an RC release??
- if this issue is related to an emerged PR, why was the issue closed already?
- if closing this issue was by accident, why has nobody reopened it?

:man_shrugging:

**Comment by hugocostadev** [comment]
Hi @xoxys , sorry, maybe I didn't express myself in the best way.

> - This one was closed https://github.com/RocketChat/Rocket.Chat/issues/26815 as duplicate of this one (#26661), even if it was talking about HTML anchors using # and not ;

**A:** About this, you are correct, I'll reopen it! Thanks for letting me know 

---

> - this issue (#26661) was closed as well, and release 5.1.0 was named as fixed release
> - the PR https://github.com/RocketChat/fuselage/pull/855 was linked that should contain a fix, but this PR is not merged yet
> - if the PR https://github.com/RocketChat/fuselage/pull/855 is not merged, how could this be fixed in an RC release??
> - if this issue is related to an unmerged PR, why was the issue closed already?
> - if closing this issue was by accident, why has nobody reopened it?

**A:** I got confused, this issue is closed due to the last Release Candidate 5.2.0.rc-0

And about the other points I mentioned the PR https://github.com/RocketChat/fuselage/pull/855 to answer @mmattel comment (https://github.com/RocketChat/Rocket.Chat/issues/26661#issuecomment-1262122321) about the hashtag issue, that is the same as https://github.com/RocketChat/Rocket.Chat/issues/26815 that I already reopened 

--- 

Again, sorry for the confusion, and we appreciate your feedback

**Comment by lestercoyoyjr** [comment]
Hi @engelgabriel @xmedeko @rmaksimov @mmattel @xoxys when you have an anchor, proceed with this:

This doesn't work
[test](https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring#comments)

but if you add slash '/' at the end it will work:
[test](https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring#comments/)

now with the ';' issue, this stills persists, We hope it can be solved in 5.2.0 version

**Comment by AlecKinnear** [comment]
Happy to report that on RocketChat 5.3.1 this syntax (which is Markdown with a link target) does take the visitor straight to the comments section:

`[test](https://www.profootballrumors.com/2022/08/cowboys-lt-tyron-smith-tears-hamstring#comments/)`

It even shows the pretty preview properly:

![Markdown-anchor-text-works](https://user-images.githubusercontent.com/107859958/202810114-ce375855-8631-4337-b80e-34973e1b11bd.png)

Thanks to everyone on the RocketChat team who worked to fix (at least in our use case) links with anchors!

**Comment by rmaksimov** [comment]
> [link_a](https://github.com)

this still does not work (5.3.3)

**Comment by AlecKinnear** [comment]
What is the use case for the underline character in a link name @rmaksimov ?

**Comment by rmaksimov** [comment]
I use it to add some specific data (marks): _dev, _test, _prod, etc
As Markdown supports this character ([github_dev](http://github.dev)) it is odd to me that RC adds some restrictions on characters in a link title
