### ISSUE TITLE
Unable to create user in 5.0.5

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#26794]
### Description:

We just upgraded from Rocketchat Version 3.18.7 to 5.0.5 while going through Version 4.1.6 - 4.4.5 - 4.8.4. With the upgrade done we are unable to create new users. There is always an error "object object" in the UI and "invalid email" in the logs. 

### Steps to reproduce:

1. Administration - Users
2. Click New User
3. Insert valid email address and click save, other options dont matter 

### Expected behavior:

Users is created without errors

### Actual behavior:

<img width="201" alt="screenshot-1" src="https://user-images.githubusercontent.com/26652586/188153562-1ed0999c-7444-4146-b58b-7d36e4a089eb.png">

Error in Log:
`{"level":35,"time":"2022-09-02T13:08:14.054Z","pid":1,"hostname":"rocketchat","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","length":"291","host":"xxx","referer":"https://rocketchat/admin/users/new","remoteIP":"xxx","err":{"type":"errorClass","message":"[invalid email]","stack":"Error: [invalid email]\n    at sendNoWrap (app/mailer/server/api.ts:162:9)\n    at Module.send (app/mailer/server/api.ts:201:2)\n    at AccountsServer._onCreateUserHook (app/authentication/server/startup/index.js:211:10)\n    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1172:23)\n    at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:253:28)\n    at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:986:67)\n    at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:1006:14)\n    at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1466:25)\n    at createUser (packages/accounts-password/password_server.js:910:19)\n    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:994:10)\n    at saveNewUser (app/lib/server/functions/saveUser.js:281:23)\n    at saveUser (app/lib/server/functions/saveUser.js:346:10)\n    at Object.post (app/api/server/v1/users.ts:243:22)\n    at app/api/server/api.js:466:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:466:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"invalid email","errorType":"Meteor.Error"},"status":400,"responseTime":128,"msg":"[invalid email]"}
`

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.5
- Operating System: RedHat 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: from Docker
- MongoDB Version: 5.0.11

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Operating System: Windows 10 21H1

### Additional context

We were able to fix the problem by disabling all mail related options in the "Account" settings page. After that the user creation was successful. After we reenabled all mail related options it was still possible to create users. Seems like there has been some sort of hickup with there settings while upgrading through the versions mentioned above. Upgrade guide states that we should not skip too many minor version so we decided to go with there hops.

There are also different errors if we add a domain validation and these errors are correctly displayed in the log. So the server still checks different options before failing on the same "invalid email" error.

I will update this on Monday. We still have an instance where I can go through the options step by step and check what fixes this issue.

### Relevant logs:

`{"level":35,"time":"2022-09-02T13:08:14.054Z","pid":1,"hostname":"rocketchat","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","length":"291","host":"xxx","referer":"https://rocketchat/admin/users/new","remoteIP":"xxx","err":{"type":"errorClass","message":"[invalid email]","stack":"Error: [invalid email]\n    at sendNoWrap (app/mailer/server/api.ts:162:9)\n    at Module.send (app/mailer/server/api.ts:201:2)\n    at AccountsServer._onCreateUserHook (app/authentication/server/startup/index.js:211:10)\n    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1172:23)\n    at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:253:28)\n    at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:986:67)\n    at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:1006:14)\n    at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1466:25)\n    at createUser (packages/accounts-password/password_server.js:910:19)\n    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:994:10)\n    at saveNewUser (app/lib/server/functions/saveUser.js:281:23)\n    at saveUser (app/lib/server/functions/saveUser.js:346:10)\n    at Object.post (app/api/server/v1/users.ts:243:22)\n    at app/api/server/api.js:466:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:466:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"invalid email","errorType":"Meteor.Error"},"status":400,"responseTime":128,"msg":"[invalid email]"}`

**Comment by dudanogueira** [comment]
Hi!

We just released 5.1.0 today, that fixes the [object Object] and should give you the readable error.

Let me know if this will also help on the email issue. Regarding this one, for some reason, your email seems to not pass the validation, or maybe it is already being used on another user.

Let me know if this helps.

**Comment by comander192** [comment]
Hi @dudanogueira 

Thanks for informing us about the new version, we will check this one asap. As you can see in the screenshot we used the address test123@gmail.com which is a valid address. I checked it with the regex in the apps/meteor/lib/emailValidator.ts which seems to be used here.

In the meantime I tested which option prevented us from creating new users. It was the "Manually Approve New Users" under Account Settings. As soon as I disabled this option, the error was gone and the user successfully created.

`{"level":35,"time":"2022-09-05T12:51:52.342Z","pid":1,"hostname":"rocketchat","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","length":"292","host":"xxx","referer":"https://rocketchat/admin/users/new","remoteIP":"xxx","status":200,"responseTime":126}
`

As soon as I reenable this option the error comes back:
`{"level":35,"time":"2022-09-05T12:58:28.280Z","pid":1,"hostname":"rocketchat","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","length":"289","host":"xxx,"referer":"https://rocketchat/admin/users/new","remoteIP":"xxx","err":{"type":"errorClass","message":"[invalid email]","stack":"Error: [invalid email]\n    at sendNoWrap (app/mailer/server/api.ts:162:9)\n    at Module.send (app/mailer/server/api.ts:201:2)\n    at AccountsServer._onCreateUserHook (app/authentication/server/startup/index.js:211:10)\n    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1172:23)\n    at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:253:28)\n    at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:986:67)\n    at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:1006:14)\n    at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1466:25)\n    at createUser (packages/accounts-password/password_server.js:910:19)\n    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:994:10)\n    at saveNewUser (app/lib/server/functions/saveUser.js:281:23)\n    at saveUser (app/lib/server/functions/saveUser.js:346:10)\n    at Object.post (app/api/server/v1/users.ts:243:22)\n    at app/api/server/api.js:466:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:466:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"invalid email","errorType":"Meteor.Error"},"status":400,"responseTime":112,"msg":"[invalid email]"}
`

Hope this helps in any way. I will check version 5.1.0 now.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/26652586/188455189-f00abbbb-14f8-4235-8c6e-56221a7cec73.png">

**Comment by comander192** [comment]
@dudanogueira and the problem persists in 5.1.0 still :(

`{"level":35,"time":"2022-09-05T13:13:13.628Z","pid":1,"hostname":"rocketchat","name":"API","method":"POST","url":"/api/v1/users.create","userId":"xxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","length":"302","host":"xxx","referer":"https://rocketchat/admin/users/new","remoteIP":"xxx","err":{"type":"errorClass","message":"[invalid email]","stack":"Error: [invalid email]\n    at sendNoWrap (app/mailer/server/api.ts:157:9)\n    at Module.send (app/mailer/server/api.ts:196:2)\n    at AccountsServer._onCreateUserHook (app/authentication/server/startup/index.js:211:10)\n    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1172:23)\n    at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:253:28)\n    at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:986:67)\n    at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore-umd.js:1006:14)\n    at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1466:25)\n    at createUser (packages/accounts-password/password_server.js:910:19)\n    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:994:10)\n    at saveNewUser (app/lib/server/functions/saveUser.js:282:23)\n    at saveUser (app/lib/server/functions/saveUser.js:351:10)\n    at Object.post (app/api/server/v1/users.ts:243:22)\n    at app/api/server/api.js:463:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"invalid email","errorType":"Meteor.Error"},"status":400,"responseTime":143,"msg":"[invalid email]"}
`

`Deployment
Version
5.1.0
Deployment ID
xxx
Apps Engine Version
1.34.0
Node Version
v14.19.3
Database Migration
281 (September 5, 2022 3:11 PM)
MongoDB
5.0.11 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (34df27ac1)
Branch: HEAD
PID
1`

**Comment by dudanogueira** [comment]
Hi!

Not sure this is it. I was able to create all kinds of user, with the same configuration you had :thinking: 

The error was raised right here:
https://github.com/RocketChat/Rocket.Chat/blob/5.1.0/apps/meteor/app/mailer/server/api.ts#L157

My bet is that the email not being validated is one of the admin emails.

So it will fail the user creation while giving a unrelated message

Can you check if all your admins have a valid email?

**Comment by comander192** [comment]
Hmm we also cant recreate this issue with our test installation with minimal data and users. I checked all admin accounts in prod and they all have a valid email address. I also changed the email addresses on our test installation to the ones in the prod environment and it still works in testing. This is really weird we cant recreate the issue there, same as you tried.

**Comment by debdutdeb** [comment]
long shot - but check the exact payload the web client is sending to the server. You can do so in the network tab under devtools; for example

![image](https://user-images.githubusercontent.com/76006232/189010078-179996d8-9b53-4eca-95a9-8adfdca8a80b.png)

filter by `users.create`

**Comment by darkpixel** [comment]
Logs from container:

```
{"level":35,"time":"2022-10-25T16:09:52.678Z","pid":1,"hostname":"rocketchat-rocketchat-5d4cbcfff6-7hvdk","name":"API","method":"POST","url":"/api/v1/users.update","userId":"LB-redacted-5qh","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.7 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36","length":"273","host":"rocket.-redacted-.com","referer":"https://rocket.-redacted-.com/admin/users/edit/tJ8-redacted-YHR","remoteIP":"-redacted-","err":{"type":"errorClass","message":"Invalid domain [error-invalid-domain]","stack":"Error: Invalid domain [error-invalid-domain]\n    at validateEmailDomain (app/lib/server/lib/validateEmailDomain.js:66:10)\n    at _setEmail (app/lib/server/functions/setEmail.ts:52:2)\n    at app/lib/server/lib/RateLimiter.js:21:15\n    at saveUser (app/lib/server/functions/saveUser.js:377:3)\n    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/users.ts:71:40)\n    at packages/dispatch_run-as-user.js:211:14\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)\n    at Object.post (app/api/server/v1/users.ts:71:11)\n    at app/api/server/api.js:463:96\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\n    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"error-invalid-domain","reason":"Invalid domain","details":{"function":"RocketChat.validateEmailDomain"},"errorType":"Meteor.Error"},"status":400,"responseTime":35,"msg":"Invalid domain [error-invalid-domain]"}
```

I notice 'ratelimiter' is in there...
The user I'm trying to change was blocked because she forgot her password and locked herself out.  Is it possible the rate limiter is causing problems for admins when a user is locked out?

**Comment by darkpixel** [comment]
It's not the rate limiter.  I can't create or edit accounts.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
