### ISSUE TITLE
Cannot modify custom emoji without re-uploading it

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#26980]
### Description:

When editing a custom emoji without uploading a new file, the error message "No file uploaded" appears when clicking the "Save" button and the changes will not be saved.

### Steps to reproduce:

1. Add a custom emoji in case you don't already have one.
2. Select a custom emoji for editing.
3. Edit its name or aliases.
4. Click the "Save" button.

### Expected behavior:

The changes are saved without an error.

### Actual behavior:

An error message is shown and the changes will not be saved:

![image](https://user-images.githubusercontent.com/404840/193107547-b48f6baf-4918-42ba-83ab-6fdb65e1402a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.4
- Operating System: Debian GNU/Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chromium 106.0.5249.61 (Offizieller Build) Arch Linux (64-Bit), Firefox 105.0.1 (64-Bit)
- Operating System: Arch Linux

**Comment by florisvangeel** [comment]
https://user-images.githubusercontent.com/1267925/193622341-fb8e8183-6d51-4816-bf02-a80c37452b69.mp4

Confirmed this does not work in 5.1.4

**Comment by kartikbh6614** [comment]
firstly create an emojis you want ADD then edit to them with help of typescript then get to server and add to them emojis or single symbol list

**Comment by codewithmitesh** [comment]
Is anyone solving this issue? If not, @dudanogueira  would you kindly assign this to me?

**Comment by Cob0ld** [comment]
can't tell if its related but we can't update our custom emojis ... it will let you save the new emoji but always false back to the older image. this is happens even if i delete the emoji and recreate it later.

**Comment by dudanogueira** [comment]
there is indeed something going off here. Let's try to make it into 6.1.0!

**Comment by Gardezi1** [comment]
Hey guys can i pick up this issue. Seems like nobody has started working on this issue

**Comment by XpertWebApp** [comment]
this issue is fixed now , please check

https://user-images.githubusercontent.com/68045060/221577178-b52c5ce2-8ecc-4c28-9e0a-08633be8c388.mp4

**Comment by paulchen** [comment]
> this issue is fixed now , please check

@XpertWebApp in which release? In 5.4.3 this problem still persists.

**Comment by AdityaSingh-02** [comment]
hey @XpertWebApp which version are you using, on my 6.0.0-develop i am still facing the issue

**Comment by Gardezi1** [comment]
I'll start looking into the issue. Because I'm also running into this issue.

**Comment by XpertWebApp** [comment]
> hey @XpertWebApp which version are you using, on my 6.0.0-develop i am still facing the issue

i am using node version 14.21.2 ,(npm v 6.14.17)

**Comment by paulchen** [comment]
> This issue can be closed.

No, it can't. I just fired up the current `develop` image from Docker Hub locally. It identifies itself as `6.3.0-develop` from Git revision `3d3bf4d832`. This is on par with the current `develop` Git branch.

I'm afraid that this issue still occurs using that version:

https://user-images.githubusercontent.com/404840/233158533-b55f4de3-15cf-4059-91d4-f9805434908c.mp4

**Comment by AdityaRaut13** [comment]
The issue is reproducible. The problem seems to arise because it is giving a 400 bad request. After investigating further, I came to realise the following :  
1.  `getUploadFormData` needs to always take a file in the request.
![image](https://github.com/RocketChat/Rocket.Chat/assets/102903554/74d14120-f238-4393-a9be-d4b1c73640f0)
The function `getUploadFormData` is only updating the fields when there exists a file in the request.
I thought about updating the getUploadFormData without file parameter, but, other routes might require it to be present.
Location of `getUploadFormData` : `apps/meteor/app/api/server/lib/getUploadFormData`.
Thanks in advance for any help, as I am new to contributing.
@dudanogueira  let me known as to what to do.

**Comment by mahmoodshariff123** [comment]
is this issue is open or closed? If it is it open can you please assign it to me?
