### ISSUE TITLE
Channels that start with a number in it fails to link

### ISSUE THREAD

**Issue by kassemz** [RocketChat/Rocket.Chat#27134]
### Description:

Channels that start with a number in it fails to link

### Steps to reproduce:

1. Create a channel with a name that starts with a number like 1test
2. Send a message in another channel with #1test in it.
3. #1test isn't turning into a link and stays as text.

### Expected behavior:

The #1test to turn into a link.

### Actual behavior:

![image](https://user-images.githubusercontent.com/20356702/197882986-ddd3f7b8-30f1-4ebd-94aa-650205d0a65f.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.8.3
- Operating System: Ubuntu Linux
- Deployment Method: Snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.17 

### Client Setup Information

- Desktop App or Browser Version: Desktop app 3.8.12
- Operating System: Windows 10

**Comment by dudanogueira** [comment]
@ujjwalban thanks!!

Indeed, I was not able to reproduce this in 5.3.0-rc.2. This is was probably fixed with recent message parser fixes.

Closing. Thanks @kassemz for pointing it out!

**Comment by kassemz** [comment]
Hi @dudanogueira  and @ujjwalban 

I upgraded the server to 5.2.0 and the issue still exists. Any ideas I can try? Thanks in advance!
