### ISSUE TITLE
Incorrect presence (everyone is present)

### ISSUE THREAD

**Issue by maluhub** [RocketChat/Rocket.Chat#27145]
### Description:

Since last update, everyone is present 24/7. 
When someone changes his status it works well, but when it comes to logging off Rocketchat or turning off the computer, the presence doesn't get updated.

### Steps to reproduce:

1. Go to members list:

### Expected behavior:

This is deep nigth, only few of members should show green icon.

### Actual behavior:

Everyone is green:
![image](https://user-images.githubusercontent.com/28625716/198527516-ef919023-2558-4a7b-8664-6109777eece5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Operating System:  Ubuntu 22.04LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version:  v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger (optlog enabled)

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Windows 10, Windows 11

### Additional context

The issue is likely to be present since last update 

### Relevant logs:

Server logs:

```
{"level":40,"time":"2022-10-28T07:43:16.740Z","pid":1076,"hostname":"rocketchat","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
{"level":40,"time":"2022-10-28T07:43:26.629Z","pid":1076,"hostname":"rocketchat","name":"VoIPService","msg":"VoIP service already stopped"}
{"level":51,"time":"2022-10-28T07:43:27.584Z","pid":1076,"hostname":"rocketchat","name":"Migrations","msg":"Not migrating, already at version 281"}
ufs: temp directory created at "/tmp/ufs"
[DatabaseWatcher] Using change streams
+-------------------------------------------------+
| SERVER RUNNING |
+-------------------------------------------------+
| |
| Rocket.Chat Version: 5.2.0 |
| NodeJS Version: 14.19.3 - x64 |
| MongoDB Version: 4.4.15 |
| MongoDB Engine: wiredTiger |
| Platform: linux |
| Process Port: 3000 |
| Site URL: [XXX] |
| ReplicaSet OpLog: Enabled |
| Commit Hash: 08f03cc9d8 |
| Commit Branch: HEAD |
| |
+-------------------------------------------------+
Loaded the Apps Framework and loaded a total of 2 Apps!
{"level":50,"time":"2022-10-28T07:44:43.018Z","pid":1076,"hostname":"rocketchat","name":"System","msg":"Exception while invoking method autoTranslate.getSupportedLanguages 'Auto-Translate is disabled [error-autotranslate-disabled]'"}
{"level":50,"time":"2022-10-28T07:44:50.832Z","pid":1076,"hostname":"rocketchat","name":"System","msg":"Exception while invoking method autoTranslate.getSupportedLanguages 'Auto-Translate is disabled [error-autotranslate-disabled]'"}
```

Application logs:
```
DevTools failed to load source map: Could not parse content for file:///C:/Users/user/AppData/Local/Programs/Rocket.Chat/resources/app.asar/app/html-parse-stringify.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/user/AppData/Local/Programs/Rocket.Chat/resources/app.asar/app/fuselage.development.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/user/AppData/Local/Programs/Rocket.Chat/resources/app.asar/app/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/user/AppData/Local/Programs/Rocket.Chat/resources/app.asar/app/stylis.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/user/AppData/Local/Programs/Rocket.Chat/resources/app.asar/app/focus-within-polyfill.js.map: Unexpected end of JSON input
```

**Comment by Gummikavalier** [comment]
I cannot replicate this issue in our test environment with RC 5.2.0. I also tried with native oplog on and off.
RHEL8 with tar installation, two nodes setup.

**Comment by tobiasreinhard** [comment]
We have a similiar issue, but instead of online some of our users stay "offline" even when they are active.

![grafik](https://user-images.githubusercontent.com/10668507/199672841-281c19ec-2a5c-4075-b7fe-2095b421dae1.png)

Our RC instance (single instance, Docker):

![grafik](https://user-images.githubusercontent.com/10668507/199672931-acfef746-46e6-4291-a439-1b7351e58880.png)

**Comment by maluhub** [comment]
Problem solved by deleting stuck sessions from RocketChat DB: https://github.com/RocketChat/Rocket.Chat/issues/27187#issuecomment-1303826402

**Comment by tobiasreinhard** [comment]
I've tried your suggestion, but it does not work in our environment.

**Comment by kertiskz** [comment]
I have the same problem, version RC 5.3, deleting hung sessions from the database did not help.

**Comment by TimmiORG** [comment]
Same with 5.3.2.
It is working correctly if I sign out from rocket chat. But it looks like it is not timing out if I'm just closing the electron for example.

**Comment by JohnDorianMD** [comment]
I have the same problem after updating from 5.2.0 to 5.3.2.

**Comment by santos525** [comment]
Same problem here after updating from 5.1.3 to 5.3.2.

**Comment by jsanchezba** [comment]
We are facing the same issue after upgrading from 3.18.2 => 4.0.0 => 5.3.1, we are using LDAP.
Neither works if i log out

**Comment by klepptor** [comment]
Same here after upgrading from 5.1.2 to 5.3.3

Docker with MongoDB 5.0.14

**Comment by tobiasreinhard** [comment]
still not fixed yet, very disappointing.

**Comment by ZsBT** [comment]
Same here. Status of all users are stuck. Using with mongo cluster under docker.
I'd be happy for a patch while waiting for the official fix.

**Comment by rrmt23** [comment]
The problem persists on version 5.4.3.
I hope there is still time to fix this on version 6.0+?

**Comment by shevchukma** [comment]
I'm experimenting right now.
On version 5.4.5:
The problem is present if the user session is on an instance that has DISABLE_PRESENCE_MONITOR enabled. If you set DISABLE_PRESENCE_MONITOR=no on all instances, then this issue does not exist.
On version 6.0.1:
On the first instance DISABLE_PRESENCE_MONITOR=no is set, on the other three DISABLE_PRESENCE_MONITOR=yes. The reverse proxy redirects client requests to the last three instances, the presence instance does not process client requests. In this case, "Auto Away" works.
It looks like this issue has been fixed in version 6 👍

**Comment by grpanho** [comment]
Same here after upgrading to 6.0.0.
Docker with MongoDB 6.0.5.

**Comment by bseclier** [comment]
The issue is still in 5.4.10 and the UsersSessions cleanup didn't solve the problem. 
Setting DISABLE_PRESENCE_MONITOR=no didn't solve it neither.
We're still facing the issue with only one instance.

**Comment by pythys** [comment]
I also experienced this issue after upgrading to 6.6.0 as I [mentioned in a related ticket](https://github.com/RocketChat/Rocket.Chat/issues/27468#issuecomment-1947771961) and I'm sharing a quick script to help with resetting until it's done

```bash
#!/bin/bash
docker exec -it rocketchat-mongo-1 mongo --eval "\
    db = db.getSiblingDB('rocketchat'); \
    db.usersSessions.deleteMany({}); \
    db.users.updateMany({status:'online'},{'\$set':{status:'offline'}});"
```

**Comment by KIDS-interactive** [comment]
Yep. Same here after upgrading to 6.6.0...

**Comment by sampaiodiego** [comment]
the presence status issues on 6.6.0 were fixed on [6.6.1](https://github.com/RocketChat/Rocket.Chat/releases/tag/6.6.1)

**Comment by pythys** [comment]
I've upgraded to 6.6.1 and the issue seems to be still not resolved.
