### ISSUE TITLE
Markdown links in the topic referring to the same RC instance open up a new tab

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#27491]
### Description:

In the new message template links referring to the same RC instance open up in a new tab instead of directing the user to the new location directly.

In the old message parser these self referred markdown links opened in the same browser window/tab.

The method is often used in topic and announcement notification on channels to promote other related channels.

### Steps to reproduce:

1. Create a markdown link into topic or announcement such as `[#support](https://open.rocket.chat/channel/support)`
2. Click the link in the browser.

### Expected behavior:

User session gets directed to the channel in the link.

### Actual behavior:

A new RC tab opens up.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox or Chrome

**Comment by Gummikavalier** [comment]
My bad. This is fixed in RC 5.4.0. I used testing RC 5.3.x.

**Comment by aurisnoctis** [comment]
Hello and thank you for Rocket.Chat!

This is not fixed, actually. I use the web client and when clicking on a link like https://chat.somedomain.cloud/channel/peer-support from another channel or channel topic in the same **Rocket.Chat instance**, a new browser tab opens.

At the moment `#` links cannot be generated in channel topics so the workaround or links in topics are https links (e.g. formatted as markdown links). They are the only way at the moment to link from one channel to another via topic, for example in a channel topic:
> This channel is for general discussion, please use #peer-support to discuss technical issues.

In the above example, #peer-support is not auto-converted to a link to the channel. So the workaround is to use e.g. [#peer-support](https://chat.somedomain.cloud/channel/peer-support) in the channel topic. Clicking that link, however

* should not open a new tab when clicking it from a channel like https://chat.somedomain.cloud/channel/general
* should open in the same Rocket.Chat desktop instance when clicking on it in the desktop client (at the moment instead a browser window is opened and users are moved from the desktop client to the browser)
