### ISSUE TITLE
Message tool menu accessibility issue

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#29575]
### Description:

This is an UI accessibility issue. (Accessibility as dictated in EU legislation.)

When the zoom or scaling of the web client or operating system is very high, RC opens up the message tool menu below the message, instead of above the message where there would be much more room for the menu.

This makes it very hard to read and scroll the menu.

### Steps to reproduce:

1. Increase zoom in the browser or decrease the height so that elements start slightly overlap.
2. Scroll to the bottom of the channel that has enough messages to fill up the screen.
3. Select three dots menu in the end of the message tool.

### Expected behavior:

The menu opens up above the message for easier reading (and scrolling if it does not fit to the above element space).

![Screenshot from 2023-06-19 09-27-49](https://github.com/RocketChat/Rocket.Chat/assets/6958942/f3b4d5f2-4fab-41b1-be99-1b523ae12330)

### Actual behavior:

When there is not enough space to open up on top of the message, the menu opens up below into much smaller space. It becomes really hard to read and use.

![Screenshot from 2023-06-19 09-13-18](https://github.com/RocketChat/Rocket.Chat/assets/6958942/bf7a46e0-a36a-4034-b9e5-cc3d8fdcd680)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.6
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Any browser
- Operating System: Any OS

### Additional context

This happens easily in the pretty common scenario where the user has a FullHD (1920x1080) screen and Windows has been set to 150% scaling.

**Comment by hugocostadev** [comment]
Thanks for reporting @Gummikavalier , we are already aware 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Re-Dei** [comment]
I would like to work on this issue

**Comment by Re-Dei** [comment]
I have found the bug but I am having trouble finding the code of the element. Is there any documentation on the folder structure of this repository? @hugocostadev

**Comment by Dnouv** [comment]
Thank you so much for reporting the issue @Gummikavalier ; this issue is resolved. And no longer thereon the RC. 
Here is the screenshot:

![image](https://github.com/RocketChat/Rocket.Chat/assets/61188295/615393d7-8c1a-42bb-9fdc-410e34f23bd5)

Please give it a try once more. And feel free to close the issue if there are no further questions. Thank you!

**Comment by Re-Dei** [comment]
@Dnouv Thank you for your reply but after giving it one more try using scale 150% in 1920x1080 scree as claimed by @Gummikavalier, I found that the issue still existed. Here is the screenshot of the issue
![Screenshot (23)](https://github.com/RocketChat/Rocket.Chat/assets/97937213/4a728cda-083d-4f4c-be94-c27c7cc3bb08)
The message toolbox becomes too small which makes it hard to read the options.
![Screenshot (24)](https://github.com/RocketChat/Rocket.Chat/assets/97937213/01d723d8-3aa2-4ca0-81af-90c2b8893bce)
The toolbox tends to open towards the bottom which makes it hard to read the message.

**Comment by Dnouv** [comment]
Thank you for confirming it, Re-Dei. Yes, it happens when we do a super zoom (~150%). Just to let you know, the team is working on improving this. 

Thank you!

**Comment by Gummikavalier** [comment]
Thanks for looking into this for both. :hugs: 

Just to keep this issue up to date, it still happens in RC 6.3.1. I'll check again at 6.4.0.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this one because it was fixed here: #30197

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by Gummikavalier** [comment]
Indeed working in RC 6.4.1. Thanks! :hugs:
