### ISSUE TITLE
History message display error when using 'zh' and 'zh-CN' locale

### ISSUE THREAD

**Issue by chaoslawful** [RocketChat/Rocket.Chat#30082]
### Description:

In webpage UI,  error messages raised instead of showing historical messages when browsing some channel if user preferred locale was set to 'Chinese'. 

### Steps to reproduce:

1. Go to 'Account' / 'Preferences' / 'Localization'
2. Click on 'Language', select 'Chinese' and click 'Save changes'
3. Browse channel messages

### Expected behavior:

Show historical messages without errors.

### Actual behavior:

![屏幕截图 2023-08-15 124228](https://github.com/RocketChat/Rocket.Chat/assets/56617/51815d8a-c7f8-43d6-a095-cca7242814f1)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1
- Operating System:  Ubuntu 20.04.6 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge 115.0.1901.203 (64-bit)
- Operating System: Windows 11

### Additional context

It seems that there are bugs in apps/meteor/private/moment-locales/zh.js and zh-cn.js . These files used functions like 'this.minutes()', 'this.diff()' and 'this.unix()' which no other moment locale files has ever used.

### Relevant logs:

Browser console:

![屏幕截图 2023-08-15 124309](https://github.com/RocketChat/Rocket.Chat/assets/56617/97acdcbd-b2bd-4ca1-892e-d1edacc8a108)

**Comment by chaoslawful** [comment]
The error message won't appear as long as the user language preference is set to any language other than 'Chinese'

**Comment by luodaoyi** [comment]
Same Error

**Comment by lovekyleman** [comment]
Same error

**Comment by cm-quint** [comment]
> The error message won't appear as long as the user language preference is set to any language other than 'Chinese'

I have users using spanish and also experiencing the same error. I was still unable to pin point the exact reason, but it seems to be related to users in different timezones and/or with different language settings, but also dependable on the browser settings itself. 

I did a test with a user that was not being able to communicate with other, one side using spanish, the other using english. When changing spanish to english but also using a browser set to english, it worked. Switching back to the user side which has the browser set to spanish, doesn't work, even if the profile is still set as english.

**Comment by luodaoyi** [comment]
I find load 'zh_CN.json'  http code return 400 . Then application was crash

**Comment by gusarg81** [comment]
I am facing the same problem (https://github.com/RocketChat/Rocket.Chat/issues/30113#issuecomment-1683884131). My users are Spanish speakers as well, so Spanish Language is being set.

Any way to fix this? Is kind critical... Thanks.

**Comment by hugocostadev** [comment]
Seems to be fixed now in the latest release, could you check, please? Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by viccar20** [comment]
Hello,
We noticed the problem in v 6.3.1, and we recently updated to 6.3.3 but the problem persists.
For now the temporary solution has been to notify our users that they cannot use the Spanish language, but we need a definitive solution soon.
Is there anything new in the case? When is a solution expected?
Thanks in advance

**Comment by ordepmas** [comment]
The same problem happened to us. We are using Catalan language but the same happens with Spanish. I have found that the problem is related to quotes. Chats containing quoted messages do not work in languages different from english.

**Comment by soyes** [comment]
Same problem here also in Spanish and v 6.3.3 version

**Comment by viccar20** [comment]
Hello,
Just confirm that the problem persists in version 6.3.4.
Regards

**Comment by SerPenTargo** [comment]
> Hello, Just confirm that the problem persists in version 6.3.4. Regards

Hello.

I confirm that the problem is still there in version 6.3.6 with Russian localization.

**Comment by lovekyleman** [comment]
Well done. It's fixed in version 6.3.7.

**Comment by SerPenTargo** [comment]
Nope. The problem persists in 6.3.7. Moreover, every time I open the list of users or channels in the container log I get Deprecation Warnings spam.
![image](https://github.com/RocketChat/Rocket.Chat/assets/119787861/d02e6274-b398-48ec-8965-90e71f9cc2f2)
![image](https://github.com/RocketChat/Rocket.Chat/assets/119787861/c91a28af-81ce-4efb-97df-17865442fce8)

**Comment by viccar20** [comment]
Hello, 
We update to 6.3.7 and now, we can use spanish language without problems,
Thanks

**Comment by HanadaLee** [comment]
@hugocostadev 
When I upgraded to 6.4.0, I found that everything was broken.

 i18n could not be loaded, the log showed that zh.js was not found, I did not find zh.js in the docker container, but only zh-CN.js , zh-TW.js, zh-HK.js. 

I don't know if the fix for this issue caused the bug. I'm so bothered now that I was forced to downgrade to version 6.3.2 to avoid the impact. Can you help me take a look at it?

https://github.com/RocketChat/Rocket.Chat/issues/30597

```{"level":50,"time":"2023-10-26T18:07:25.077Z","pid":1,"hostname":"70b0611c17f7","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js<br>    at getAsset (/app/bundle/programs/server/boot.js:303:21)<br>    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)<br>    at server/lib/getMomentLocale.ts:7:17<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/meteor.js:367:22<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)<br>    at packages/ddp-server/livedata_server.js:1818:36<br>    at new Promise (<anonymous>)<br>    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)<br>    at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)<br>    at app/api/server/v1/misc.ts:559:33<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/v1/misc.ts:559:17<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}} 
```

![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/b0f5d632-2703-498f-a2ad-eeeacee6ea24)

**Comment by filefi** [comment]
v6.4.3 keep logging this error and high memory high cpu. I am going to reopen this issue.
