### ISSUE TITLE
Opening moderation console window results in GUI crash 

### ISSUE THREAD

**Issue by paymanzafar1** [RocketChat/Rocket.Chat#30096]
### Description:
I am using Persian language which is RTL. When I select the Moderation Console menu item, the below error message is shown. There is no problem when I switch to English language:

![14](https://github.com/RocketChat/Rocket.Chat/assets/91053236/984e51d1-236b-4b21-815b-b996e6c6c207)

**Comment by liyue1010110** [comment]
backup you /opt/Rocket.Chat/programs/server/assets/app/i18n/en.i18n.json; rename (need to use language).json to en.i18n.json; switch to English language;  clear the browser Cache and  reload the page @paymanzafar1

**Comment by paymanzafar1** [comment]
Thank you very much for your solution.
But please note that Persian language is RTL, and English language is LTR. I think it makes a problem in UI.

**Comment by esnutd** [comment]
You can change anything free and powerful.(English)
salam.khoobi? say kon khodet RTL koni ziad sakht nist vali har bar ke update koni ehtemalesh hast ke berize beham.chon class ha taghir mikone.(Persian)

**Comment by hugocostadev** [comment]
Seems to be fixed now in the latest release, could you check, please? Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by paymanzafar1** [comment]
Hi There.

I installed the latest version 6.3.3 today. The language is set to Persian, but the application pages are always LTR not RTL. So the problem does not happen. But Persian is a RTL language not LTR.
The livechat widget is OK.

**Comment by paymanzafar1** [comment]
The problem is not solved even in 6.3.4 version.

**Comment by hugocostadev** [comment]
Got it @paymanzafar1 we will investigate

**Comment by KevLehman** [comment]
For the "invalid date", we have a PR :)
https://github.com/RocketChat/Rocket.Chat/pull/30209 we're waiting internal process for merging it into develop

**Comment by Dnouv** [comment]
The Moderation Console page crash is fixed here -> https://github.com/RocketChat/Rocket.Chat/pull/30393. 

Thank you!

**Comment by paymanzafar1** [comment]
@Dnouv , @hugocostadev 
Hi.
Thank you very much. The GUI crash in Moderation menu is solved, but the GUI crash is still there in Omnichannel->Analytics menu.
