### ISSUE TITLE
Adding guests to channels and teams -> limit reached

### ISSUE THREAD

**Issue by Alpha6333** [RocketChat/Rocket.Chat#30299]
### Description:

I create a user as admin with the role Guest. I want to add this user to a channel or team with /invite @test.user or via the web gui Add User.

After that Rocket.Chat gives me the following message.

```
error-max-rooms-per-guest-reached
```

### Steps to reproduce:

1. Go to a channel (public/private)
2. Type the command `/invite @test.user`
3. Error message appears in the channel

### Expected behavior:

That the user is added.

### Actual behavior:

Is not added and an error message comes.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.3
- Operating System: Ubuntu 20.04 - Server
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Both and all Versions
- Operating System: All

### Additional context

Rocket.Chat app, not the server, runs in German in my profile. 

### Relevant logs:

No logs found that could help.

**Comment by DATA-HORIZON** [comment]
Guest users are an enterprise feature: https://www.rocket.chat/pricing

Do you have a license?

**Comment by didierm** [comment]
Fixed in #30488 ?

**Comment by nkeilar** [comment]
Looks like the fix is scheduled for 6.5. I'm screwed at the moment as I can't onboard clients as guests due to this issue. If I'm correct in my understanding then until its released in 6.5, I'm unable to add guests to the CE edition. Would say this is a major regression that CE users can't add guests... I understand the push may be to get CE users to get Enterprise licences, if that is the case CE users should be clearly notified. If not then its a bug. 

When I try to add people I get a red warning "The maximum number of rooms per guest has been reached"

**Comment by himpierre** [comment]
Just tried 6.5.0. To my big disappointment the problem still exists.

**Comment by himpierre** [comment]
Took a closer look. Apparently they decided to move the guest user feature to the enterprise version.

**Comment by himpierre** [comment]
Took an even closer look. After unsubscribing from starter one is back to community edition. And here adding guests to channels work. \o/

**Comment by madnificent** [comment]
@himpierre How did you unsubscribe from starter?

**Comment by juzser** [comment]
Version 6.5.2 and I'm also getting this issue...

**Comment by saschafoerster** [comment]
I had the starter license (50 users) with 9 users and 2 guests. I was not able to add other guest (for debugging purposes with the rocketchat team) until I removed the starter license and went back to the community license. I would expect, that seats are counted for users + guests, at last.

**Comment by juzser** [comment]
Same issue, and still occur until now. This limitation is really annoy.
