### ISSUE TITLE
Workspace reloading continously

### ISSUE THREAD

**Issue by CulturalProfessor** [RocketChat/Rocket.Chat#30717]
### Description:

Rocket.Chat workspace is reloading continuously on firefox .
### Steps to reproduce:

1. Go to rocket.chat
2. wait for workspace to load up.

### Expected behavior:

Workspace should loadup immediately

### Actual behavior:

[Screencast from 23-10-23 07:40:45 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/92238941/9ac6eaa0-e3ad-4deb-b1b4-da2262a0a98d)

### Client Setup Information

- Desktop App or Browser Version: Mozilla firefox snap for Ubuntu Version 118.0.1 (64-bit)
- Operating System: Ubuntu 22.04.1 LTS

### Relevant logs:

[bugsnag] Event failed to send… Error: Request failed with status 0

**Comment by CulturalProfessor** [comment]
> I guess there is issue with your internet connection, coz when I'm opening this into my safari browser its working perfectly fine.

I guess it's a browser issue as it's working fine in brave , can you check in firefox?

**Comment by lovekyleman** [comment]
Same issue on iOS app latest version

**Comment by MatiasPenna** [comment]
Exactly the same thing is happening to me, do you know what it could be or how I can fix it? My Rocket.Chat would be for internal use, but it still doesn't load.

![image](https://github.com/RocketChat/Rocket.Chat/assets/64233385/97daab33-5b1e-4565-ab1f-92ea94a4b9fe)

**Comment by rasmniel** [comment]
I have the same issue

Nothing happens. Just a loading spinner forever.
Restarted machine and reinstalled Rocket.Chat app without any luck.

![image](https://github.com/RocketChat/Rocket.Chat/assets/11680653/5dc7f908-2cd9-4973-b100-cd61cebe3ffe)

I get this console output.
```
[Rocket.Chat Desktop] waiting for window load
meteor_runtime_config.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
client_environment.js:1 Uncaught ReferenceError: __meteor_runtime_config__ is not defined
    at client_environment.js:1:1
    at client_environment.js:78:1
    at url_common.js:80:1
preload.ts:28 [Rocket.Chat Desktop] preload.ts start
preload.ts:32 [Rocket.Chat Desktop] preload.ts serverUrl is not defined
```

As expected, the network tab shows a single red line, 404 for this file: `/meteor_runtime_config.js`

All my colleagues have similar machines to me and they have no issue booting the app or accessing the chat space. It literally just stopped working for me overnight, as my computer rebooted for a Windows Update. Naturally, I am not going to start fiddling with Windows Update or Windows versions in order for the Rocket.Chat app to work.

The web app has the same behaviour, for my colleagues as the app does for me, hinting that new sessions cannot be created while old ones still work, so maybe the app itself isn't the problem.
I hope you can use this info to fix the problem.

**Comment by rasmniel** [comment]
I found found a workaround to solve my issue by using the action "view -> clear ignoring cache", whatever that means.

**Comment by dexhek** [comment]
Another workaround to solve the issue is "Clear trusted certificates" under the tab help, on the menu. 
I dont know if its a permanent fix tho...

**Comment by LvckyAPI** [comment]
I had this issue after updating Rocket.Chat to v6.4.2 AND v6.4.3.
Reinstall the desktop-app can fix the problem, but this can't be the way of going.

The desktop-app is loading the workspace, and you can see something for 1 second.
Then it reloads in an endless loop.

**The workspace can be loaded too, after reload using `View` -> `Reload ignoring cache`**



Desktop-App version 3.3.9 on Ubuntu 22.04.3 LTS x86_64.

```
            .-/+oossssoo+/-.               
        `:+ssssssssssssssssss+:`           ----------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 21AB001VGE ThinkPad L13 Gen 2a 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.2.0-35-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 22 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2212 (dpkg), 51 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.9 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-purple-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-purple [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics (16) @ 1.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI 07:00.0 Cezanne 
      -+sssssssssssssssssyyyssss+-         Memory: 5547MiB / 14796MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   

```

**Comment by kim2048** [comment]
I deleted cookies and data in Firefox and now the reload issue is gone \o/

**Comment by CulturalProfessor** [comment]
Yeah mine is also working now , but I didn't deleted any cookies :thinking:

**Comment by drj3ky11** [comment]
I have the same issue, and not solvet at all....

**Comment by LvckyAPI** [comment]
> I have the same issue, and not solvet at all....

Do you've tried the workarounds above?

**Comment by drj3ky11** [comment]
> > I have the same issue, and not solvet at all....
> 
> 
> 
> Do you've tried the workarounds above?


Yes. On docker everything seams ok; but workspace never load. Also I have try other different docker images (older ones).

**Comment by CulturalProfessor** [comment]
This error popped up again and clearing cookies solved it, this seems like only workaround for now.

**Comment by ankar84** [comment]
We have something similar - some clients looks like continuously reloading - their statuses are changing from offline to online every few seconds.  @shirev have details.

**Comment by kim2048** [comment]
I had to delete the cookies today again (was working for one week).

**Comment by paulchen** [comment]
This is a really annoying problem. For some of the users on my server, this happens reliably with each update. Whenever this happens, they are only able to make this stop by deleting cookies.

In the meantime, I also observed this behaviour in Google Chrome as well as in the Electron client, so this is not limited to Firefox.

**Comment by LvckyAPI** [comment]
> This is a really annoying problem. For some of the users on my server, this happens reliably with each update. Whenever this happens, they are only able to make this stop by deleting cookies.
> 
> In the meantime, I also observed this behaviour in Google Chrome as well as in the Electron client, so this is not limited to Firefox.

And reloading without cache is not a option?

**Comment by paulchen** [comment]
> > This is a really annoying problem. For some of the users on my server, this happens reliably with each update. Whenever this happens, they are only able to make this stop by deleting cookies.
> > In the meantime, I also observed this behaviour in Google Chrome as well as in the Electron client, so this is not limited to Firefox.
> 
> And reloading without cache is not a option?

No, unfortunately, for some reason that seems to not help resolving the problem.

**Comment by andyman365** [comment]
We have the same issue. Eeloading without cache does work for us for a short peiod of time. But then it happens again.

**Comment by btafoya** [comment]
Has impacted all of my clients and my own instance. Clearing the cache seems to be the resolution in the meantime.

**Comment by da-avidid** [comment]
Our team is experiencing the same issue as well.

Operating System: Mix of Windows (10/11) and Ubuntu (22.04) machines.
App Version: 6.4.5
Installation type: Snap install (Ubuntu 22.04)


This "constant refresh" affects both the Desktop Application as well as the Webapp (Firefox/Brave/Edge).

Workarounds:
1. The "clear cache and server refresh" does fix the issue temporarily but the problem comes back.

2. If using the browser, sometimes clicking the refresh button manually fixes the issue temporarily as well. 

3. For Windows machines sometimes we had to remove the cache manually, this worked for us YMMV:
C:\ > Users  > $USER > Appdata (you may need to enable 'show hidden files') > Local || Roaming (Depending on version) > Rocket.Chat > Delete all except the config.json

Hopefully, this helps other users while we wait for a permanent fix.

**Comment by gromfaus** [comment]
I see the same problems for all users. Version 6.4.5

**Comment by florisvangeel** [comment]
{sortof} Fixed by passing environment variable, without the need to clear client caches:
```
METEOR_SETTINGS='{"public": {"packages": {"dynamic-import": {"useLocationOrigin": true}}}}'
```
source: https://open.rocket.chat/channel/support?msg=R5gQss4Tdm8xWEXZP

**Comment by ggazzo** [comment]
it should be closed by https://github.com/RocketChat/Rocket.Chat/pull/35466

while the reload still happens, it does not reload instantly, giving some time for deploys to "accommodate"
