### ISSUE TITLE
activation a Starter license fails with "Period validation failed"

### ISSUE THREAD

**Issue by individual-it** [RocketChat/Rocket.Chat#33233]
### Description:

Starter License does not have correct period and cannot be used

### Steps to reproduce:

1. Use an existing server with 20 seats and 1 App
2. On https://cloud.rocket.chat/ delete all subscriptions
3. restart server
4. register server
5. verify the registration
6. check the logs

### Expected behavior:

No error message should be shown, enterprise functionalities (like matrix federation) should work

### Actual behavior:

1. Error in the logs
2. when trying to use matrix federation, the server completely stops working
3. In the workspace admin console the subscription is shown as "community"
    ![grafik](https://github.com/user-attachments/assets/ff260672-b438-4e31-b460-e600eeab0a97)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.0
- License Type: Should be Starter
- Number of Users: 20
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3 - x64 
- MongoDB Version: 5.0.28    

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Ubuntu

### Additional context

I'm trying to get matrix federation working with the Starter license, on an existing server but fail to get a valid license.
Ether there is a bug or I misunderstand the Starter license 

adding `REG_TOKEN` env. variable did not change anything

### Relevant logs:
```
rocketchat-1  | {"level":50,"time":"2024-09-09T08:40:33.425Z","pid":7,"hostname":"fd4793b8a95f","name":"System","msg":"Server has been unregistered from cloud"}
rocketchat-1  | {"level":50,"time":"2024-09-09T08:41:34.953Z","pid":7,"hostname":"fd4793b8a95f","name":"License","msg":"Period validation failed","period":{"validUntil":"0001-01-01T00:00:00Z","invalidBehavior":"invalidate_license"}}
```

**Comment by reetp** [comment]
Likely a duplicate of 

https://github.com/RocketChat/Rocket.Chat/issues/33222

**Comment by reetp** [comment]
Leaving this open for now - this is under investigation.

**Comment by individual-it** [comment]
I also tried to go back to 6.11.0 but without luck

**Comment by scuciatto** [comment]
@individual-it : can you please try syncing again? We had an issue earlier today but it is now fixed

**Comment by individual-it** [comment]
@scuciatto it seems to work now, thank you. The subscription is shown correctly now, next I will see if I can get federation with Matrix going
![grafik](https://github.com/user-attachments/assets/aa20d421-6242-43c1-ae69-3664cbad12c0)

But FYI: this morning (nepali time) I could not login to the server and had to restart it first.
The logs showed this:
```
rocketchat-1  | {"level":50,"time":"2024-09-09T12:00:20.258Z","pid":7,"hostname":"fd4793b8a95f","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts:46:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}}
rocketchat-1  | {"level":40,"time":"2024-09-09T15:32:33.236Z","pid":7,"hostname":"fd4793b8a95f","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}
rocketchat-1  | {"level":40,"time":"2024-09-09T17:22:27.425Z","pid":7,"hostname":"fd4793b8a95f","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}
rocketchat-1  | {"level":50,"time":"2024-09-10T00:00:20.204Z","pid":7,"hostname":"fd4793b8a95f","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts:46:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}}
```

`"Failed to communicate with Rocket.Chat Cloud"` does that mean that if our server cannot reach yours, it will stop working?

**Comment by individual-it** [comment]
cannot get the matrix federation to work. Maybe I still have a license issue
Setting the log-level to ` 2 - Errors, Information and Debug` I see this:

```
rocketchat-1  | {"level":30,"time":"2024-09-10T07:43:27.492Z","pid":9,"hostname":"518a81af2ee7","name":"License","msg":"New Enterprise License"}
rocketchat-1  | {"level":20,"time":"2024-09-10T07:43:27.495Z","pid":9,"hostname":"518a81af2ee7","name":"License","msg":"license","decrypted":{"version":"3.0","information":{"id":"66deb4be9470ef992d39736a","autoRenew":true,"createdAt":"2024-09-10T07:30:42.270845642Z","visualExpiration":null,"notifyAdminsAt":null,"notifyUsersAt":null,"trial":false,"cancellable":true,"offline":false,"grantedBy":{},"grantedTo":{},"tags":[{"name":"Starter","color":"#F3BE08"}]},"validation":{"serverUrls":[{"value":"chat.jankari.tech:8443","type":"url"}],"cloudWorkspaceId":"66deb4bb71974379ff4c3056","serverUniqueId":"ng5Nm9vAtqjXR6fGq","validPeriods":[{"validUntil":"2024-09-30T07:30:42.270839193Z","invalidBehavior":"invalidate_license"}],"legalTextAgreement":{"type":"required","acceptedVia":"cloud"},"statisticsReport":{"required":true,"allowedStaleInDays":2}},"grantedModules":[{"module":"canned-responses"},{"module":"ldap-enterprise"},{"module":"livechat-enterprise"},{"module":"voip-enterprise"},{"module":"omnichannel-mobile-enterprise"},{"module":"engagement-dashboard"},{"module":"push-privacy"},{"module":"teams-mention"},{"module":"saml-enterprise"},{"module":"oauth-enterprise"},{"module":"federation"},{"module":"videoconference-enterprise"},{"module":"message-read-receipt"},{"module":"outlook-calendar"}],"limits":{"activeUsers":[{"max":25,"behavior":"start_fair_policy"},{"max":26,"behavior":"prevent_action"}],"guestUsers":[{"max":0,"behavior":"start_fair_policy"},{"max":0,"behavior":"prevent_action"}],"roomsPerGuest":[{"max":0,"behavior":"start_fair_policy"},{"max":0,"behavior":"prevent_action"}],"monthlyActiveContacts":[{"max":100,"behavior":"start_fair_policy"},{"max":101,"behavior":"prevent_action"}]},"cloudMeta":{}}}
rocketchat-1  | {"level":30,"time":"2024-09-10T07:43:27.499Z","pid":9,"hostname":"518a81af2ee7","name":"License","msg":"Limit validation failed","kind":"roomsPerGuest","limit":{"max":0,"behavior":"start_fair_policy"}}
rocketchat-1  | {"level":30,"time":"2024-09-10T07:43:27.528Z","pid":9,"hostname":"518a81af2ee7","name":"License","msg":"Limit validation failed","kind":"guestUsers","limit":{"max":0,"behavior":"start_fair_policy"}}
```

Specially the least two messages make me think that there is still something strange going on.
We don't have a single `guestUser` in our system. At least if I filter by `guest` in the Users list, I get `No Users found.`

**Comment by reetp** [comment]
> cannot get the matrix federation to work. Maybe I still have a license issue


This is probably unrelated.

Please don't merge different issues.

Your Matrix bug is here?

https://github.com/RocketChat/Rocket.Chat/issues/33240

This bug should be closed.

**Comment by individual-it** [comment]
Yes I think this is solved, thank you
