### ISSUE TITLE
fix(Integration): Incoming webhook 'Emoji filed 'has no validation

### ISSUE THREAD

**Issue by MrKalyanKing** [RocketChat/Rocket.Chat#37451]
### Description:

When Creating a new incoming webhook  the Emoji Filed dosent have proper validation ex:[ ghost ] it will taking this as emoji field . but under the text box clearly mentioned that it should start and end with colon 

### Steps to reproduce:

1.Navigate the Adminstration click on the Integration
2. click on the new tab 
3. select the Incoming tab  
4. Fill in all required fields (e.g., Name: Test Emoji, Post to Channel: #general, Post as: Kalyan12).
5. Scroll down to the "Avatar URL" field.
6.Type an invalid string that is not a Emoji type string (e.g., ghost ).
7.click on save button

### Expected behavior:

If the user tries to fill the Emoji field .The form should not be save. Because the value provided, should not be validated .It should throw an error should appear like "please enter an valid emoji name"

### Actual behavior:

The form saves successfully with the invalid string in the "Emoji String" field. A green "Integration has been saved" toast message appears, and the integration is created with a broken Emoji String.

### Server Setup Information:

- Version of Rocket.Chat Server: develop(running in local development
- License Type:community
- Number of Users: 1
- Operating System: ubuntu(via WSL)
- NodeJS Version: 22.16.0
- MongoDB Version:6.10.0

### Client Setup Information

- Desktop App or Browser Version:chrome(latest)
- Operating System:Windows

### Relevant logs:

No server or console logs are generated because the application incorrectly treats this as a successful operation. The bug is the absence of a validation error.

**Comment by sdv96** [comment]
IS THIS ISSUE SOLVED I CAN IMPROVE IT By..... if @MrKalyanKing  approves assign within 1 WEEKS {WORKING NOW}

**Comment by MrKalyanKing** [comment]
It is already fixed

**Comment by reetp** [comment]
> It is already fixed

It isn't fixed - you have just added a PR which will get no attention because you have not asked about it on open.

Please do as requested multiple times. Ask first and don't waste your own time - you will just end up frustrated.

Thanks.

**Comment by Heyy-Himanshuu** [comment]
I'd like to take this up . can you please assign it to me ?
