### ISSUE TITLE
[support] The autolinker does not decode HTML tags

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#4199]
Your Rocket.Chat version: 0.38

For example - the url http://www.zerohedge.com/news/2016-07-24/nintendo-crashing-most-2000-after-admitting-limited-earnings-impact-pokemon-go shows preview as:

![image](https://cloud.githubusercontent.com/assets/16319433/18247930/3427872a-737e-11e6-9086-fb8b94941db2.png)

The host machine have the environment setting **LANG=en_US.UTF-8**

The previous release 0.32 was ok, but 0.36, 0.37, 0.38 have this problem.

**Comment by lunitic** [comment]
Have the same issue in 0.36

**Comment by zxweed** [comment]
The 0.39 release has the same problem. Any help, please?

**Comment by zxweed** [comment]
I have tried to change the locale to single-byte from UTF, but nothing changes..

**Comment by MartinSchoeler** [comment]
I'm pretty sure that was fixed 
<img width="704" alt="screen shot 2017-07-17 at 1 37 57 pm" src="https://user-images.githubusercontent.com/20868078/28278970-5873b760-6af5-11e7-9b7c-ce2eb9ee1822.png">

if not please reopen this.
Thanks!

**Comment by zxweed** [comment]
I have upgrade and checked the last version - 0.59.3, the problem still exists

**Comment by zxweed** [comment]
![image](https://user-images.githubusercontent.com/16319433/34391243-7770451c-eb55-11e7-8349-a4358f7a99df.png)
