### ISSUE TITLE
Users when log out, they still show under online

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5562]
I noticed when user logout, their name come to the bottom of the online list and then once i refresh page they disappear..

Your Rocket.Chat version: (0.49.0)
![image](https://cloud.githubusercontent.com/assets/12454319/21934590/f725e442-d977-11e6-9d96-e267213664a0.png)

**Comment by engelgabriel** [comment]
We must also update the list with the join channel message so it shows the new users when they join

**Comment by IQ2022** [comment]
![image](https://cloud.githubusercontent.com/assets/12454319/21955435/316b44f0-da39-11e6-843c-ec55c7c781ea.png)

**Comment by IQ2022** [comment]
this is still an issue, now user count doesn't update at all - I have to refresh page to get the actual total users logged in

Running 50.1

**Comment by IQ2022** [comment]
am on release 51.0 and this issue hasn't been resolved?  right now am using refresh page to get the actual count

**Comment by IQ2022** [comment]
upgraded to release 52.0 issue still exist.. i think its important to have this fixed, sometime I see users typing and before their status shows online and vice versa...

**Comment by cyclops24** [comment]
Part of #8175

**Comment by Hudell** [comment]
It is still an issue.

**Comment by Hudell** [comment]
According to @ggazzo it also doesn't show users who become online after the list is opened.

**Comment by ggazzo** [comment]
this list is not reactive, we use a method instead a subscription, actually I dont like this method `getUsersOfRoom`... we will find a better way... but its not a "bug" its how we implemented =/

**Comment by subham103** [comment]
I have verified, this issue still persists.

When a user comes online (or goes offline), the color of the small dot changes, but it doesn't come to the top of the list (or goes from the top of the list if offline). I think I can solve this issue by calling the function responsible for the reshuffling of the user list in the function which is responsible for color change upon activation of a user.

I want to work on this issue:)
