### ISSUE TITLE
Error: OpLog (ReplicaSet) should be enabled when running multiple instances

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#5665]
Your Rocket.Chat version: 0.49.3

Hello Devs. I get "Error: OpLog (ReplicaSet) should be enabled when running multiple instances" after upgrading to 0.49.3 on info page. Should i be worried? 

![bildschirmfoto 2017-01-19 um 08 47 46](https://cloud.githubusercontent.com/assets/631865/22097945/0b781806-de24-11e6-81d2-8977add4d660.png)

**Comment by himbeere** [comment]
Oh. For your information. There is only one instance running currently.

**Comment by elfrinjo** [comment]
In my case, this vanished after a the first restart of mongo and rocketchat.

**Comment by himbeere** [comment]
Just tried on my test machine. You are right. One have to restart mongodb. But i think this still qualifies as bug, no?

thanks and cheers

**Comment by Mte90** [comment]
I confirm the problem but after a reload of mongo and rocketchat I continue to have that error.
I used `service stop mongod` and start. Any suggestions?

**Comment by himbeere** [comment]
I had to try a few times start and stop mongodb and rocketchat. At some point the error eventually disappeared.

**Comment by Mte90** [comment]
I done twice, before killing the process and next with the service. 
It was a process running from 70 days was a big unpleasure command :-(

**Comment by graywolf336** [comment]
@rodrigok

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/commit/3217739a9d5a5a6c02c9186dd0d99af3c37a4c84 was meant to improve this.

**Comment by engelgabriel** [comment]
FYI, is you DO have more than 1 instance, yes, you MUST have OpLog configured.

The issue is that when you restart the instance, it takes a while to detected that the previews instance is actually gone, so it shows 2... we fixed that for the next version.

**Comment by djschilling** [comment]
I am using Rocket.Chat Version 0.54.2 and i'm still getting this bug.

After upgrading from 0.53 to 0.54.2 and restarting Rocket.Chat the Error `Error: OpLog (ReplicaSet) should be enabled when running multiple instances` appears.
I have only one instance running.

**Comment by justechn** [comment]
I just installed 0.55.1 and I am seeing this issue
