### ISSUE TITLE
Upgrade from emojione v2 to emojione v3

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6740]
https://github.com/Ranks/emojione/blob/master/UPGRADE.md

Refactor to avoid having to run the compile script manually on updates.

**Comment by sampaiodiego** [comment]
SVGs are now at premium license :disappointed:

**Comment by engelgabriel** [comment]
Maybe we should use the npm module directly, to try to fix https://github.com/AdmitHub/meteor-buildpack-horse/issues/169

**Comment by engelgabriel** [comment]
Related Issues that could be all solved by this:
https://github.com/AdmitHub/meteor-buildpack-horse/issues/169
https://github.com/RocketChat/meteor-buildpack-horse/issues/10
https://github.com/RocketChat/Rocket.Chat/issues/6444
https://github.com/RocketChat/Rocket.Chat/issues/6613

**Comment by pojoba02** [comment]
Hey Guys, is the emojione issue resolved cos is still not working at my end.

**Comment by danielbahl** [comment]
Emojione SVGs are now requiring a premium license. 
Alternative open emoji package: https://github.com/eosrei/twemoji-color-font

**Comment by fifou17** [comment]
i will try to work on it

**Comment by sampaiodiego** [comment]
thanks @fifou17 .. but unfortunately current emojione versions doesn't allow embedding on open source projects.

if you want to take a look, we're considering adding https://github.com/twitter/twemoji as a replace for emojione

**Comment by fifou17** [comment]
sure i will take a look @sampaiodiego
