### ISSUE TITLE
[Livechat] exception while `sendMessageLivechat` called

### ISSUE THREAD

**Issue by legendecas** [RocketChat/Rocket.Chat#7147]
Rocket.Chat Version: 0.57.0-develop
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.8.1 - x64

Method calls and responses flow as follows.
```
sending:  {
  "msg": "method",
  "method": "livechat:registerGuest",
  "params": [
    {
      "token": "NLpurdwP4wxon",
      "name": "Tony Hawkins",
      "email": "mukhiga@jepileawu.ni",
      "department": "s5zATNW3msGM5E8c5"
    }
  ],
  "id": "1"
}
response:  {
  "msg": "result",
  "id": "1",
  "result": {
    "userId": "6FrmEm7XP8LdAimoi",
    "token": "fHZYN8dsJSnCEtTDRYEPFDMnwGj_2d-LkIz26dxgDVi"
  }
}
sending:  {
  "msg": "method",
  "method": "login",
  "params": [
    {
      "resume": "fHZYN8dsJSnCEtTDRYEPFDMnwGj_2d-LkIz26dxgDVi"
    }
  ],
  "id": "2"
}
response:  {
  "msg": "result",
  "id": "2",
  "result": {
    "id": "6FrmEm7XP8LdAimoi",
    "token": "fHZYN8dsJSnCEtTDRYEPFDMnwGj_2d-LkIz26dxgDVi",
    "tokenExpires": {
      "$date": 1504102789065
    }
  }
}
sending:  {
  "msg": "method",
  "method": "sendMessageLivechat",
  "params": [
    {
      "_id": "LRQaNr^",
      "rid": "#Ou%$PqtU@",
      "msg": "Vuufavan tefabuem zofbizen lufninji copunufu.",
      "token": "NLpurdwP4wxon"
    }
  ],
  "id": "3"
}
response:  {
  "msg": "result",
  "id": "3",
  "error": {
    "error": 500,
    "reason": "Internal server error",
    "message": "Internal server error [500]",
    "errorType": "Meteor.Error"
  }
}
```

Server logs
```
Exception while invoking method 'sendMessageLivechat' TypeError: Cannot read property 'length' of undefined
  at Object.RocketChat.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:3091:38)
  at Object.RocketChat.Livechat.sendMessage (/app/bundle/programs/server/packages/rocketchat_livechat.js:3259:30)
  at [object Object].Meteor.methods.sendMessageLivechat (/app/bundle/programs/server/packages/rocketchat_livechat.js:1118:30)
  at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1021:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)
  at /app/bundle/programs/server/packages/ddp-server.js:905:20
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:904:41
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:903:46
  at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)
  at /app/bundle/programs/server/packages/ddp-server.js:755:85
```

**Comment by legendecas** [comment]
Also errored with the same exception while using embeddable HTML scripts.

**Comment by sampaiodiego** [comment]
this should have been fixed by https://github.com/RocketChat/Rocket.Chat/pull/7096 

can you please update your instance and test it? thanks

**Comment by legendecas** [comment]
@sampaiodiego I'm using latest `develop` Docker image. Looks like the problem still exists for every first livechat message of a guest, the second message and follows will be delivered successfully.

**Comment by sampaiodiego** [comment]
@legendecas our `develop` docker image is now fixed, you can pull it and test it again..

**Comment by legendecas** [comment]
@sampaiodiego yes it's fixed.
