### ISSUE TITLE
Option to enable/disable auto away and configure timer

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#736]
Rocket.Chat keeps user status as `Online` only if user is actively using chat window or if chat window is hovered via mouse. 

Otherwise, user status falls onto `Away`...
##

**Comment by rodrigok** [comment]
What is the expected behaviour?

**Comment by rockneverdies55** [comment]
User status shouldn't be determined based on the interaction with the chat window.

User is online as long as she/he's logged in to rocket.chat and doing something on the computer. No activity with OS at all for a predefined time (can be set by Admins) should make user Away.

**Comment by Maysora** [comment]
probably should add an option to enable/disable auto away?

**Comment by rodrigok** [comment]
I don't know if we can detect OS inactivity inside the browser.

The auto away is useful to send mentions via push notification.

**Comment by geekgonecrazy** [comment]
maybe an option to choose how long before auto away.  The only place this is really going to be possible is in Electron

**Comment by jclabaugh** [comment]
maybe 'Set to Away status in [  ] minutes' defaulting to 10 min.

**Comment by geekgonecrazy** [comment]
agreed :+1:

**Comment by jclabaugh** [comment]
might check out https://atmospherejs.com/dpid/user-presence for inspiration (advanced settings stuff)?  Since the app is browser-based, it is harder than Slack's desktop client to set user presence accurately but there might be a cludge idea somewhere that gets you closer to replicating that by adding a user-defined delay period.

We have had UX issues currently with people going "I'm at my computer, I am just not typing in the app right this sec, why is it setting me to 'away' already?"

**Comment by jclabaugh** [comment]
I think Slack actually does a non-standard implementation of user presence, contrary to the likes of Skype or any IM client... If the app is open, you are 'online', regardless of any of your activity in the app. If the app is not open or your computer is asleep/off, you are 'offline.' You say you are 'away' by manually setting your status by clicking 'Set yourself away'. So its detecting a binary presence state, kind of.

**Comment by geekgonecrazy** [comment]
https://developers.google.com/web/updates/2015/08/27/using-requestidlecallback

Ran across this during my perusing of the interwebs.  Looks like it might be of use here.

**Comment by gmsecrieru** [comment]
[ifvisible.js](https://github.com/serkanyersen/ifvisible.js) looks interesting, do you folks think it could be of any use?

**Comment by klatys** [comment]
+1 on this. This also causes sending mobile notifications eventhough you are active on a computer (but not in RC window) which is quite annoying.

I found [Robot.js's getMousePos](https://github.com/octalmage/robotjs/wiki/Syntax#getmousepos) which could check/detect mouse position change. Detecting keypresses is (for obvious reasons) probably an issue, but if there wasn't any other way. Mouse might at least partially fix this...

I'm not really fluent with electron, but was wondering - if it was somehow working the same way the cordova does then maybe some sort of plugin might do the trick...

**Comment by joergludwig** [comment]
We switched to Rocket.Chat for communication in our company. Every user runs the desktop app on his computer. It would be very useful if we could see, who is working at his computer and who is not at his desk. In the past we used Pidgin with an XMPP server, which did this well.

Rocket.Chat should switch a user to "away", if he does not move the mouse for 5 minutes, and switch back to "online", as soon as he is active again. If Rocket.Chat could detect, if the screen is locked, this would work as well.

**Comment by freddy70** [comment]
Hi all
I'm in the same situation and I  have the same need as joergludwig.
I installed the desktop app on several computers in my company. I would like to have a "green" status when user is working on his computer and "orange" status when user stop moving his mouse or screen locked. Do you know if this feature will be implemented ?
Thanks a lot for your feedback.

**Comment by StealthMicro** [comment]
+1

**Comment by klatys** [comment]
Hi, like I suggested earlier, I tried tinkering with [robot.js](https://github.com/octalmage/robotjs), since it's for a electron apps (or if I get it correctly requires actual app - means it won't work in browser) I used it in [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) and it seems to work:
![inactive window logging mouse pos](http://g.recordit.co/bAESrAYyXN.gif)
Now I'm not that fluent in how the client works with rocket.chat instance, I suppose it might send some sort of info regarding user status to server which would process that. Could someone from @RocketChatApp point me in the right direction?

**Comment by jerrylanejohns** [comment]
+1 Need this very badly to make chat more useful in business environment.

**Comment by armand1m** [comment]
I've started working on this issue, but I've seen many references to these packages in the application exposed as an `UserPresence` global variable:

https://atmospherejs.com/konecty/user-presence
https://github.com/Konecty/meteor-user-presence

I guess this is being used only in the cordova client for when the application goes to background, right?

**Comment by armand1m** [comment]
Hi, I've started implementing this feature, but I'm in doubt in certain situations:

This feature involves not only the actual online/away user but the whole team that this user belongs, so I'm in doubt if this must be in the "My Account" preferences for each user to configure its own Idle Time Limit, or in another place.

![screenshot_27](https://user-images.githubusercontent.com/6154901/29999104-46ea22e4-9012-11e7-961f-69dad41ec713.png)

For me, it should be configured per User in the "My Account" preferences.

**Comment by armand1m** [comment]
For now, I'm not willing to change the way Rocket Chat handles User Presence, I'm just creating the option to enable the auto away and change the Idle Time Limit if enabled.

**Comment by armand1m** [comment]
Hey, I've updated the PR #8029.

Know the tests are all passing, and we have the feature implemented in 4 languages:

- English (default)
![captura de tela 2017-12-04 as 23 04 00](https://user-images.githubusercontent.com/6154901/33587513-9cb2f354-d955-11e7-8be3-d12ae77f07e8.png)

- Portuguese
![captura de tela 2017-12-04 as 23 04 12](https://user-images.githubusercontent.com/6154901/33587493-8792db9c-d955-11e7-9707-9b6264215859.png)

- Brazilian Portuguese
![captura de tela 2017-12-05 as 00 42 34](https://user-images.githubusercontent.com/6154901/33587474-71d35570-d955-11e7-899c-cdff9006f988.png)

- Dutch (Nederlands)
![captura de tela 2017-12-05 as 00 42 23](https://user-images.githubusercontent.com/6154901/33587476-7747a8ee-d955-11e7-9091-9d067185eaa4.png)

Here is a GIF demonstrating the feature.

![enableautoaway](https://user-images.githubusercontent.com/6154901/33587771-bef6c020-d956-11e7-97fa-f2ab507be75f.gif)

**Comment by joergludwig** [comment]
Thank you for your work. Unfortunately I think, the actual problem is not solved:

> rockneverdies55 commented on 8 Sep 2015
> User status shouldn't be determined based on the interaction with the chat window.
> User is online as long as she/he's logged in to rocket.chat and doing something on the computer. No activity with OS at all for a predefined time (can be set by Admins) should make user Away.

**Comment by rodrigok** [comment]
@joergludwig Unfortunately there is no way to get the OS activity from inside the browser.

**Comment by armand1m** [comment]
@joergludwig can you be more clear? you just copy pasted the message from @rockneverdies55 but didn't explained anything at all. If you want me to detect no activity with OS at all, I must say that I'm sorry because this is actually impossible without a chrome extension or something like that. But the PR was merged, the issue was closed and the desired functionality was delivered, I think I deserve the bounty. If you want to know if the user is interacting with the OS, I would recommend you to use another kind of monitoring tool in your company such as Hubstaff.

**Comment by armand1m** [comment]
@joergludwig I've also asked for some feedback before starting to implement this feature, and no one even took the time to respond to some of my questions before I took the liberty to make the decisions about this feature myself. I think it is really not fair.

**Comment by rodrigok** [comment]
@armand1m Your solution was a good solution, thanks.

@joergludwig We already have some improvements to get the OS activity when using the Desktop/Electron app, we can improve, please open an issue at https://github.com/RocketChat/Rocket.Chat.Electron/issues if you have suggestions.

Thank you guys.

**Comment by armand1m** [comment]
@joergludwig can you accept the claim in the bountysource please?

**Comment by joergludwig** [comment]
Sorry for the misunderstanding. I thought this issue was about detecting OS activity. We only use the desktop and mobile apps. I was not aware that there are different issue trackers for browser and app usage.

I accepted your claim in bountysource anyway to support further development of Rocket Chat.

**Comment by armand1m** [comment]
thanks @joergludwig  🙂 

@engelgabriel can you take a look and accept the bounty? :smile:
