### ISSUE TITLE
RocketChat doesn't load properly in Safari 8

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7699]
Version 0.57.2

It can't handle the "calc" in the height style of the message box 

Here's what users see:
![image](https://user-images.githubusercontent.com/23452628/29125679-11daeffc-7d25-11e7-9e3a-461d894dff11.png)

**Comment by sampaiodiego** [comment]
@danieljhochman can you please verify if this is the same issue as https://github.com/RocketChat/Rocket.Chat/issues/7574? it was already fixed on `release-candidate` branch.

**Comment by danieljhochman** [comment]
@sampaiodiego looks the same. Sorry, we only searched open issues. We will search closed issues next time as well :)

**Comment by MartinSchoeler** [comment]
fixed by #7621

**Comment by danischreiber** [comment]
@RamonNobre this is still not working. You can reproduce by opening the release-candidate branch in Safari 8.

**Comment by Sing-Li** [comment]
Not working.  Per test by  @danischreiber.

**Comment by sampaiodiego** [comment]
the #7621 fix was for latest safari versions.. I'll need to discuss with the team if we will support older versions of safari, which we don't for now.
