### ISSUE TITLE
Subscriptions aren't removed when a room is deleted

### ISSUE THREAD

**Issue by Fazil93** [RocketChat/Rocket.Chat#7709]
* Version of Rocket.Chat Server: 0.57.3
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc): none
* Number of Running Instances: 1
* DB Replicaset Oplog:  enabled
* Node Version: 4.8.0

deleting room general or any other room it doesnt not delete its subscription and same for users its give empty room subscription error

**Comment by juice99** [comment]
I confirm, i have the same problem. It's quite annoying since it writes this error to syslog every few minutes or so:
Sep  1 12:36:47 vps nodejs[1695]: Empty Room for Subscription { _id: 'T2b[...]',
Sep  1 12:36:47 vps nodejs[1695]:   rid: '6Y8E[...]',

**Comment by Hudell** [comment]
#10700 changed it so that subscriptions and DMs are deleted with an user, I'll update the description to reflect the new state.

**Comment by geekgonecrazy** [comment]
Should be fixed by the before mentioned PR.  Closing

**Comment by Hudell** [comment]
That PR handles user deletion, but the subscription is still not removed when the room is deleted.

**Comment by geekgonecrazy** [comment]
Ah! Good catch!  👍

**Comment by ggazzo** [comment]
Fixed
