### ISSUE TITLE
[BUG] [UI] Scrollbar new design breaks in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8223]
Hi @ggazzo ,
Scrollbar new design breaks in RTL. (after #8190 ) It's automatically hide and convert to horizontal scrollbar when I try to drag it or use mouse scroll button. See this:
![15](https://user-images.githubusercontent.com/8266479/30650902-57fd257e-9e39-11e7-8d57-11cb03823c13.gif)

**/CC:** @karlprieb , @rodrigok

**Comment by cyclops24** [comment]
Also in messages area:
![18](https://user-images.githubusercontent.com/8266479/30653274-e54b6390-9e3f-11e7-9e34-26053466d563.gif)

**Comment by engelgabriel** [comment]
This is still a bug, we just have temporarily removed the functionality.

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175

**Comment by gdelavald** [comment]
This was fixed in the latest RC.

**Comment by cyclops24** [comment]
@gdelavald it's still show previous style scrollbar.
Can you mention witch PR fixed this? :thinking: 

**/CC:** @engelgabriel

**Comment by cyclops24** [comment]
Part of #8494

**Comment by cyclops24** [comment]
@gdelavald @engelgabriel it's not fixed yet.

**Comment by mnlbox** [comment]
@gdelavald @engelgabriel any news about this old issue?

**Comment by karlprieb** [comment]
@mnlbox I tested on our `develop` branch and this bug doesn't happen anymore.
