### ISSUE TITLE
replacement with internal data in code block

### ISSUE THREAD

**Issue by neurolabs** [RocketChat/Rocket.Chat#8640]
### Description:

When sending a message with specific content inside a code block, Rocketchat replaces the content of the code block with something looking like internal state.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Debian GNU/Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. paste a message containing a specific code block
```
`\(.*\)`
```

### Expected behavior:

Rocketchat displays the given message formatted as code

### Actual behavior:

Rocketchat substitutes the content of the code block with internal data, e.g.:
```
=!=kCFKHzxbbR9nm8KHW=!=
```
When editing the message, it shows the original message. When resubmitting the edited message, the substitution contains a different string. Via WebSocket, the original message is sent.

**Comment by thinkeridea** [comment]
I find that the latest edition has been solved, and it should be closed to inform all the people concerned.  version:0.62.2

**Comment by DLAtWork** [comment]
Using the snap of 0.69.2 on Ubuntu 18.04 .1 we've found this is NOT fixed.

The following string breaks chat:
`ls -1 /boot/vmlinuz-* | sed -n -e 's/.*\/vmlinuz-\(.*\)\(\.el[0-9]\..*\)/\1 \2/p' | sort -t' ' -k1V | tr -d ' '`

We get the following error whether using triple backticks, single backticks, or just regular chat:
```
ls -1 /boot/vmlinuz-* | sed -n -e 's/.*\/vmlinuz-.∗.*.∗KaTeX parse error: Can't use function '\.' in math mode at position 1: \̲.̲el[0-9]\..*
/\1 \2/p' | sort -t' ' -k1V | tr -d ' '
```

**Comment by neurolabs** [comment]
@DLAtWork Your issue most probably is a new issue. I would file a new report for that one.

**Comment by neurolabs** [comment]
And @MartinSchoeler don't you think this issue can be closed?
