### ISSUE TITLE
Since http://rocket.chat/images/mockup.png is not available all newly saved Incoming Integrations are broken

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#8766]
### Description:
Hey guys, it seems like all integrations which have been saved after the URL http://rocket.chat/images/mockup.png throws a 404 error are broken with the error. Even tho I only want to fire a console.log("").
```
TypeError
Cannot read property 'importSync' of undefined
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: ON
* Node Version: 4.5.0

### Steps to Reproduce:

1. Add a new integration
2. Enable Script
3. Write some valid code
4. click on safe

### Expected behavior:

The integration should work then.

### Actual behavior:

The integration doesnt work with error.

### Relevant logs:
```
mockup.png:1 GET https://rocket.chat/images/mockup.png 404 ()
Image (async)
t._insertNodeWithHooks @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t._insert @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t.attach @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t._insert @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t.attach @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t.setMembers @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
t @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
e.nonreactive @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
t @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
e._withTemplateInstanceFunc @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
f._withCurrentView @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
nrr:materialize @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:79
e.Computation._compute @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
e.Computation._recompute @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
e._runFlush @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
e @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:3
postMessage (async)
u @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:3
h @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
e.Computation.invalidate @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
e.Dependency.changed @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:31
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:63
runTask @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:3
flush @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:3
drain @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:3
b.update @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:63
update @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:69
o.(anonymous function) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
A.each.A.forEach @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:1
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
A.each.A.forEach @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:1
_performWrites @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
_flushBufferedWrites @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
_livedata_result @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
r @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
(anonymous) @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
A.each.A.forEach @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:1
t.socket.onmessage @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
r.dispatchEvent @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
C._dispatchMessage @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
C._didMessage @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55
r.ws.onmessage @ ff1111f2e4db1a16f58dfc6084003c97ad56cb22.js?meteor_js_resource=true:55

```
```
[34mI20171103-11:31:00.096(1) Exception in defer callback: TypeError: Cannot read property '0' of undefined   at parseMessageText (/opt/rocket.chat/rocket.chat/programs/server/packages/rocketchat_lib.js:1863:41)   at /opt/rocket.chat/rocket.chat/programs/server/packages/rocketchat_lib.js:2040:18   at /opt/rocket.chat/rocket.chat/programs/server/packages/rocketchat_lib.js:316:25   at Array.reduce (native)   at Object.RocketChat.callbacks.run (/opt/rocket.chat/rocket.chat/programs/server/packages/rocketchat_lib.js:309:6)   at /opt/rocket.chat/rocket.chat/programs/server/packages/rocketchat_lib.js:3329:31   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at packages/meteor.js:445:51   at runWithEnvironment (packages/meteor.js:1180:24) 
```

Thank you very much.
Kind regards,
Marvyn

**Comment by graywolf336** [comment]
@SeanPackham @geekgonecrazy  we need this on the website server, as there are too many servers out there depending on this location. Or at least a server redirect to it being stored somewhere else

**Comment by geekgonecrazy** [comment]
Done!

**Comment by hExPY** [comment]
Hi @greywolf336 the images appeared. Thanks for it but the error still exists. I thought it been triggered through the missing Image.

**Comment by hExPY** [comment]
<img width="1020" alt="bildschirmfoto 2017-11-05 um 10 46 53" src="https://user-images.githubusercontent.com/8867063/32413656-ad506134-c216-11e7-8f44-b9eebc83ea9c.png">
This happen after i click on save (when the script is enabled).

**Comment by graywolf336** [comment]
That's because your script is invalid and that is the error being shown. Please see: https://docs.rocket.chat/administrator-guides/integrations/

**Comment by hExPY** [comment]
Hi @graywolf336 ,

even when I use the example script from the Doc site, I get the error shown above.

Kind regards,

**Comment by hExPY** [comment]
Hi @graywolf336 ,

can you help out with https://github.com/RocketChat/Rocket.Chat/issues/8788 ?
The error still exists but even after fixing the image source and using a valid script, it's still broken with the same error.

Kind regards,
