### ISSUE TITLE
Unable to upload files with multi-instance setup

### ISSUE THREAD

**Issue by joshuaspence** [RocketChat/Rocket.Chat#9174]
### Description:

I am seeing the same problem that was originally described in #6926 using RocketChat 0.59.3. We are running three RocketChat instances and have correctly configured `INSTANCE_IP` and `PORT` to allow for broadcast.

![rocketchat](https://user-images.githubusercontent.com/234676/34133728-7e69da24-e4aa-11e7-8ddf-ed67b6a34a74.png)

![broadcast](https://user-images.githubusercontent.com/234676/34133790-e388fa2a-e4aa-11e7-940c-64ed2c607f4f.png)

We have configured RocketChat using the following environment variables:

```
INSTANCE_IP=10.52.0.101
MONGO_URL=mongodb://mongodb.service.consul/rocketchat?replicaSet=rs0
MONGO_OPLOG_URL=mongodb://mongodb.service.consul/local?replicaSet=rs0
PORT=8080
ROOT_URL=REDACTED
SETTINGS_BLOCKED=Accounts_AllowEmailChange,Accounts_AllowUsernameChange,Accounts_OAuth_Google_callback_url,Accounts_OAuth_Google_id,Accounts_OAuth_Google_secret,Accounts_RegistrationForm,Accounts_AllowAnonymousRead,Accounts_AllowedDomainsList,Accounts_OAuth_Dolphin,Accounts_OAuth_Drupal,Accounts_OAuth_Facebook,Accounts_OAuth_Github,Accounts_OAuth_GitHub_Enterprise,Accounts_OAuth_Gitlab,Accounts_OAuth_Google,Accounts_OAuth_Linkedin,Accounts_OAuth_Meteor,Accounts_OAuth_Proxy_host,Accounts_OAuth_Proxy_services,Accounts_OAuth_Twitter,Accounts_OAuth_Wordpress,Accounts_RegistrationForm_SecretURL,CAS_base_url,CAS_enabled,CAS_login_url,CAS_version,CROWD_Enable,CustomSounds_Storage_Type,Direct_Reply_Debug,Direct_Reply_Enable,Direct_Reply_Host,Direct_Reply_IgnoreTLS,Direct_Reply_Password,Direct_Reply_Port,Direct_Reply_Protocol,Direct_Reply_Username,EmojiUpload_Storage_Type,FileUpload_S3_Acl,FileUpload_S3_AWSAccessKeyId,FileUpload_S3_AWSSecretAccessKey,FileUpload_S3_Bucket,FileUpload_S3_BucketURL,FileUpload_S3_CDN,FileUpload_S3_ForcePathStyle,FileUpload_S3_Region,FileUpload_S3_SignatureVersion,FileUpload_S3_URLExpiryTimeSpan,FileUpload_Storage_Type,Force_SSL,From_Email,IRC_Enabled,IRC_Host,IRC_Port,Jitsi_Enabled,LDAP_Enable,SlackBridge_Enabled,Smarsh_Email,Smarsh_Enabled,Smarsh_Interval,Smarsh_MissingEmail_Email,Smarsh_Timezone,SMS_Enabled,SMS_Service,SMTP_Host,SMTP_IgnoreTLS,SMTP_Password,SMTP_Pool,SMTP_Port,SMTP_Protocol,SMTP_Username,Site_Url
SETTINGS_HIDDEN=Accounts_OAuth_Google_secret,Accounts_RegistrationForm_SecretURL,FileUpload_S3_AWSSecretAccessKey
OVERWRITE_SETTING_Accounts_AllowAnonymousRead=false
OVERWRITE_SETTING_Accounts_AllowedDomainsList=REDACTED
OVERWRITE_SETTING_CustomSounds_Storage_Type=GridFS
OVERWRITE_SETTING_Direct_Reply_Enable=false
OVERWRITE_SETTING_EmojiUpload_Storage_Type=GridFS
OVERWRITE_SETTING_FileUpload_S3_Acl=private
OVERWRITE_SETTING_FileUpload_S3_Bucket=REDACTED
OVERWRITE_SETTING_FileUpload_S3_Region=us-west-2
OVERWRITE_SETTING_FileUpload_Storage_Type=AmazonS3
OVERWRITE_SETTING_Force_SSL=true
OVERWRITE_SETTING_From_Email=REDACTED
OVERWRITE_SETTING_IRC_Enabled=false
OVERWRITE_SETTING_Jitsi_Enabled=false
OVERWRITE_SETTING_SMTP_Host=smtp_relay.service.consul
OVERWRITE_SETTING_SMTP_IgnoreTLS=true
OVERWRITE_SETTING_SMTP_Port=25
OVERWRITE_SETTING_Accounts_AllowEmailChange=false
OVERWRITE_SETTING_Accounts_AllowUsernameChange=false
OVERWRITE_SETTING_Accounts_OAuth_Google=true
OVERWRITE_SETTING_Accounts_OAuth_Google_id=REDACTED
OVERWRITE_SETTING_Accounts_OAuth_Google_secret=REDACTED
OVERWRITE_SETTING_Accounts_RegistrationForm=Disabled
OVERWRITE_SETTING_FileUpload_S3_AWSAccessKeyId=REDACTED
OVERWRITE_SETTING_FileUpload_S3_AWSSecretAccessKey=REDACTED
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): TAR
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: 4.8

### Steps to Reproduce:

1. Attempt to upload a file in a private chat. I have been using the following file for testing purposes:
 [test.txt](https://github.com/RocketChat/Rocket.Chat/files/1569821/test.txt)
2. Repeat step 1 multiple times as the bug does not always reproduce (I'm guessing it depends on which backend the request is made to).

### Expected behavior:

The file to be successfully uploaded.

### Actual behavior:

2 out of 5 uploads (of the same file) failed with "Internal server error [500]"

### Relevant logs:

```
[34mI20171218-23:57:00.185(0) Exception while invoking method 'ufsComplete' Error: ENOENT: no such file or directory, open '/tmp/ufs/GqhAai75TtRZMrQtK'   at Object.Future.wait (/opt/rocketchat/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/opt/rocketchat/programs/server/packages/jalik_ufs.js:817:24)   at [object Object].methodsMap.(anonymous function) (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/opt/rocketchat/programs/server/packages/ddp-server.js:1857:12)   at /opt/rocketchat/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /opt/rocketchat/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /opt/rocketchat/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/opt/rocketchat/programs/server/packages/ddp-server.js:874:21)   at /opt/rocketchat/programs/server/packages/ddp-server.js:753:85      - - - - -   at Error (native)  
[34mI20171218-23:57:02.853(0) Exception in callback of async function: Error: Future resolved more than once   at Object.Future.throw (/opt/rocketchat/programs/server/node_modules/fibers/future.js:292:10)   at /opt/rocketchat/programs/server/packages/jalik_ufs.js:797:34   at runWithEnvironment (packages/meteor.js:1188:24)   at AmazonS3Store.<anonymous> (packages/meteor.js:1201:14)   at /opt/rocketchat/programs/server/packages/jalik_ufs.js:1968:34   at runWithEnvironment (packages/meteor.js:1188:24)  
[34mI20171218-23:57:32.571(0) Exception while invoking method 'ufsComplete' Error: ENOENT: no such file or directory, open '/tmp/ufs/zWAt5BYCX3n8NbxwK'   at Object.Future.wait (/opt/rocketchat/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/opt/rocketchat/programs/server/packages/jalik_ufs.js:817:24)   at [object Object].methodsMap.(anonymous function) (/opt/rocketchat/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/opt/rocketchat/programs/server/packages/ddp-server.js:1857:12)   at /opt/rocketchat/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /opt/rocketchat/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /opt/rocketchat/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/opt/rocketchat/programs/server/packages/ddp-server.js:874:21)   at /opt/rocketchat/programs/server/packages/ddp-server.js:753:85      - - - - -   at Error (native)
```

**Comment by joshuaspence** [comment]
Setting a sticky session cookie in the load balancer seems to fix it, but this isn't an ideal solution.

**Comment by geekgonecrazy** [comment]
Can you take a look at your chrome Dev console?  Goto network tab and upload until it fails... Then look at the headers on that request that failed.  There should be an instance Id header on there.  

Would probably be useful for debugging to see if it's only one instance that has issues or if it's multiple instances?

**Comment by AmShaegar13** [comment]
Are instances able to connect to each other directly on port 8080? You could verify that using telnet:

```
$ telnet 10.52.0.142 8080
$ telnet 10.52.0.101 8080
```

**Comment by joshuaspence** [comment]
I think I figured it out.... it seems that this occurs when Force SSL is enabled.

**Comment by joshuaspence** [comment]
Yep, this definitely seems to be caused by Force SSL being enabled. In our setup, there is no reverse proxy. We have an AWS ALB sitting in front of RocketChat and perform SSL termination at the ALB (so the ALB talks to RocketChat itself using plain old HTTP). We aren't running a reverse proxy on the RocketChat instances.

**Comment by geekgonecrazy** [comment]
Makes sense.  We tried to include a warning there about things breaking.  Usually it's the case of people locking them selves out though

**Comment by joshuaspence** [comment]
Can we ignore Force SSL for this type of proxy request?

**Comment by geekgonecrazy** [comment]
Hm.. that sounds great in theory.. but we are forcing ssl at low level.  Not sure how easy.

Any reason not forcing upgrade at ALB level.

Disclaimer never used ALB but most other competing products seem to support this functionality

**Comment by joshuaspence** [comment]
As far as I know, it can't be done.

**Comment by joshuaspence** [comment]
Any update on this issue?

**Comment by geekgonecrazy** [comment]
I believe is likely resolved in the latest update.  Changes were made to that in 0.62.0. So I'd recommend giving 0.62.1 a try

**Comment by geekgonecrazy** [comment]
Please give that a try and we can re-open if persists

**Comment by joshuaspence** [comment]
Definitely not fixed. Can you point to the PR that was meant to fix this?

```
Mar 08 23:48:15 ip-10-52-1-183 node[11099]: { RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.extractError (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:577:35)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at callNextListener (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at IncomingMessage.onEnd (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:269:13)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at emitNone (events.js:111:20)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at IncomingMessage.emit (events.js:208:7)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at endReadableNT (_stream_readable.js:1064:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   message: 'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.',
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   code: 'RequestTimeout',
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   region: null,
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   time: 2018-03-08T23:48:15.160Z,
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   requestId: '3E9874E53FD67253',
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   extendedRequestId: 'xu94bpeHVIQpwEfxjP9/P1xoj4XpYHWLjbsg8cEUnGmjZwIEoYPEJfaj97wuGt1veDUbqhhKEXs=',
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   cfId: undefined,
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   statusCode: 400,
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:   retryable: true }
Mar 08 23:48:15 ip-10-52-1-183 node[11099]: Exception while invoking method 'ufsComplete' NoSuchKey: The specified key does not exist.
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.extractError (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:577:35)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at callNextListener (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at IncomingMessage.onEnd (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:269:13)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at emitNone (events.js:111:20)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at IncomingMessage.emit (events.js:208:7)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at endReadableNT (_stream_readable.js:1064:12)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 08 23:48:15 ip-10-52-1-183 node[11099]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]: Error: FileNotFound: no file with id HpiKnuMraJzhMR2k7 found
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at handleCallback (/opt/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]: { AccessDenied: Access Denied
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.extractError (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/services/s3.js:577:35)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.emit (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.transition (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at AcceptorStateMachine.runTo (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at /opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.<anonymous> (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at Request.callListeners (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at callNextListener (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at IncomingMessage.onEnd (/opt/rocketchat/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:269:13)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at emitNone (events.js:111:20)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at IncomingMessage.emit (events.js:208:7)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at endReadableNT (_stream_readable.js:1064:12)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   message: 'Access Denied',
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   code: 'AccessDenied',
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   region: null,
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   time: 2018-03-08T23:51:03.389Z,
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   requestId: 'BF8CE0CEF8DA8DC7',
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   extendedRequestId: '6x8e8XgrtMk0s5hIob58j6Ep/OQ62rIt0ZmTTU6WAqKEx+X5w8UL88UzB8fTU3IFDN/+Lk7owfA=',
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   cfId: undefined,
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   statusCode: 403,
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   retryable: false,
Mar 08 23:51:03 ip-10-52-1-183 node[11099]:   retryDelay: 40.96938906825465 }
```

**Comment by joshuaspence** [comment]
I tried again today and got a different error:

```
Mar 12 02:56:21 ip-10-52-1-122 n[30322]: Exception in callback of async function: Error: socket hang up
Mar 12 02:56:21 ip-10-52-1-122 n[30322]:     at createHangUpError (_http_client.js:331:15)
Mar 12 02:56:21 ip-10-52-1-122 n[30322]:     at Socket.socketCloseListener (_http_client.js:363:23)
Mar 12 02:56:21 ip-10-52-1-122 n[30322]:     at emitOne (events.js:121:20)
Mar 12 02:56:21 ip-10-52-1-122 n[30322]:     at Socket.emit (events.js:211:7)
Mar 12 02:56:21 ip-10-52-1-122 n[30322]:     at TCP._handle.close [as _onclose] (net.js:554:12)
```

It looks like it sorta works, but the behavior is completely broken. I think this is what is happening:

  1. Initial file chunk is sent to instance A.
  2. Subsequent file chunks are sent either to instance A, B or C. If you are lucky, every chunk of the file will be sent to instance A and the file will have been uploaded seamlessly. The chance of this happening, however, is `(1/N)^k` (uploading a file consisting of `k` chunks to `N` instances).
  3. If a subsequent file chunk is sent to the wrong instance (i.e. instance B or instance C), an `EPIPE` error is logged server-side and the connection sits idle. Eventually, the connection will time out and the client will get a 504 (in our case, the load balancer terminated the idle connection after 60 seconds).
  4. After receiving a 504 response from the server, the client tries again, repeating steps 2-3.

**Comment by geekgonecrazy** [comment]
I think to solve this we should switch to use our new restful API.  That way chunks aren't being sent over the websocket.

**Comment by maxdwit** [comment]
@joshuaspence @geekgonecrazy Interesting. This still happens with the most current version.
I had to disable uploading for the moment.

**Comment by Ishrat1401** [comment]
Tested - this issue can't be replicated now. I assume this is fixed, hence closing it.
